### ISSUE TITLE
fix bugs in updated site

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1008]
- make menu directly expand below 'about' in the menu bar

<img width="311" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/66872140-283a-4a62-a7a5-ca2217d31606">

- generate recently pub. articles from fourth-level hierarchy (not third)

<img width="297" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/34f42be8-fcd2-4db1-bf2e-74abee37cf97">

**Comment by thierrylahaije** [comment]
@hannesdatta issues tackled in branch bugs-optimizing.
