### ISSUE TITLE
#flask: webstructure issues SEO

### ISSUE THREAD

**Issue by thierrylahaije** [tilburgsciencehub/website#1020]
Hi @hannesdatta,

I uploaded [report](https://github.com/tilburgsciencehub/website/files/13867612/Report.pdf) about the current website structure. All blue items can be dismissed since they are not really important, but the red & orange items are severe SEO issues impacting our position in SE's, and so affect our organic traffic. Most of them are (as I expected) dead links, pages that need redirects, double titles and missing alt attributes. 

Would you like me to take care of these issues? We could also fix all the links first, and then update the structure of for example 10 pages to measure what the affect is on our web traffic?

**Comment by hannesdatta** [comment]
Yes! Please fix all these issues.

**Comment by marijnbransen1998** [comment]
@thierrylahaije I sent you some files to fix redirects!

**Comment by thierrylahaije** [comment]
There is quite a lot of content to fix. What i suggest is that i write a script that reports the following:

- Broken images 
- Double titles
- Too long titles
- Empty meta description
- Double meta descriptions
- Too long meta description 
- Empty alt text

These are currently the main on page issues with our SEO. By creating a script, in the future, other students can easily check in the report what could be done to the on page SEO to improve the organic traffic. This is an easy task which you could delegate to other RA's as well which are not very familiar with SEO. In this way, you could choose yourself whether you invest time and resources in SEO.

@hannesdatta Would you like me to proceed with this script?

**Comment by hannesdatta** [comment]
Yes, please go ahead.

Ideally, we run it weekly with GitHub actions and create an issue with a report attached.

@marijnbransen1998 has moved on to another job. @thierrylahaije can handle this issue for now.

**Comment by thierrylahaije** [comment]
I created and added the SEO Script and the action to run it. We still need to adjust the AWS settings

For that, I the access key from an IAM user with read/write access to s3 buckets. Furthermore I need the name and region of the AWS bucket. After that, everything is set.

Meanwhile, I am still expanding the excel file to contain more extended information.
