### ISSUE TITLE
Shiny App for marketing research with code

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#1024]
Would love to see a marketing equivalent of this: 

http://econ.mathematik.uni-ulm.de:3200/ejd/
https://github.com/skranz/EconJournalData

But with better search features. Can imagine it being quite useful

**Comment by hannesdatta** [comment]
This is indeed super cool, but prob beyond reach right now given time constraints. I leave this issue open so we can revisit at a later time.
