### ISSUE TITLE
Duplicate contributions on contributor pages

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#1044]
Redirect from #1040

Hi @thierrylahaije !

Today I've noticed on my contributor's page that each of my contributions appear twice on the [website](https://tilburgsciencehub.com/contributors/fernandoiscar/). I opened a new branch thinking I should modify something in the markdown file, but seems it may be a rendering issue, as I don't see any error.

**Comment by hannesdatta** [comment]
<img width="459" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/bff75688-7477-4f42-9b5b-27b0b499823d">

**Comment by hannesdatta** [comment]
e.g., https://tilburgsciencehub.com/contributors/nielsrahder/

**Comment by hannesdatta** [comment]
@krzysztof99xd  -  maybe you can also figure out how to solve this issue. Update this issue to let us know your progress. If you need a starter, I'm posting a link to the file where it's going wrong.

**Comment by hannesdatta** [comment]
https://github.com/tilburgsciencehub/website/blob/e6a0657440e5b45ef78d558c47950e99ca67e688/themes/tilburg/layouts/contributors/single.html#L32

**Comment by lachlandeer** [comment]
fixed via #1040
