### ISSUE TITLE
Update left-menu scroll bar

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#105]
**Is your feature request related to a problem? Please describe.**
The current scroll bar doesn't look good and doesn't belong to our current design system. Moreover, even when the scroll bar is not needed (the left-menu is short enough), a white horizontal tab is visible. This is where the bar usually scrolls in.

 
![image](https://user-images.githubusercontent.com/50109671/109668989-f82aaf80-7b71-11eb-8d9b-dda9314d29f1.png)

**Describe the solution you'd like**
Update the scroll bar according to the InVision project. The white tab behind it should disappear. The bar should be moved to the left of the menu.

![image](https://user-images.githubusercontent.com/50109671/109668859-d92c1d80-7b71-11eb-9be3-ca208528c37f.png)

**Comment by andreantonacci** [comment]
Currently, the scroll bar is enabled only for tutorials (it never shows up on building blocks for instance). We want it to be universal, it should appear in long building blocks too. 

However, it must only appear when it's actually needed! If the entire left-menu fits in the user's viewport, then it should not render.

**Comment by heyarviind** [comment]
This is done, just testing is left.

Can you please tell me any article in Building Blocks, where there is scrolling in the table of content section? I can;t find any

**Comment by andreantonacci** [comment]
@heyarviind I think this one has a rather long left menu: https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/write-your-paper/amsmath-latex-cheatsheet/

**Comment by andreantonacci** [comment]
It looks much better, but it still doesn't work as it should, unfortunately.

The problem is still the same one: the table of content is too long and it exceeds my viewport.
![image](https://user-images.githubusercontent.com/50109671/114432948-89556300-9bc1-11eb-96f3-44667fb73981.png)

So, despite having its own scrollbar, to get to end of the table of content I need to scroll down the page a little bit.
Perhaps, the table of content should be smaller, or even better, its height should be dynamic, based on the window size. This way, the bottom margin (I think you call it pseudo spacer) is always visible, even if you scroll to the top of the page.

![Screenshot 2021-04-12 at 19 05 12](https://user-images.githubusercontent.com/50109671/114433470-287a5a80-9bc2-11eb-8298-7003aae94dd5.png)

**Comment by andreantonacci** [comment]
Also, the new scroll bar design doesn't work on Firefox:

![image](https://user-images.githubusercontent.com/50109671/114433758-7c853f00-9bc2-11eb-8a4c-d109c02c8311.png)

**Comment by heyarviind** [comment]
Here is the fix: https://github.com/tilburgsciencehub/website/pull/157

Regarding the firefox issue: firefox [doesn't really support the styling of the scrollbar](https://bugzilla.mozilla.org/show_bug.cgi?id=1513602). I can change the background color and foreground color but for this, [the scrollbar has to always visible on mac OS](https://github.com/mdn/browser-compat-data/pull/3204/files#diff-453dc0601842fad8f6c16769ced904d2ea26088d15d480305875278b7f7a87faR23).

**Comment by andreantonacci** [comment]
Make the TOC even shorter taking into account the breadcrumb trails at the top, so that it fits on the page even when fully scrolled up. Thanks

**Comment by andreantonacci** [comment]
Yes! Way better thanks. I'd make it even shorter, so that the margin below the TOC is equal to the margin above. Please, set .TableOfContents max-height: calc(100vh - 430px);

**Comment by andreantonacci** [comment]
awesome, thanks

**Comment by andreantonacci** [comment]
Opening again because hard coding the height (calc(100vh - 430px);) works fine for most of our articles, but not always.

That's because most of the time our titles (h1.text-center text-lg-left) take two line of text. However, sometimes they can take 3 or more. For instance, on this page (https://tilburgsciencehub.com/learn/project-setup) "Principles of Project Setup and Workflow Management", takes three lines and therefore pushes the TOC down, resulting in a smaller margin below the TOC.

Is there a way to avoid hard coding 430px and calculating the height taking into consideration the title height too?

![image](https://user-images.githubusercontent.com/50109671/115267173-29b70480-a139-11eb-8641-c063336ebaa7.png)

**Comment by heyarviind** [comment]
I removed the calc and added the flexbox but it still needs the top offset... 

is this okay, I have added the bottom margin.... now it doesn't matter how many lines do title has.. it will adjust automatically 

![Screenshot 2021-04-20 at 4 18 19 PM](https://user-images.githubusercontent.com/21043614/115383927-0735f180-a1f4-11eb-85fa-25c48e6a183c.png)

**Comment by andreantonacci** [comment]
It looks perfect Arvind, thanks
