### ISSUE TITLE
Request for Articles on Time Series Data Analysis in R

### ISSUE THREAD

**Issue by MatthijstenTije** [tilburgsciencehub/website#1050]
**Title**: _Request for Articles on Time Series Data Analysis in R_

**Description**:
I am proposing the creation of a set of articles focused on handling, analyzing, and visualizing time series data in R. The goal is to produce a set of articles that covers different aspects of time series data manipulation and analysis, using popular R packages. The articles should be self-contained, allowing readers to benefit from each independently, while also complementing each other when “read as a series”.

**Deliverables**:
1. _Manipulating Time Series Data in R with xts & zoo_
- Objective: Introduce the xts and zoo packages as powerful tools for managing time series data in R. Cover basic to intermediate techniques for data manipulation and cleaning, tailored specifically for time series analysis.
- Key Topics:
        - Introduction To XTS objects
	- Basic Manipulations
	- Merging and modifying time series
	- Apply and Aggregate by time
	- Periods, Periodicity and Timestamps
- Expected Outcome: Readers will gain proficiency in using xts and zoo packages for manipulating time series data, preparing them for further analysis or visualization.

2. _Visualizing Time Series Data_
- Objective: Guide readers through the basics of time series data visualization in R, emphasizing the use of the plot function along with its options.
- Key Topics:
    - 	Introduction to time series visualization principles.
    - Detailed exploration of the plot function tailored for time series data.
    - Customizing plots: adjusting types, colors, labels, and adding legends.
    - Demonstrating the application of visualization techniques on time series data using real-world examples. Probably Stocks, to connect the website more to the Finance studies.
- Expected Outcome: Readers will learn how to effectively visualize time series data, enhancing their analytical and presentation skills.

3. _Univariate Time Series Data Analysis Visualizations_
- Objective: Expand on the visualization theme by focusing on univariate time series analysis. This piece will explore more specialized plots such as qqplots, autocorrelation plots, histograms, and boxplots, providing readers with a toolkit for comprehensive time series data analysis.
- Key Topics:
     - Overview of univariate time series analysis.
     - Guide on creating and interpreting qqplots, autocorrelation plots, histograms, and boxplots for time series data.
     - Best practices for analyzing and visualizing univariate time series data.

- Expected Outcome: Readers will be equipped with advanced visualization techniques for in-depth time series data analysis, enabling them to uncover more insights from their data.

**Comment by hannesdatta** [comment]
1) @MatthijstenTije  - could you check whether `zoo` is still the best in town? Found it very slow on large data sets a few years ago.
2) Please do 2 - visaulizing time series - using ggplot and spend attention on grouping and facets. 
3) Not so fond of this - a bit boring/not state of the art. Would put it low on the prio list but gather a few thoughts and what would have to be done if you're done with 1 & 2. 

@lachlandeer can give you definite go's. This is just feedback.
