### ISSUE TITLE
Article: Machine Learning 101

### ISSUE THREAD

**Issue by Lisa-Holling** [tilburgsciencehub/website#1052]
## Machine Learning 101 BB

I noticed there's a lack of info on very basic machine learning content (ML Section)
I think it could be useful to write a short BB on the very basic machine building theory
Talk about concepts such as:
* Classification vs. regression
* Supervised vs. unsupervised
* Data splits: training-test
* R vs. Python 
* Etc.

**Comment by Lisa-Holling** [comment]
@lachlandeer can I start working on this? Any comments/suggestions before I start?

**Comment by lachlandeer** [comment]
Thanks for this @Lisa-Holling 

Looks good. Perhaps don;'t go int othe R vs Python debate, but mention can be done on either. (ideally by end of semester we have articles on each that flesh this out a bit more)

Lachlan

PS. if i don't respond in a week, drop me a note somewhere - I get tonnes of GH notifications and some fall through the cracks
