### ISSUE TITLE
Update the share preview

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#108]
**Describe the bug**
When sharing any link from the website on social media or messaging apps, there's no preview rendered. The title is ALWAYS "Tilburg Science Hub" regardless of which page is being shared (see also #102). The description metadata and the preview images are also missing.

**To Reproduce**
1. See on https://socialsharepreview.com/?url=https://tilburgsciencehub.com

**Expected behavior**
Each page should render a unique share preview, with a specific title (the article title), a description and a generated preview image.

**Comment by andreantonacci** [comment]
Please improve the SEO of every page. Title, meta description, meta content type, keywords should all work.

**Comment by heyarviind** [comment]
Can you get the image from your designer? or just tell me what content do you want to show on the image and I can create it in figma.

**Comment by andreantonacci** [comment]
We don't want to show the same image for every page. Ideally, every page has a unique and generated preview image, like a screenshot of that page. 

Alternatively, we can manually add an image that we want for the preview and specify it in the front matter. If we don't include one for a certain page, then a fallback image should be used - a standard one for the entire website - for instance, the homepage one.

What do you say?

**Comment by heyarviind** [comment]
sure you can add the image path in markdown with the key `og-image` and I will add this in the header of the page. If this key is not present then I will pick the fallback image

**Comment by heyarviind** [comment]
could you share the common image for now? so that we can test it

**Comment by andreantonacci** [comment]
@heyarviind I will provide you with the fallback image. But I can't see this your temporary one when sharing the links. Probably there's a typo in the og:image link: https://tilburgsciencehub.comimg/default-og-image.png

**Comment by andreantonacci** [comment]
I can now see the fallback image, thanks.How can we specify a specific og:image for a certain page? can we use og-image in the front matter in markdown? Is this already implemented? Thanks

**Comment by heyarviind** [comment]
yes, you have to use ogimage: imgaename.jpg... it has been implemented

**Comment by heyarviind** [comment]
please keep in mind its ogimage not og-image 😬

**Comment by andreantonacci** [comment]
great job, thanks
