### ISSUE TITLE
Alumni at contributors look a question(mark)able :) 

### ISSUE THREAD

**Issue by alexandervossen** [tilburgsciencehub/website#1081]
https://tilburgsciencehub.com/contributors/

<img width="897" alt="Screenshot 2024-02-21 at 09 24 39" src="https://github.com/tilburgsciencehub/website/assets/79662088/8938ceb4-2e45-49cc-b173-4bf29a5947ca">

@thierrylahaije  - accessed via Safari Version 17.2.1

**Comment by lachlandeer** [comment]
same for me! (Chrome, v121.0.XX)

**Comment by thierrylahaije** [comment]
@alexandervossen @lachlandeer Thanks for noticing! I fixed the bug and it can now be merged.
