### ISSUE TITLE
Building block on R Markdown

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1086]
We may already cover some markdown basics. Yet, with markdown, you can do so much more.

Here's a great cookbook I discovered.

https://bookdown.org/yihui/rmarkdown-cookbook/

Can we highlight some advanced use cases of markdown in R? E.g., pagebreaks, citations, numbered figures, formatting and advanced latex output?

**Comment by MatthijstenTije** [comment]
Hello @hannesdatta, I can work on this if that is possible. If so, do you have specific examples in mind on the advanced use cases you'd like to focus on? Additionally, how would you prefer the article to be structured?

**Comment by MatthijstenTije** [comment]
@hannesdatta 
Pushed a first draft within the branch. Happy to hear your thoughts about it.
