### ISSUE TITLE
Share buttons do not appear on mobile

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#109]
**Describe the bug**
The share buttons are only visible from desktop.

![image](https://user-images.githubusercontent.com/50109671/109800340-52cd1580-7c1d-11eb-9eb5-e2b5577330b2.png)

**Expected behavior**
They should appear from mobile too.

**Comment by heyarviind** [comment]
fixed

**Comment by andreantonacci** [comment]
They now appear on mobile too, but they are too big so the newly added copy button is on a new line. Please resize the icons just enough to make them all fit on one line, thanks.

![IMG_495406271EF8-1](https://user-images.githubusercontent.com/50109671/114431864-4646c000-9bc0-11eb-9aeb-865541534b94.jpeg)

**Comment by heyarviind** [comment]
oops it should not be in review in first place sorry for that... i was working on it...

**Comment by andreantonacci** [comment]
Closing, but please update their alignment. See #110 
https://github.com/tilburgsciencehub/website/issues/110#issuecomment-820287119
