### ISSUE TITLE
Article request: getting started with Tilburg's GitLab

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1091]
__Background:__ Tilburg has a gitlab server and it's amazing. Has so many features like Github, including Continuous Development/"Actions", etc.

I foresee a lot of demand for an article explaining the use. Compared to GitHub, gitlab requires users to set up an authentication token and that's super hard to set up for newbees. 

Can you please develop an article, 
1) explaining the fetaures of gitlab.uvt.nl,
2) explaining how to login in the interface and link to existing buildingblocks on git/github
3) explaining how to set up SSH keys and access
4) explaining hwo tolink gitlab to RStudio, VS code, and using it from the command prompt/terminal.

Thanks a bunch!

Something for @krzysztof99xd or @arutyunovv. If you don't have capacity, let us know so we can reassign.

**Comment by krzysztof99xd** [comment]
Hey @hannesdatta, 
Apologies for coming back late. It is a great idea! I was using GitLab during my Bachelor's. 
I would like to take it. For the heads up, realistically looking at that article, I could finish it in around 3-4 weeks. First I would like to help Thierry with finishing issues for website-flask repository.
Is the given time frame fine?
