### ISSUE TITLE
adding latex template to master thesis guide

### ISSUE THREAD

**Issue by Lisa-Holling** [tilburgsciencehub/website#1098]
I wanted to add the [latex thesis template](https://tilburgsciencehub.com/topics/research-skills/templates-dynamic-content/templates/latex-templates/) to the [Prepare for your Master Thesis](https://tilburgsciencehub.com/topics/research-skills/writing/writing-process/preparation/) page.

**Comment by alexandervossen** [comment]
@Lisa-Holling I think it would be great to integrate that as part of #1097 . See also @lachlandeer comment in there. Also @kleintob has hinted he has a template. So I think its just bundling/updating some existing stuff. Great!
