### ISSUE TITLE
remove/fix duplicates in search

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1109]
Our search is showing duplicates. Fix when we have moved to Flask, please.

<img width="354" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/ac05f97f-71b9-4404-8e8c-5de0b47060cd">

**Comment by thierrylahaije** [comment]
The duplicates in between these items are files that are either placed in two categories or two articles have the same title. 

E.g.

Set up Docker: is the of two separate articles.
Import and run...: this article is placed in two different categories.

Therefore, if there still are duplicates in the search, we need to adjust the .md files

**Comment by hannesdatta** [comment]
Thanks for letting me know.

__Deliverable:__

- We will NOT adjust the .md files (will likely break again in the future). 
- Instead, please ensure that only unique articles are shown on the search result page. You could do that by retaining the original file name in some meta data json dictionary before showing that list, and then dropping all duplicate entries. As we base the uniques on the original path + filename of the .md file, we will always show complete results.

**Comment by thierrylahaije** [comment]
Issue now fixed and merged in PR #1270. All duplicates are automatically removed and not shown.
