### ISSUE TITLE
Title: Use k-fold cross-validation to prevent overfitting

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1111]
Title: Use k-fold cross-validation to prevent overfitting

Overfitting is well-known issue of many predicting models which makes the model have issues with generalization. The concept fits well at our lack of 'analyse the data' building blocks. We can explain how to detect overfitting and how we can change the parameters to prevent it.

_Originally posted by @casruger in https://github.com/tilburgsciencehub/website/issues/578#issuecomment-1354725896_

**Comment by hannesdatta** [comment]
@Fernando-Iscar - see this new content dev request. you're overseeing the ML content creation right now, correct? Maybe something to spend some time on?

**Comment by Fernando-Iscar** [comment]
Hi @hannesdatta, I can take over this BB.
Regarding the ML new content, I thought someone else took the lead, otherwise, I'll be happy to take it over. 
I'll bring it up in the next Wow to clarify it anyways.

**Comment by hannesdatta** [comment]
Thanks, @Fernando-Iscar. Please clarify who's the ML lead here - just to make sure I know whom to tag. Or was it @srosh2000?

**Comment by hannesdatta** [comment]
I any case, i think i would prefer if I could both tag you and Roshini where I see fit, so that you can in turn steer other, more junior RAs. Sounds good?

**Comment by srosh2000** [comment]
@hannesdatta I'm leading the causal inference circle. I thought @Fernando-Iscar could lead the RAs working on ML related content to make things more manageable? But yes feel free to tag us both wherever needed.

**Comment by hannesdatta** [comment]
Good like this! Thanks!

**Comment by lachlandeer** [comment]
See #1167
