### ISSUE TITLE
update installation of docker on Windows

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1139]
__Context:__
- We will soon see many new users of Docker on Windows.
- We need to provide easy ways to install docker.

__Deliverables:__
- Please identify our building block for how to install Docker on Windows
- Add the following way of installing docker to it.
- If you feel this is easier than the regular install, make it the primary way and degrade the other one.

> - als je docker-desktop installeert op windows vraag hij of hij moet integreren met WSL, de dockerd draait dan ook in een eigen WSL omgeving (zijn een soort van mini-vm's)
> - + dat de WSL waar mensen in werken dan ook docker commando's tegen die docker instantie kunnen draaien
> - dus WSL erop, docker-desktop erop en dan kun je vanuit zowel WSL als windows terminal docker gebruiken

Thanks!

@Fernando-Iscar - please distribute to some docker person on our team or test w/ a newbee (they will have to learn installing docker anyways, e.g., @Lisa-Holling).

**Comment by Fernando-Iscar** [comment]
I'll assign @arutyunovv for now, as he's interested in learning Docker, potentially using it in for his thesis.

**Comment by Fernando-Iscar** [comment]
@arutyunovv 
The article to update is [this one](https://tilburgsciencehub.com/topics/automation/replicability/docker/install_docker/)
