### ISSUE TITLE
improve next/previous navigation

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#114]
**Is your feature request related to a problem? Please describe.**

I'm frustrated when I have to click on the button, rather than on next.

![image](https://user-images.githubusercontent.com/16557730/110627025-c2a14a00-81a1-11eb-999b-d91adaa2ae95.png)

**Describe the solution you'd like**

Make "next" and "previous" clickable

**Describe alternatives you've considered**

- Remove the labels next and previous (the arrows should tell enough, right)?
- Integrate the word NEXT and PREVIOUS in the yellow arrows.

**Comment by heyarviind** [comment]
umm so what exactly should I do here? should I remove the next and previous label or make them clickable?

**Comment by andreantonacci** [comment]
I don't think that many people experienced similar problems with the buttons so if you can, just make "Previous" and "Next" clickable too, like the buttons below them.
