### ISSUE TITLE
Adding multiple authors: no link to article on contributor pages

### ISSUE THREAD

**Issue by valerievossen** [tilburgsciencehub/website#1148]
Hi @thierrylahaije and @krzysztof99xd ,

@srosh2000 and me encounter an issue when wanting to add two authors to an article. As thierry suggested, we did the following: author: "Roshini Sudhaharan, Valerie Vossen" in the introduction to causal inference (#1129). However,  the article doesn't show up on the contributor page in the local site. (I already tested it with another name, to make sure the issue is not that Roshini doesn't have an own contributor page yet.)

It is a small issue but might become more important as more people start collaborating on topics!
Let me know if one of you knows how to solve it (feel free to assign yourself then)

**Comment by krzysztof99xd** [comment]
Hey @valerievossen,
Thanks for noticing it. I will take a look at it in the upcoming days (at the moment I would like to finish some issues for the website-flask). To clarify, the article does not show up for both authors on the contributor page (so neither for Valerie nor for Roshini) ?

**Comment by valerievossen** [comment]
@krzysztof99xd I will get back to you on this after the PR is merged because my version doesn't include the contributor page yet, not sure why!

**Comment by krzysztof99xd** [comment]
I have found an issue.  The author field in the md file is a string. When we were saving 2 authors, even though they are separated by a coma it is still one string which stands in the field author.  Therefore, at the contributors page when we try to read authors names now we need to check if coma appers  and if so, check that contributor name is there.
