### ISSUE TITLE
Topic: System GMM approach for dynamic panel models

### ISSUE THREAD

**Issue by valerievossen** [tilburgsciencehub/website#1161]
This is a method I probably have to use for my thesis. So if it's something interesting for on the TSH website, I can make an article of it, coverng the basics and giving a code example in R.

**Comment by hannesdatta** [comment]
Good idea! I see it's already scheduled? Ensure to update it's status on the project board.

Thanks!

<img width="333" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/4fde68d5-d650-4d39-9d40-6ed159eb5a1e">

**Comment by valerievossen** [comment]
Hi @alexandervossen, 

I drafted an outline for the topic about dynamic panel data estimation with System-GMM, with each section and some extra points of clarification. Any suggestions are welcome! I would like to ensure that this topic is relevant for the audience of the TSH website before I continue with properly writing it. I think it is, but it's good to confirm with someone from the core team! :)

1. Overview
    - Introduce topic
    - Motivation why dynamic panel models are relevant; e.g. many economic relationships are dynamic in nature
    
2. Dynamic panel data model
    - Capturing the persistence of dependent variable over time periods
    - Provide a simple regression equation of the dynamic panel model (Lag of dependent variable included on the right-hand side)

3. Nickel Bias
    - How does this bias arise? Correlation of lagged dep. var with error term by construction
    - What are the consequences? Standard panel data estimators (FE, RE, FD) will be inconsistent, (especially short time series with large N) 

4. Estimation with System-GMM  
    - Brief theoretical introduction on what it is, still focusing on the practical intuition, without going into too much mathematics
    - Instruments used for the lagged dependent variable from the second and third lags
    - System-GMM: Lagged levels as well as lagged differences used as instruments

5. Example in R with 'pgmm()' from plm package
    - Adapt example from here: https://rdrr.io/cran/plm/man/pgmm.html
    - Interpretation of output
    - Tests and diagnostics
        - Sargan test
        - AR test for autocorrelation of residuals

**Comment by alexandervossen** [comment]
Looks great! A few smaller things here and there: 
1. I would also include how they differ from "traditional" panel models and why that difference matters. 
2. I think you could use the opportunity to also talk a bit about instrument validity. There is a great chance to give a shoutout to this, in my mind, really nice paper[here](https://www.sciencedirect.com/science/article/pii/S1048984322000765).
3. Maybe include a shoutout to your other panel model content in an info box and compare to give the readers and intiution on when to use what. Cool!
