### ISSUE TITLE
Images not rendering in dynamic reports section

### ISSUE THREAD

**Issue by MatthijstenTije** [tilburgsciencehub/website#1189]
Images inside the ../content/topics/Research-skills/templates-dynamic-content/dynamic-reports directory are not rendering properly. Despite my efforts, I can't identify the problem's root cause. Any assistance to render the image properly or insights into what might be causing this problem would be appreciated.

Example of a code snippet inside the article:

```
<p align = "center">
<img src = "../images/citation-rmarkdown.png" width="300">
</p>
```

and the image name in the images folder:
citation-rmarkdown.png

**Comment by valerievossen** [comment]
I will try to remove the ../ as the images folder is in the same folder as the file. I was also thinking it might be a problem that the "dynamic reports" is consisting of two words without a "-" inbetween. Will make a PR to test whether it works when adjusting it !

**Comment by valerievossen** [comment]
@MatthijstenTije, the issue was that one of the folder names contained two words. I changed it by putting a - in between the words and the images are showing now!
