### ISSUE TITLE
Show tutorial sections in the footer

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#119]
**Is your feature request related to a problem? Please describe.**
Currently all the tutorials are shown in the footer. This is not sustainable because in the future we will have many more of them and the tutorial column in the footer would get very long.

**Describe the solution you'd like**
Show the tutorial sections instead (Project Managament, Reproducible Research, Educational Support, More Tutorials...), similar to how it's done for building blocks.

**Additional context**
![image](https://user-images.githubusercontent.com/50109671/110926814-230cc480-8325-11eb-8ae6-7d9792556ec6.png)

**Comment by heyarviind** [comment]
> Self Note: Removed the posts and now showing the title of the sections. but because sections do not have their dedicated page, Hugo redirects to the tutorials search page.

**Comment by andreantonacci** [comment]
@heyarviind I see that you did it but you did not label it under review. Is it finished? Does it work properly?

**Comment by heyarviind** [comment]
no actually it is dependent on index pages for every section...

**Comment by andreantonacci** [comment]
Great job, thanks
