### ISSUE TITLE
Suggest change to: topics/Collaborate-share/Project-management/engage-open-science/contribute-to-tilburg-science-hub/pullrequests.md

### ISSUE THREAD

**Issue by gbocsardi** [tilburgsciencehub/website#1199]
Hi @hannesdatta @krzysztof99xd,

On [this site](https://tilburgsciencehub.com/topics/collaborate-share/project-management/engage-open-science/contribute-to-tilburg-science-hub/pullrequests/) at the bottom of the page ([Contribution Templates](https://tilburgsciencehub.com/topics/collaborate-share/project-management/engage-open-science/contribute-to-tilburg-science-hub/pullrequests/#contribution-templates)) links are broken, they throw a 404.

**Comment by krzysztof99xd** [comment]
Thanks for noticing @gbocsardi. Links were not correct, they were pointing to empty resources. I have correct them now. Please find the fix in Pull Request #1207 .
