### ISSUE TITLE
add code snippet of how to download data from google drive to the building block

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#122]
# Development Call: Building block to upload and synchronize directories/files with Google Drive and Dropbox

## Objectives

Students / researchers need a programmatic way to upload or synchronise directories / files with their remote storage at publicly available clouds like Google Drive and Dropbox. I'm always frustrated when this part of the workflow is manual. 

**Additional context**
Students do not/cannot make use of S3, for which we have implemented this already. So, developing this for cloud providers is highly important.

## Deliverables

A building block in the spirit of https://tilburgsciencehub.com/building-blocks/store-and-document-your-data/store-data/aws-s3-buckets/, but then for Drive & Dropbox.

It needs to cover uploading (i.e., just putting files), and synchronising (i.e., taking care that a local and remote directory are in sync/up-to-date).

- Suggested title: *Ex. "How to synchronize local files with Dropbox and Google Drive"*
- Required tools: *Ex. Python, R, Dropbox, Google Drive*
- References: former RA of TSH has put up this (https://github.com/hulaizh/get-data-from-drives); please reuse where possible (but, only features downloads, not uploads).

**Comment by hannesdatta** [comment]
Some other starting references are the official docs of Google Drive, for example. --> https://developers.google.com/drive/api/v3/manage-uploads

**Comment by hannesdatta** [comment]
Here's starting code for Google Drive:

this is what my students developed:
```
library(googledrive)
data_id <-"11MaNZ2_XaXXXXXXXXXXXXXXXXXXXXX"
drive_download(as_id(data_id), path = “out_file.csv”, overwrite = TRUE) 
df <- read.csv(“out_file.csv”)
It needs some extra explanation to authenticate the package w/ google, etc. so makes sense trying to go through these steps yourself first w/ sharing a particular (own) file from googledrive.
```

**Comment by Tomeulnv** [comment]
Done. Pull request #292
