### ISSUE TITLE
fix alignment of buttons

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#124]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/16557730/111127804-850f3900-8574-11eb-937c-944c423f0e7d.png)

Buttons are not aligned.

**Describe the solution you'd like**
Align buttons.

**Describe alternatives you've considered**
Ignoring it, but that doesn't look nice ;).

**Additional context**
Let's be as stylish as Jordan! ;)

**Comment by heyarviind** [comment]
Fixed
