### ISSUE TITLE
#flask: deactivate Google Analytics

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1244]
__Background:__

We're still using a few hard-coded private keys in the project, e.g.: https://github.com/tilburgsciencehub/website-flask/blob/main/static/scripts/service_account.json

__Deliverable:__
- Please set this up using GitHub secrets (or something like that) such that the credentials are not exposed.
- Needs to work with our docker way of deployment.
- Also search for other potentially exposed keys.
- After implementing this, we need to regenerate all private keys and destroy the existing ones.

QUESTION (or, is this only a read-only authenticated key, giving read permissions to google analytics data only)?

**Comment by thierrylahaije** [comment]
This code in service_account.json has been there for a very long time, even before I started. As far as I tried it is a read-only key, but still, we need to resolve this. @krzysztof99xd can you look into this issue?

**Comment by hannesdatta** [comment]
Deactivated permissions with this key; eventually, we retire Google Analytics and then this key is fully removed and deleted.

**Comment by hannesdatta** [comment]
__Deliverable:__

- Deactivate GA when #1254 is implemented.
