### ISSUE TITLE
#flask: add broken link checker script to github actions on this site

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1246]

**Comment by hannesdatta** [comment]
@thierrylahaije already is an admin; let's meet up to configure this together.

**Comment by thierrylahaije** [comment]
I have added the correct broken_link_checker and the action. Currently there is only a minor issue, the size sometimes seems to big when trying to create an issue but I dont understand why. I will need to further test to see what is happening.

**Comment by thierrylahaije** [comment]
Final issues have been fixed and everything is now working. The broken link script runs every week on friday evening and will create an issue with the broken links.
