### ISSUE TITLE
#flask: Update coding style on the website

### ISSUE THREAD

**Issue by krzysztof99xd** [tilburgsciencehub/website#1248]
Since there are some nuances in creating content on this repo we should think about how to update style guidelines. 
After collecting all the issues we came across while developing the website I wrote the following [markdown file](https://github.com/tilburgsciencehub/website-flask/wiki/Coding-guidelines-for-contributing-to-website%E2%80%90flask).

Then I learned that there is actually the article [Style and Writing Guidelines](https://tilburgsciencehub.com/topics/collaborate-share/project-management/engage-open-science/contribute-to-tilburg-science-hub/style-guide/#). Therefore, I think the easiest option will be to update it.  Should we directly update the guidelines markdown file in this repo?

**Comment by hannesdatta** [comment]
Let's discuss when we meet.

**Comment by krzysztof99xd** [comment]
We clarified this during the meeting and the new style guide is already in the current repo.
