### ISSUE TITLE
#flask: server-side analytics

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1254]
Hi @thierrylahaije - didn't we want to store some server-side analytics for this project? We need some minimal degree of reporting, similar to what we got with Netlify.

![image](https://github.com/user-attachments/assets/322f69fe-d54f-463c-a930-9ea7b665f86b)

![image](https://github.com/user-attachments/assets/241fa920-c230-4fd5-bcac-c3d72972cc4a)

![image](https://github.com/user-attachments/assets/e7226178-065e-4d42-9638-21d15d23c9fa)

__In particular, top resources not found. Is this tackled?!?__

Let's discuss our current setup, please.

**Comment by hannesdatta** [comment]
Deliverables:
1. Hannes installs Matomo on our server
2. Thierry implements tags on our site
3. Thierry implements fetching "most popular pages" so we can retire Google Analytics

**Comment by thierrylahaije** [comment]
@hannesdatta What is the status of the setup of Matomo on the server?
