### ISSUE TITLE
#flask: fix search

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1258]
why is this going into a 404?

<img width="1373" alt="image" src="https://github.com/user-attachments/assets/31cd05b4-ecb1-4b5a-b20d-dad594984fdb">

**Comment by thierrylahaije** [comment]
This has to do with the fact that the style guide is added twice in our structure. I have removed it in the upcoming PR. We do need to update Algolia to make sure it has refreshed all the results when moving the flask domain to the main domain.

**Comment by thierrylahaije** [comment]
Issue now fixed and merged in PR #1270.
