### ISSUE TITLE
#flask: viz. of popular pages

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1259]
<img width="323" alt="image" src="https://github.com/user-attachments/assets/ec681a80-d307-4d10-8b1f-0adda12b5cec">

vs.

<img width="349" alt="image" src="https://github.com/user-attachments/assets/429c1f00-13fd-4806-a6a4-63823087dfca">

Please fix:
- where do pop. pages are coming from?
- why are they not the same?

**Comment by thierrylahaije** [comment]
Issue now fixed and merged in PR #1270 . It opened random pages before typing, which resulted in not showing the popular pages. Symbols also fixed.
