### ISSUE TITLE
#flask: more issues

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1269]
- bullet points don't render: 
![image](https://github.com/user-attachments/assets/32f56d00-9773-4137-a0ca-4a00fae06dac)

seen on: https://flask.tilburgsciencehub.com/topics/Analyze/Regression/linear-regression/survival-analysis-lubridate/
compare to: https://tilburgsciencehub.com/building-blocks/analyze-data/regressions/survival-analysis-lubridate/

- search doesn't work
when searching on the new site for "survival", it tries to redirect to 
`https://flask.tilburgsciencehub.com/building-blocks/analyze-data/regressions/survival-analysis-lubridate`

but the correct link is `https://flask.tilburgsciencehub.com/topics/Analyze/Regression/linear-regression/survival-analysis-lubridate/`

Can you see what's going on?

- merge issues
scan repos for things like this and fix.

![image](https://github.com/user-attachments/assets/facb789c-a1b8-4ad0-9d7e-a658fae59e92)

prob some merging issues.

**Comment by krzysztof99xd** [comment]
I also noticed the search issue and asked @thierrylahaije for help and waiting for an advice from him.  I was doing some initial research (caches, incorrect routing, outdated links in the database) and tried different things but currently, I ran out of ideas.

I will work on other issues in the meantime.

**Comment by krzysztof99xd** [comment]
Found math equations to fix:
- matching.md
