### ISSUE TITLE
Problems with rendering Katex

### ISSUE THREAD

**Issue by krzysztof99xd** [tilburgsciencehub/website#1285]
Just noticed when was finishing the previous issue. Any idea why this issue arises @thierrylahaije ? 

![image](https://github.com/user-attachments/assets/3a1f3fa5-efb0-45dc-a1c5-06a4e7944bae)

**Comment by thierrylahaije** [comment]
I cannot rebuild the problem. Did you refresh your cookies? When I load the page I only get the following (neglectable) issues:

<img width="649" alt="image" src="https://github.com/user-attachments/assets/bb999aeb-87ae-4dfc-b581-168f2dd9f05c">

In the md, I also see the Formula structure is still incorrect:

<img width="591" alt="image" src="https://github.com/user-attachments/assets/dca271d5-baff-43db-8791-189d5ab5dd73">

**Comment by krzysztof99xd** [comment]
I cleaned the caches and actually, the issue is gone.  I cannot recreate it. Something to keep in mind but at the moment I am closing this issue. If the problem reoccurs, we will reopen it.
