### ISSUE TITLE
Prev/Next buttons glitches when text is too long

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#129]
**Describe the bug**
When the previous/next content has a title that's too long, the buttons behave weirdly and look bad:

![image](https://user-images.githubusercontent.com/50109671/111169028-e6e69780-85a2-11eb-8c5d-bfd25943337b.png)

**Expected behavior**
Make the font smaller inside the buttons ONLY when the text is too long. Alternatively, only show "Previous" and "Next" buttons (like on mobile).

**Comment by heyarviind** [comment]
okay... how about if we truncate the text?

**Comment by andreantonacci** [comment]
That's fine, as long as we truncate between words and not within a word. You can also add ellipsis. 

My only issue with this solution is that the number of words after which we truncate is dynamic. It changes depending on how big is the screen. Larger widows allow for larger buttons and thus longer text in them.

**Comment by heyarviind** [comment]
for now, I have added the max-width which changes according to the screen sizes. let me know your views. (committing changes in some time)

**Comment by andreantonacci** [comment]
Good thanks
