### ISSUE TITLE
quick way to open the repository when being on the site

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#131]
**Is your feature request related to a problem? Please describe.**

It always takes me ages to navigate to the site's GitHub repository when I'm at tilburgsciencehub.com.

**Describe the solution you'd like**
I need a quick access link, that takes me from TSH to the repository with one click. The button should be yellow, too. Signaling importance!

For example, a button on this page (well, that would be two clicks then)...
![image](https://user-images.githubusercontent.com/16557730/111277411-b6513d00-8638-11eb-8b77-16294d8c0416.png)

**Describe alternatives you've considered**

It may also be possible to put it in the footer of the site, but it will be less prominent then. But certainly viable for a start. The insiders will know it.

![image](https://user-images.githubusercontent.com/16557730/111277550-dd0f7380-8638-11eb-9bbd-28cc62343bd5.png)

```
About
Contribute
***GitHub repository***
Contact
```

I'd say: put it in the footer anyways.

**Comment by andreantonacci** [comment]
There's a link to our repo on the contribute page, but I'll make it more prominent and move to the top. 

In the footer, we already have the github icon (next to linkedin) that links to our profile. I could link it directly to our repo or add a text link as you've suggested.
