### ISSUE TITLE
katex rendering issue

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#1318]
I noticed that the Katex formulas aren't rendering well.

<img width="583" alt="image" src="https://github.com/user-attachments/assets/0a4d72de-f892-4906-b06a-9280b399068e">

See https://tilburgsciencehub.com/topics/analyze/causal-inference/panel-data/system-gmm/.

Please debug and fix.

**Comment by krzysztof99xd** [comment]
Thanks for noticing!  I have accessed the article and for me, it is displayed nicely. 
![image](https://github.com/user-attachments/assets/0c1cec84-db71-4010-abf5-6724cb134e16)

However, I will investigate what is going on there.

**Comment by krzysztof99xd** [comment]
Hmmm this error seems to be sometimes there:
`Uncaught TypeError: Cannot read properties of undefined (reading 'ParseError')
    at l (auto-render.min.js:1:2427)
    at e (auto-render.min.js:1:3177)
    at auto-render.min.js:1:3423
    at e (auto-render.min.js:1:3430)
    at auto-render.min.js:1:3423
    at e (auto-render.min.js:1:3430)
    at auto-render.min.js:1:3423
    at e (auto-render.min.js:1:3430)
    at auto-render.min.js:1:3423
    at e (auto-render.min.js:1:3430)`
    

Explore the following files: `templates/partials/head.html`  and `static/katex/auto-render.min.js`
