### ISSUE TITLE
Reformatting of multi-line menu items

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#133]
**Is your feature request related to a problem? Please describe.**

It's difficult to see from the menu whether a new item starts, or the text belongs to the subsequent line (e.g., "should know" belongs to the preceding line).

![image](https://user-images.githubusercontent.com/16557730/111308742-5a4be000-865b-11eb-9797-9251d0db994e.png)

**Describe the solution you'd like**

Reformatting of the text (e.g., by means of putting lines that belong together closer to each other, and by working with a little space after each paragraph/enter.

**Describe alternatives you've considered**

None. But open to listen to alternatives - I'm not a designer ;)

**Additional context**

Maybe something for Jordan to advise on?

**Comment by andreantonacci** [comment]
I think it can be solved tweaking the line-height in css. I'll give it a try.

**Comment by andreantonacci** [comment]
Thanks Arvind! Great job. I can see this working only in the building block menu though.

- Can you please do the same for all the menus (tutorials especially) and in the footer too? 
- And could you please add a little bit more padding between the columns in the menu? I've just noticed they're very close to each other. Maybe changing padding-left and padding-right from 7px to 10px? That would be great, thanks

![Screenshot 2021-04-22 at 10 24 15](https://user-images.githubusercontent.com/50109671/115682130-770fbd80-a355-11eb-85fb-10a0e0d977f5.png)

**Comment by andreantonacci** [comment]
Great, I can see this in all the menus now, but not on the footer yet. Can you please do the same for multi-line items here?

![image](https://user-images.githubusercontent.com/50109671/115703209-235b9f00-a36a-11eb-90d1-7b756e0953db.png)

**Comment by heyarviind** [comment]
sorry, i forgot... now added!
