### ISSUE TITLE
Development Call: tutorial writing a paper or thesis using LaTeX or LyX

### ISSUE THREAD

**Issue by kleintob** [tilburgsciencehub/website#135]
This tutorial should jump start the process of writing a paper or thesis using LaTeX.

It should first explain what LaTeX is good for and why it's a good alternative to Word (very briefly).

Then, it should explain that there at least three ways in which one can approach this:
- the user-friendly way: using LyX with a template such as ours (link to it)
- the in-between way: using overleaf
- the nerdy way: using an editor

The first two ways are easy and a simple link should get people started.

For the third way it would be good to link to a building block. In that building block it would be good to explain what people have to do to get TeX going on their Windows or Mac PC. Here it would be good to explain that they need the tex environment (so Miktex for Windows or Mactex for the Mac) and then an editor. Actually, this is nicely integrated into editors like Visual Studio Code.

Then it would be good to explain a few basic things:
- put references into a BIB file and use bibtex (an easy way to do this is to export them in tex format in google scholar)
- always use labels for equations, sections, figures, tables etc and then reference to those inside the tex document
- use code snippets for nice looking tables and figures (to be developed, building blocks)
- use our template (add a tex template that corresponds to the lyx template)

**Comment by andreantonacci** [comment]
a36afee
