### ISSUE TITLE
making the logo blink in the footer

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#136]
**Is your feature request related to a problem? Please describe.**

The geek in me tells we must use the blinking TSH logo in the footer.

![image](https://user-images.githubusercontent.com/16557730/111331344-1a8ff300-8671-11eb-9d25-6fef8e7c249d.png)

**Describe the solution you'd like**

Just use that gif there. Do we have it somewhere?

**Describe alternatives you've considered**

None :)

**Comment by heyarviind** [comment]
How is this?


https://user-images.githubusercontent.com/21043614/114342924-710e2580-9b7a-11eb-9d4e-e5e8970c425f.mov

**Comment by andreantonacci** [comment]
Arvind, I think we wanted only the underscore _ to be blinking, like is it was a console input. This is not very important right now so don't worry about it, just focus on critical issues, thanks

**Comment by andreantonacci** [comment]
Please, revert to the old one. I'll take care of this someday, don't worry about it, thanks!

**Comment by heyarviind** [comment]
Sure i will revert it 🤓

**Comment by andreantonacci** [comment]
Great, thanks
