### ISSUE TITLE
quick link to navigate to source code on repository ("Edit button")

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#137]
**Is your feature request related to a problem? Please describe.**

When browsing the site, I frequently see pages that I directly would like to edit. Yet, it's super cumbersome to navigate to them on our repository to make these changes. 

Similarly to the feature that we used to have on our old mkdocs site, a little *edit* link would be nice that takes you directly to the source code at GitHub.

See, e.g., the doc at Mkdocs:
![image](https://user-images.githubusercontent.com/16557730/111337089-12868200-8676-11eb-9926-d3c732362c26.png)
https://www.mkdocs.org/user-guide/configuration/

Here's how to do it on Hugo: https://discourse.gohugo.io/t/how-to-implement-edit-this-page-on-github/1166

**Describe the solution you'd like**

That very edit button. Gotta think through the design though. Add to Jordan's list and use a quick fix for now?

**Describe alternatives you've considered**

No.

**Additional context**

**Comment by heyarviind** [comment]
I have added the edit button but it needs to be designed properly, you can suggest the design or ask the designer...

**Comment by andreantonacci** [comment]
Good job, thanks. Regarding the button:

- Please move it at the end of the page, below the author credits and aligned on the right next to the sharing buttons
- As regards the style, use the class cta-secondary (white background, orange outline)
- Change the button text to "Edit this page"
- Hide the button from mobile, it's not necessary there 

![Screenshot 2021-04-22 at 10 10 51](https://user-images.githubusercontent.com/50109671/115680621-03b97c00-a354-11eb-9666-bf142f4e5c5c.png)

**Comment by andreantonacci** [comment]
Great job. Can you please add align-items: center to the flex container? That way the sharing buttons and the Edit button will be aligned vertically:

https://user-images.githubusercontent.com/50109671/115703005-e394b780-a369-11eb-8e92-b644a6661b67.mov
