### ISSUE TITLE
Fix dropdown alignment in mobile footer

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#143]
**Describe the bug**
As you can see, the text of the dropdown menus in the footer from the mobile view is not properly aligned. It's not vertically centered and it almost touches the preceding line.

![image](https://user-images.githubusercontent.com/50109671/112513053-40fe0e80-8d94-11eb-9d78-df2abe440022.png)

**Expected behavior**
The text should be vertically centered between the previous and the next horizontal line or, even better, aligned with the down arrow on the right.

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.4.1
 - Browser: Safari

The same applies to tablets too.

**Comment by heyarviind** [comment]
Fixed
