### ISSUE TITLE
Additional function for data preparation page

### ISSUE THREAD

**Issue by Jorg1002** [tilburgsciencehub/website#144]
Dear Hannes,

We have created an additional function to add to the page: "Prepare your data for analysis" which people could use to clean-up their social media data.

Unfortunately I was not able attach the file (I guess this is not possible with RMarkdown files), that is why I added the exact same code below.

Kind regards,
Jorg Boers

# Function to clean-up like, followers and following count extracted from social media.

The following function can be used to cleanup your social media output. The reason that this function is created is that for example the output when scraping TikTok can contain letters like K's (Thousands), M's (Millions) and B's (Billions). You are not able to analyze the numbers with these letters and for this reason these letters need to be changed in to zeros. That is exactly what the following function does.

```{r}
# function to convert textual social media counts to their actual numbers

#' Convert textual likes/follower counts to numeric values
#'
#' @param x Character vector with textual "counts" (e.g., 1.5K, 1.7M, etc.)
#'
#' @return Numerical vector with converted inputs
#' @export
#'
#' @examples social_media_cleanup(c('212K', '1M', '6.4B', '634')) or social_media_cleanup(df$column)

social_media_cleanup <- function(x) {
  if (class(x)%in%c('integer','numeric')) {
    warning('Input is already numeric.')
  }
  numerics <- gsub('[A-Za-z]','',x)
  units <- gsub('[0-9]|[.]|[,]','',x)
  multipliers <- rep(1, length(x))
  multipliers[grepl('K', units)]<-1000
  multipliers[grepl('M', units)]<-1E6
  multipliers[grepl('B', units)]<-1E9
  
  return(as.numeric(numerics)*multipliers)
}
```

An example of the output after running this function is the following:

```{r}
social_media_cleanup(c('212K', '1M', '6.4B', '634'))
```

**Comment by andreantonacci** [comment]
293cd5a
