### ISSUE TITLE
Development Call: Running computations remotely

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#145]
# Development Call: running computations remotely

## Objectives

With increasing demands in computations (i.e., high number of CPUs) or data (i.e., high memory), it may be an idea to move your computations and data preparation pipelines to the cloud. For example, AWS EC2 offers computers for rent (and so does Google, Azure, etc.).

How to run your computations/data preparations remotely?

## Deliverables

- [ ] **A Tutorial:**
  - Purpose: Teach users how to take their computations to a remote computer. 
  - Motivation: speed up computations, minimize errors (e.g., avoid computer restart), minimize interference from others (cf. blades), have access to high-memory
  - Scope: AWS EC2; also Azure & Google?
  - Suggested title: Hitting CPU or memory limits? Run your computations remotely
  - Suggested short link: tilburgsciencehub.com/learn/cloud; tilburgsciencehub.com/run/remotely
  - Outline:

1. First page of the Tutorial - Getting started + motivation
2. Comparison of main cloud providers (dimensions see below)
3. Get access to a cloud provider (link to sign up forms) --> links
4. Start remote instance
5. Move your infrastructure there (best way: clone repository and run make - link to tutorial for setting up a project); worse way: transfer manually (+ show how)
6. Monitor resource use + build in trigger in code to notify about end of data prep / [...]
7. programmatically or manually shot down instances

- [ ] **A Building Block:**
  - Purpose: Start up and close an EC2 instance
  - Conceptual stuff: Pay attention to types of servers (i.e., CPU and memory), and operating systems
  - Also show how to monitor resources
  - Also show how to programmatically destroy instances
  
- [ ] **A Building Block:** [same as above]
  - Purpose: Start up and close Azure instance

- [ ] **A Building Block:** [same as above]
  - Purpose: Start up and close Google Cloud instance

**Comment by kleintob** [comment]
I would suggest to add something to help people decide which cloud service to use. This could be part of the tutorial and also result in a building block that has a comparison table along various dimensions. We could also do a comparison of costs for various "typical" projects (maybe at a later point in time. I would first do a web search to see how good the existing comparisons are (and maybe we can link to them).

**Comment by hannesdatta** [comment]
dimensions to compare
- user friendliness
- possibilities, flexibility
- availability of Tilburg licence keys/discounts
- preinstalled images
