### ISSUE TITLE
default sorting: alphabetically

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#153]
**Is your feature request related to a problem? Please describe.**

As our content grows, setting the weights for content items becomes cumbersome. When removing weights, items are sorted by dates.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/16557730/114541060-8789af00-9c56-11eb-9c34-918d3ce7660c.png">

**Describe the solution you'd like**
Please make the default sorting when no weights are given alphabetic by title.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by andreantonacci** [comment]
Please revert this. We will use weight when we want to. Or remove the weights and date from the front matter for alphabetical sorting. Thanks
