### ISSUE TITLE
consider moving sharing bar up

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#155]
**Is your feature request related to a problem? Please describe.**
Some people I talked to didn't know about our permanent links.

<img width="813" alt="image" src="https://user-images.githubusercontent.com/16557730/114541892-8e64f180-9c57-11eb-9bd7-0af498a206f8.png">

**Describe the solution you'd like**
Move the sharing bar UP?

**Comment by andreantonacci** [comment]
@hannesdatta Where on the page would you suggest to move it? I think it's in a logical position: you first need to read the article to decide whether or not you like it (and want to share it).

**Comment by hannesdatta** [comment]
People still copy the old link from the browser bar. That’s the problem we need to fix in a way.

From: Andrea Antonacci ***@***.***>
Date: Tuesday, 13 April 2021 at 13:06
To: tilburgsciencehub/website ***@***.***>
Cc: H. Datta ***@***.***>, Mention ***@***.***>
Subject: Re: [tilburgsciencehub/website] consider moving sharing bar up (#155)

@hannesdatta<https://github.com/hannesdatta> Where on the page would you suggest to move it? I think it's in a logical position: you first need to read the article to decide whether or not you like it (and want to share it).

**Comment by andreantonacci** [comment]
We should find a way to make it more prominent then, without making it distracting. Sounds like a job for Jordan.

**Comment by hannesdatta** [comment]
Yes.

From: Andrea Antonacci ***@***.***>
Date: Tuesday, 13 April 2021 at 13:12
To: tilburgsciencehub/website ***@***.***>
Cc: H. Datta ***@***.***>, Mention ***@***.***>
Subject: Re: [tilburgsciencehub/website] consider moving sharing bar up (#155)

We should find a way to make it more prominent then, without making it distracting. Sounds like a job for Jordan.

**Comment by hannesdatta** [comment]
> We should find a way to make it more prominent then, without making it distracting. Sounds like a job for Jordan.

Still require this. It's soo hidden below there, and when I want to share stuff, it involves this extra long scrolling for me, too.
