### ISSUE TITLE
Development Call: How to deal with large datasets in R

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#168]
# Development Call

## Objectives

Give practical tips dealing with large datasets in R.

**Additional context**
Most students use dplyr or read.table to read in data. Give a list of tips to better dealing with large datasets.

## Deliverables

A list of tips.

Here is my draft for a building block:

 
- Restart R – your memory may be full given what you’ve done in R earlier
- Strictly use the data.table package’s fread function to read in data
- Use the nrows argument to only important a few 100 rows
- Learn which columns you need, and which ones you do not; then specify the KEEP argument in fread
- Never transform your data back to a data.frame; keep it as a data.table
- Store any derivative file using fwrite; close and restart R & read the smaller file using `fread` from the data table package

**Comment by MKT-Analytics** [comment]
Should this issue be closed? 
https://tilburgsciencehub.com/building-blocks/prepare-your-data-for-analysis/data-preparation/large-datasets-r/

**Comment by lachlandeer** [comment]
agreed! closing for now
