### ISSUE TITLE
improve search

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#178]
**Describe the bug**

Searched for "sensitive" but don't get any search results.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/16557730/128479666-3c23e781-6ed6-476c-b1dc-a32018b79d7b.png">

**To Reproduce**
1. Go to tilburgsciencehub.com
2. Type sensitive in the search box

**Expected behavior**
Show relevant search results

**Comment by andreantonacci** [comment]
f3e5de9
