### ISSUE TITLE
Development Call: How to work with literature

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#181]
# Development Call
## Objectives

**Is your content request related to a problem you've encountered during your research process? Please describe.**
We want to explain how to efficiently work with literature in your projects.

## Deliverables

**Note:** We encourage the use of this template. However, feel free to suggest your ideas in your own format, if you prefer. Just erase everything below in that case.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Choose if you need a Tutorial, a Building Block, both, or more of them. Add new ones by copying the structure below, or remove the unnecessary ones. Lastly, fill in the required information.

- [ ] **A Building Block:**
  - Purpose: How to build and maintain a reference list
  - Motivation: You should not use MS word for this or even worse try to remember everything inside your brain. Use tools to keep organized.
  - References: mendeley, zotero, endnote, bibtex

- [ ] **A Building Block:**
  - Purpose: How to search for literature
  - References: Libkey.io, Crossref.org, Google Scholar

- [ ] **A Building Block:**
  - Purpose: How to cite in text
  - Motivation: do it efficiently and according to a style guide / formats
  - References: bibtex, bibdesk, lyx, etc.

**Comment by hannesdatta** [comment]
@Tomeulnv, Work on literature Block first...

**Comment by Tomeulnv** [comment]
Perfect, will do

**Comment by lachlandeer** [comment]
Seems like there is content on this stuff on TSH, thus closing this
