### ISSUE TITLE
edit: principles of good coding

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#191]
**Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)?**

The updated "Principles of Good Coding" site (just merged @Tomeulnv PR) feels like reading a book. It's way too elaborate, and unspecific (e.g., talks about so many things, talks about so many languages).

**Describe the solution you'd like**

I ideally would like to see these coding principles be broken down into small, manageable "building blocks", and then tied together in a tutorial: "The 10 steps to improve your coding". Or something along these lines.

No new content, please. Just breaking it down into pieces like we do things in the TSH-style, i.e., building blocks are small, manageable pieces of info or code, and tutorials "talk them together".

@Tomeulnv, curious to hear your ideas & you're welcome to try it out!

**Additional comments**

Please familiarise yourself with our various shortcodes and ways to add code boxes (supporting multiple languages) in articles/building blocks. Add some flavor to the text :) (e.g., R/Stata code can go in code boxes). Use tips, summaries where appropriate, etc.

No need to start away: we can wait for @andreantonacci to put it to your sprint.

**Comment by andreantonacci** [comment]
@Tomeulnv Thanks for the update.

- The R guidelines page seems a bit too basic. Maybe we could not only link to the Google's R style guide but also explain its most important points in the building block as well? 

- Could you please link back all the language-specific building blocks (currently python, r and stata) to the main "principle of good coding" building block? Something like "for language-specific guidelines, see here for python, here for R..." and so on. What do you think?
