### ISSUE TITLE
Development Call: Using Research Cloud

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#198]
# Development Call: Using Research Cloud to deploy IT infrastructure for coauthors

Please port this to a building block. Thanks a bunch!

https://docs.google.com/document/d/183Lfi_5xEMdcProZ13Ok-IIOsFWewoEDrj1UTeWA7xQ/edit

**Comment by hannesdatta** [comment]
@Tomeulnv, just checked the post. great job. 

just some feedback here: 
- please use enumeration with dots, e.g., 1. 2. 3. instead of - 1, -2, -3. The house template of TSH renders those as nice numbered lists then.
- the warning box was a bit big, it was the entire onboarding instructions. i made it a little smaller.
- 
thanks a bunch, I feel a lot of stuff is moving well here.

**Comment by Tomeulnv** [comment]
Okay, noted. Thank you for the feedback @hannesdatta !

**Comment by hannesdatta** [comment]
all up and running: https://tilburgsciencehub.com/configure/research-cloud
