### ISSUE TITLE
Make Chromedriver easier

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#203]
Students always have a problem installing chromedriver.

A team of students now came up w/ an amazing fix (so you don't have to manually install chromedriver).

```
# Make selenium and chromedriver work for Untappd.com

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

#driver = webdriver.Chrome()
driver = webdriver.Chrome(ChromeDriverManager().install())

url = "https://untappd.com/"
driver.get(url)
```

The task would be to offert his as our primary choice for installing chromedriver. We could then have a manual instruction somewhere else ("install manually"), but this one really works best.

- [ ] run it
- [ ] write stepwise instructions (probably: pip install selenium, pip install webdriver_manager --> and then this snippet)
- [ ] test it on windows, mac and linux (if possible)
- [ ] propose change to existing chromedriver building block.

--> https://tilburgsciencehub.com/configure/python-for-scraping

**Comment by andreantonacci** [comment]
Maybe also here: https://tilburgsciencehub.com/scrape/dynamic-website

**Comment by hannesdatta** [comment]
@andreantonacci, assign to someone?

**Comment by hannesdatta** [comment]
Why hasn't this been done yet?! ;)

**Comment by hannesdatta** [comment]
great for fixing!

Please also add it here: also here: https://tilburgsciencehub.com/scrape/dynamic-website w/ a reference to installation of chromedriver should you want to run it manually.

Thanks!
