### ISSUE TITLE
Remove "Related Posts" section within tutorials

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#209]
**Is your feature request related to a problem? Please describe.**
Related posts at the bottom of the page distract from what's really important: the navigation arrows to move on to the next tutorial page.

**Describe the solution you'd like**
Remove related posts while keeping the keywords assigned to the pages. Only show related posts AT THE END of each tutorial (on their last page).

**Comment by lachlandeer** [comment]
Closing as can't tell if have fixed this or what the status might be... looking at tutorials the end of the post looks quite different across each

reopen if we want to work on it
