### ISSUE TITLE
Review checklist for new contributions

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#210]
**Is your feature request related to a problem? Please describe.**
Create a checklist for content and styling of new contributions to TSH. It should be embedded somewhere prominently on GitHub and/or in the review process.

**Comment by andreantonacci** [comment]
Cool idea: a review mechanism is automatically in place for new pull requests via GitHub actions. For instance, one may check whether at least an alias has been specified in the frontmatter (for permalinks).

**Comment by lachlandeer** [comment]
Not sure what happened here, and would need more content to develop out.

Closing for now, reopen later if needed
