### ISSUE TITLE
Update Google Drive download snippet

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#213]
**Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)?**
@hannesdatta where's the updated snippet?

Current version: https://tilburgsciencehub.com/store/data

**Comment by hannesdatta** [comment]
this is what my students developed:

```
library(googledrive)
data_id <-"11MaNZ2_XaXXXXXXXXXXXXXXXXXXXXX"
drive_download(as_id(data_id), path = “out_file.csv”, overwrite = TRUE) 
df <- read.csv(“out_file.csv”)
```

It needs some extra explanation to authenticate the package w/ google, etc. so makes sense trying to go through these steps yourself first w/ sharing a particular (own) file from googledrive.

**Comment by hannesdatta** [comment]
duplicated issue from #122
