### ISSUE TITLE
mention "edit button" on contribution guide

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#216]
It may be difficult to understand for newcomers who to edit content/find stuff in the source code.

please enhance the contribution guide at TSH (https://tilburgsciencehub.com/tutorials/more-tutorials/contribute-to-tilburg-science-hub/contribute/), by explicitly mentioning the "edit page" button to find out where particular files are stored on the repository.

Thanks!

PS.: We already have a little section on this in the contribution guide, but do not mention the edit page button yet.

**Comment by andreantonacci** [comment]
5c7f5d3
