### ISSUE TITLE
Development Call: Publish on the web using R (bookdown and distill)

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#217]
# Development Call

## Getting started

Many academics seek out to publish own websites - either in the form of profile pages (we already have that covered w/ Hugo), or in the form of interactive academic papers & digital books.

This is where `bookdown` and `distill` come into place - two R packages that facilitate the creation of websites. Through R. 

## Objectives

The objective of this dev call is to 

(1) develop two building blocks,
 - one on using [distill](https://rstudio.github.io/distill/?panelset=screenshot#creating-an-article)
 - one on using bookdown

*provide the necessary resources to get started (code snippets)*
 
Further,
(2) develop a brief tutorial that
- explains why publishing through R is a good idea ("connected to empirical work", "easy")
- compares `distill` and `bookdown`

## Deliverables

- [ ] **A Tutorial:**
  - Purpose: *How to publish ebooks and interactive articles directly from R*
  - Motivation: *Sometimes writing a paper is simply not enough: provide readers with an interactive article on the web, or start drafting your own ebook!*
  - Suggested title: *see purpose*
  - Suggested keywords: *publish, website, distill, bookdown, R, markdown, publish*
  - Outline:
    1. First page of the Tutorial - Explain the objective
    2. Compare existing tools
    3. Provide links to code snippets for bookdown and distill
    4. Provide examples (+ add them to our tsh example section, too!)
    5. Conclusion & next steps (e.g., suggest to read Hugo too)

- [ ] Building block for distill
- [ ] Building block for bookdown
- [ ] New item in Example section, linking to a couple of "publishable" distill/bookdown projects for inspiration.
 
@Hschuett, could you please review this dev call + add your notes to it? I can then move it into "production" at Tilburg Science Hub. Thanks a bunch!

**Comment by hschuett** [comment]
Fully agree with Objectives and Deliverables

Re: comparison. 
- Distill: 
  - Seems easy and intended for "article-like" shorter webpages or weblogs. See the Distill reference [examples](https://pkgs.rstudio.com/distill/articles/examples.html) or one of my [attempts](https://hschuett.github.io/BayesForAccountingResearch/)
  - From the Distill [doc](https://pkgs.rstudio.com/distill/index.html): "Distill for R Markdown is a web publishing format optimized for scientific and technical communication."
- Bookdown:
  - Seems perfect for large content with always visible toc. Many [webbooks ](https://github.com/hadley/adv-r) and [documentations ](https://github.com/stan-dev/docs) are written using bookdown
  - From the bookdown [doc](https://bookdown.org/): "The bookdown package is an open-source R package that facilitates writing books and long-form articles/reports with R Markdown."

**Comment by hannesdatta** [comment]
- A building block on bookdown
- Move distill to the building block on building a website

**Comment by hannesdatta** [comment]
Hi @srosh2000,
here is the other package I mentioned earlier: https://quarto.org/

Above, I suggested making individual blocks for distill / bookdown + a tutorial that wraps things up/explains the bigger thing.

Maybe that's a way forward? See first post above.

Feel free to break it down in smaller chunks.

E.g., start w/ a comparison of the three packages (find some broad dimensions) + just link to them.
In a next, you can add a building block on your favorite package (my intuition says it may be quarto as it is most versatile, that's what it seems in any case).

Makes sense? 

Let me know if you need input.

**Comment by srosh2000** [comment]
@hannesdatta , These are some pre-existing tutorials on these options that seem quite good already:

https://rstudio.github.io/distill/ --> this brief tutorial on distill
https://quarto.org/docs/guide/ --> detailed guides and tutorials on using quarto
https://bookdown.org/yihui/bookdown/ --> guide for bookdown 

Given that there are really good existing guides/tutorials on all the alternatives I'm not sure how much value adding it would be to have separate building blocks for each of them. 

So I'm thinking of doing a single building block piece that showcases all the three available options, describe and compare them and just add these aforementioned links to "get started".

And I will make sure to link some of the examples for each of them under example section as well. 

Lemme know what you think. But for now I will work on the comparison part and start drafting it.

**Comment by hannesdatta** [comment]
Yep - let's proceed that way, @srosh2000! Curious to see it soon!

**Comment by hannesdatta** [comment]
Oh, btw - add a few examples / have our own "research" gallery of awesome material.

**Comment by srosh2000** [comment]
@hannesdatta , just made a pull request please have a look and lemme know if you want me to edit it further or add more things (quite basic for now). 
Technical question:  I wanted to change the comparison table layout to a more standard layout without scrolling, any idea how to change it on atom?

**Comment by lachlandeer** [comment]
@srosh2000 

What;s the status here?

**Comment by srosh2000** [comment]
@lachlandeer Yes indeed, we can close this issue its done.

**Comment by hannesdatta** [comment]
It exists: https://tilburgsciencehub.com/topics/collaborate-share/share-your-work/content-creation/using-r/
We can close.
