### ISSUE TITLE
[Feature]: Add links to overview pages and relative sections on the menu

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#235]
### Contact Details

h.datta@tilburguniversity.edu

### Is your feature request related to a problem? Please describe.

Our front end developer has recently implemented fully-clickable breadcrumb tails. That's great.

However, our menu doesn't yet use these "mock-up" landing packages. For example, you cannot click on "professionalize project management".

![image](https://user-images.githubusercontent.com/16557730/136553488-ad0d9d3d-46b1-439f-8f2e-9afcda6b77fc.png)

...while you *can* click on it here:

![image](https://user-images.githubusercontent.com/16557730/136553532-248f0039-91b4-4e3c-a32d-04471bc770e8.png)

### Describe the solution you'd like

Add the relevant links to our menu.

(1) first level:

![image](https://user-images.githubusercontent.com/16557730/136553598-7611352a-f64f-495b-9a3f-0a49ea5f753d.png)

(2) second level:

![image](https://user-images.githubusercontent.com/16557730/136553625-fdf3d255-405f-4961-aec0-38748e3860c6.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
Agree on this. Will become more relevant as content gets more

Moving to 2023 sprint for web designers to think about

**Comment by hannesdatta** [comment]
All solved with our layout update at the end of 2023.
