### ISSUE TITLE
Bug: broken content

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#237]
### Contact Details

h.datta@tilburguniversity.edu

### What happened?

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/16557730/136945185-51f08999-b1c6-4165-ac4e-f66fcab0d894.png">

click on first hit --> leads to 404

### To reproduce

- search for "project setup"
- click on first hit
- gives you a 404

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andreantonacci** [comment]
e251e42
