### ISSUE TITLE
[Development Call]: Collaborating & Sharing Files with Dropbox

### ISSUE THREAD

**Issue by Tomeulnv** [tilburgsciencehub/website#240]
### Is your content request related to a problem you've encountered during your research process? Please describe.

Mainly motivated by professors sharing dropbox folder with large datasets that can't be added to your Dropbox (usually free version) instead of sending dropbox link to where the files are. This way, one can access files in Dropbox without having to add them to their own Dropbox.

Also if you think it might be interesting, we could add short guide (or best "hacks") to Dropbox.

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
Stale -- closing
