### ISSUE TITLE
Screen materials on thesis.hannesdatta.com for possible integration on TSH

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#252]

**Comment by hannesdatta** [comment]
- [ ] Find material that's useful for TSH and add it there
- [ ] Replace material that exists on science hub with links

**Comment by lachlandeer** [comment]
I don't see this going anywhere soon -- @hannesdatta can I close this?

**Comment by hannesdatta** [comment]
Dooooone :). We now have a new thesis guide on our TSH website. Thanks to @alexandervossen and @valerievossen (right)?
