### ISSUE TITLE
[Feature]: Make landing page dynamic

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#253]
### Contact Details

h.datta@tilburguniversity.edu

### Is your feature request related to a problem? Please describe.

The landing page is static.

![image](https://user-images.githubusercontent.com/16557730/143409563-5db6944c-5c27-4697-8fc5-2edffe0b26a0.png)

Instead, we could make the landing page dynamic by shuffling the topics on these cards / showing some new ones (potentially even based on clicking behavior).

### Describe the solution you'd like

- Write flask API in Python that serves random topics, from each category (or, later, w/ some kind of propability)
- Rather than hard-coding the page, use API to pull in topic names + links.

What we will learn:
- writing our own API + integrating it w/ our site

Why is it useful?
- this is a toy example, but later we can use our knowledge to make dynamic other parts of the website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
Another idea is to tag "new" content automatically and surface it on the landing page

**Comment by hannesdatta** [comment]
__To do:__

- look at tech platforms (stackoverflow, datacamp, a lot of stuff) and "see" how the design their landing page
- identify ways in which they use their landing page to pull in new users & retain existing ones

My ideas:
- learning paths?
- talk to other RAs about it?
- look google analytics...?

**Comment by hannesdatta** [comment]
e.g., 
Cialdini's 7 principles of persuasion

    Social proof.
    Reciprocity.
    Authority.
    Liking.
    Commitment & Consistency.
    Scarcity.
    Unity.

13 Jun 2019

Using Cialdini's 7 principles on your self service portal

**Comment by hannesdatta** [comment]
--> some inspiration for cool UI elements; https://semantic-ui.com/modules/rating.html

**Comment by Tomeulnv** [comment]
Here is  a ppt file with some ideas:
[Dynamic_landing_page.pptx](https://github.com/tilburgsciencehub/website/files/7876801/Dynamic_landing_page.pptx)

Could go through it next check-in meeting.

**Comment by Tomeulnv** [comment]
See issue #298
