### ISSUE TITLE
[Q]: Plan meeting w/ RAs to discuss how traffic can be boosted

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#254]
### Shoot!

A few leads:
- which courses could we integrate our site with?
- making ads?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MKT-Analytics** [comment]
@juliehabets I'm checking the issues and some of them are pretty old and probably not relevant anymore/solved. To make the board tidier, we can consider closing some of them. I'll just tag you so you can make the final decisions.

**Comment by hannesdatta** [comment]
Please ensure we do not consider issues "closed" simply because they are old. Maybe bundle them and then discuss w/ me or Tobi whether we see a prior on this. Ok?

**Comment by lachlandeer** [comment]
Moved to the 2023 Spring "TSH marketing" board so that whoever takes on this role can assess

**Comment by hannesdatta** [comment]
Traffic's up :)
