### ISSUE TITLE
conduct weekly maintenance

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#258]
https://github.com/tilburgsciencehub/maintainer-handbook/wiki/Recurring-Tasks

**Comment by hannesdatta** [comment]
Take a look at this and see what is crucial to do

**Comment by lachlandeer** [comment]
Feels like a role for more than one person. 

Let's think about how to split among different people based on their role, and then make them  accountable

**Comment by kleintob** [comment]
Hannes and I had a weekly steering group meeting with Julie. Agreed, we need a version 2.0 of this. Maybe we could ask one of the RAs to do part of this and coordinate everything in a little steering group meeting with the four of us and the new RA, just before the weekly standup?

**Comment by shrabasteebanerjee** [comment]
Indeed - we have a call scheduled Feb 22 at 10AM Dutch time, we can set up
a meeting schedule when we speak then!

**Comment by hannesdatta** [comment]
Legacy issue. We're up and running.
