### ISSUE TITLE
integrate/add links to page

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#264]
I have come across these useful resources recently.

Let us find a place to link to them on TSH:

- [ ] https://psyteachr.github.io/reprores-v2/plotstyle.html
- [ ] https://debruine.github.io/webexercises/
- [ ] https://adv-r.hadley.nz
- [ ] https://github.com/debruine/shinyintro
- [ ] https://github.com/debruine/msc-data-skills
- [ ] https://psyteachr.github.io/reprores-v2/repro.html
- [ ] https://debruine.github.io/tutorials/webpages.html

**Comment by Tomeulnv** [comment]
Here they are (dev-link-integration):

- [ ] https://psyteachr.github.io/reprores-v2/plotstyle.html --> In BB: [Learn R](https://tilburgsciencehub.com/building-blocks/develop-your-research-skills/learn-to-code/learn-r/)
- [ ] https://debruine.github.io/webexercises/ -->  In BB: [Learn R](https://tilburgsciencehub.com/building-blocks/develop-your-research-skills/learn-to-code/learn-r/)
- [ ] https://adv-r.hadley.nz --> In BB: [Learn R](https://tilburgsciencehub.com/building-blocks/develop-your-research-skills/learn-to-code/learn-r/)
- [ ] https://github.com/debruine/shinyintro -->   In BB: [Build Interactive Dashboards With R Shiny](http://localhost:1313/building-blocks/collaborate-and-share-your-work/publish-on-the-web/shiny-apps/)
- [ ] https://github.com/debruine/msc-data-skills -->  In BB: [Learn R](https://tilburgsciencehub.com/building-blocks/develop-your-research-skills/learn-to-code/learn-r/)
- [ ] https://psyteachr.github.io/reprores-v2/repro.html -->  In BB: [Learn R](https://tilburgsciencehub.com/building-blocks/develop-your-research-skills/learn-to-code/learn-r/)
- [ ] https://debruine.github.io/tutorials/webpages.html -->  In BB: [Learn R](https://tilburgsciencehub.com/building-blocks/develop-your-research-skills/learn-to-code/learn-r/)
