### ISSUE TITLE
create follow-up issue to ask whether suggestinos have been implemented + reattach document

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#266]
It was: 

Find around 20 of the best resources on the TiU INTRANET (mostly under research support) that would be valuable and fit on TSH, i.e., something useful for researchers that we want to disclose to the INTERNET

https://www.tilburguniversity.edu/intranet/research-support-portal
(make a list of links)

**Comment by Tomeulnv** [comment]
Done, it's in the followinf issue
Best resources on the TiU INTRANET follow-up #271
