### ISSUE TITLE
create analysis building blocks

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#268]

**Comment by hannesdatta** [comment]
inspired by these sections?

https://www.cmdmethods.nl/cards/showroom

Keep it brief, so let's add a lot of stuff.

**Comment by hannesdatta** [comment]
- Lasso, Ridge
- Bagging & boosting

**Comment by lachlandeer** [comment]
Now part of the Spring 2023 sprint, with specific issues, Closing this
