### ISSUE TITLE
[Development Call]:  using packrat w/ R

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#269]
### Contact Details

h.datta@tilburguniversity.edu

### Is your content request related to a problem you've encountered during your research process? Please describe.

Follow up of issue #219 :

How to use tools like `packrat` or `packman` to make packages be archived & more reproducible.

### Additional context

When working with R, users use all kinds of different package versions. If one wants to run code produced by others, hence, it becomes important to use the exact same package versions (otherwise, the could work).

What we require is a quick piece (building block) on how to use packrat/packman, which I believe is the best way to solve this in R.

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Purpose

Archive your packages so that other users use the same version or that you can quickly transport your code to a different machine, running the same packages.

### Suggested title

Make sure your code is reproducible, even if R packages change

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
If completed, do it for conda environments

**Comment by srosh2000** [comment]
@hannesdatta Just pushed my draft of the building block under packrat-branch. Lemme know if its okay :)

**Comment by hannesdatta** [comment]
great work, @srosh2000.

A few comments to make the final touches:
- [ ] please try to find a good screenshot and add it on top of the article (or wherever it makes sense illustrating stuff). I plan to make the site look a bit more lively, and this may add just that bit of "liveness".
- [ ] Please change the title so it conveys a meaning: Never miss an R package: Using Packrat. Or something like that. You'll come up w/ something better, but see the spirit here.
- [ ] The styling in the tip box doesn't seem right (font too big, etc.) - check other articles for how they do it on our site.

For the rest - great! You can directly make these changes to our master branch!

**Comment by srosh2000** [comment]
Hi @hannesdatta,
Just finished incorporating your feedback.
- I added some screenshots where I thought could be illustrative.
- Changed title as per your suggestion, I quite liked it too and couldn't think of anything better at the moment so for now I think this works well 
- changed tip box layout
Lemme know if there is anything else to add/change. 

Thank you!

**Comment by hannesdatta** [comment]
Great - I swapped page titles so that the search title will return something more meaningful. Looks great. @casruger we could promote this one eventually!
