### ISSUE TITLE
create links on tilburg science hub for resources market in GREEN

### ISSUE THREAD

**Issue by Tomeulnv** [tilburgsciencehub/website#271]
Hi @kleintob,

I shared with  you and Andrea a list of links with the best resources on the TiU INTRANET:

https://docs.google.com/document/d/1o2JDXbdqhmnpXMXDLVxQYmO7N3k8QWotJ1E_ZBDnx3E/edit

Have any of these suggestinos been implemented? Or is any of the information in the links found to be of interest ?

Thanks,

Tomeu

**Comment by hannesdatta** [comment]
__To do:__
- create meaningful linkages (so, find a good spot where we're talking about something similar/relevant), and then add link as follow-ups. "weave it" into the site.
