### ISSUE TITLE
create docker template for example respository & test it

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#277]

**Comment by hannesdatta** [comment]
Follow-up to #219

**Comment by hannesdatta** [comment]
@Tomeulnv heck this resource as a guide, given to me by @kleintob: https://aeadataeditor.github.io/posts/2021-11-16-docker

**Comment by hannesdatta** [comment]
> Hi Tomeu,
> 
> I heard from Hannes that you are working on Docker solutions. This blog post describes where the best econ journals are at the moment (quite far):
> https://aeadataeditor.github.io/posts/2021-11-16-docker
> 
> Maybe we can build on that, at the minimum we should refer to it.
> 
> They also stress that Stata is still super important. They call it the holy grail and show an interesting figure. I think we should keep that in mind and explain in detail on TSH how to do that with stata.
> 
>  Best,
> Tobi

**Comment by Tomeulnv** [comment]
Hi @hannesdatta ,

A few updates on current situation.:

__GOAL 1:__

- I have now done the tutorial and other ones to understand how Docker works. This [handbook](https://docker-handbook.farhan.dev/container-manipulation-basics#naming-or-renaming-containers) is a great starting point if you also want to look at it.

- Now that I start to understand its usage, I shall start creating a test repo that contains python and R code to try and run it from inside a docker container.

__GOAL 2:__

- It seems as I have managed to access the image (it required creating a password). Is this how it is supposed to look:
![image](https://user-images.githubusercontent.com/78488301/149941504-40488c0b-cfde-4dd7-be18-e1480debaf82.png)


I also have a word document with notes on resources etc

**Comment by Tomeulnv** [comment]
Done, check pull request #295
