### ISSUE TITLE
develop github action to check for broken links

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#278]
__To do:__
1. Crawl the website and check for any broken link (e.g., with Screamingfrog SEO Spider) (see here: https://github.com/tilburgsciencehub/maintainer-handbook/wiki/Recurring-Tasks)
2. Extend docuemntation on how exactly you did it and put it to our wiki
3. Find an "algorithm" to scan for broken links ourselves (e.g., using Python); how to do it? what kind iof links are broken? where to we link to?

**Comment by Tomeulnv** [comment]
Hi @hannesdatta ,

I have checked Screamingfrog among other crawlers and they all seem to have a limit number of links that they check for free (500 in Screaminfrog's case). Do you happen to know whether Andrea had a license?

However, if we require "only" to check for broken links, **Brokenlink.com**  does the job online and for free (though a bit slow). Here is attached an excel sheet (first sheet) with the broken links found by brokenlink.com in our website:
[Crawl_05_01.xlsx](https://github.com/tilburgsciencehub/website/files/7814102/Crawl_05_01.xlsx) How do we deal with such links?

Alternative to Brokenlinks:
- A solution could be to check for subdomains with Screamingfrog and thus, not reach the limit. But it is a bit tedious, especially if the objective is only checking for broken links.
-  Google Search Engine can also do it, but it requiered accessing the DNS registers

If Brokenlink.com is enough, I will extend the documentation along with alternatives.

**Comment by hannesdatta** [comment]
Follow up: hannes will try to get `.py` tool running.

**Comment by hannesdatta** [comment]
__UPDATED DELIVERABLES__: Develop GitHub Actions to scan for broken links on Tilburg Science Hub and subsequently create a new issue flagging those broken links.

*Background:*
We use a lot of external links on our site, and some may break. We need a way to get notified about these broken links soon, and - if possible - in an automated way.

*How I think this can be solved:*
GitHub actions automate part of a repos and can be triggered at intervals (e.g., daily, at each commit, etc.). We already have such an action running for our search Index. The yml (triggering the action) is [here](https://github.com/tilburgsciencehub/website/tree/47e2f303bbed744f9ea98f4283bb66cbc14c3c18/.github/workflows) and the Python script that gets triggered is [here](https://github.com/tilburgsciencehub/website/blob/47e2f303bbed744f9ea98f4283bb66cbc14c3c18/content/create-search-index.py).

*How I suggest going about this:*
First, develop a .py script that checks for links automatically. I imagine it a two-part process. Part 1 scans for available links in the .md and .html source code of our site. It creates a list of these links and then uses the requests library to make HTTP requests, storing the return value for each request. The script then returns, by their response code (with some extra stuff/info so ppl who're not technical know what a 404 vs 403 is etc.) and compiles an overview about what needs to be fixed. Using GitHub actions, this is then submitted as a new issue called ("fix xxx broken links"), with the body being the output of your script. Here is some inspiration I found for automating the [writing of issues](https://github.com/JasonEtco/create-an-issue).

**Comment by thierrylahaije** [comment]
This issue is finished and now available in the broken-link-checker repository.
