### ISSUE TITLE
[Development Call]: How to use parallel computing in R?

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#284]
__Background:__

Parallel computing is increasingly important. While some libraries, such as `data.table` or `dplyr`, have parallelization built in, researchers can also parallelize code that wasn't meant to be run in parallel in the first place!

__Deliverable:__

- Highlight the basic principles of parallelizing code: 
  - determine number of cores available
  - create cluster
  - send "data", load packages, and send "functions" to the nodes of the cluster
  - execute code in parallel
- See code snippet below

```
# Parallelizing code in R

library(parallel)

perc_use = .8
ncpu = floor(detectCores(all.tests = FALSE, logical = TRUE) * perc_use)

# create cluster
cl <- makePSOCKcluster(ncpu)

# e.g., call a function on the cluster
clusterEvalQ(cl, 1+2)

# a function we would like to call
cluster_test <- function(x) x+x


# export function to cluster
clusterExport(cl, 'cluster_test')

res = clusterApplyLB(cl, 1:1000, cluster_test)

```

**Comment by hannesdatta** [comment]
Something for you, @Fernando-Iscar?

**Comment by Fernando-Iscar** [comment]
Hi @valerievossen, could you take this over?
