### ISSUE TITLE
[Development Call]: panel data analysis

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#285]
### Contact Details

h.datta@tilburguniversity.edu

### Is your content request related to a problem you've encountered during your research process? Please describe.

Explain students how to do panel data analysis (e.g., using `plm` in R)

### Additional context

As part of our (extending) building blocks section on analysis tools.

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

e.g., some example snippet to start w/ in R:

```
N = 1000
library(data.table)
data = data.table(y=rnorm(1000), X=runif(1000))
data[, id:=as.factor(rep(1:5, length.out=1000))]
data[, time:=as.numeric(rep(1:300, length.out=1000))]

library(plm)

m <- plm(y~X, model = 'within', index = c('id','time'), data=data)

```

**Comment by lachlandeer** [comment]
closing this, will flesh out same content via `fixest` as a starting point #618
