### ISSUE TITLE
identify ways in which we can broaden our site to other audiences (non econ & non-marketing), aligned w/ your personal ersearch interests

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#287]

**Comment by Tomeulnv** [comment]
**How to expand to other audiences?**

First ideas:
-	More on Covid-19 + hot topics?
-	Add comments to tech forums relating to our posts
-	Content on generic quantitative methods applied in multiple disciplines
o	E.g. PCA, hierarchical clustering, Random Forests
-	More attractive/clear names (e.g. Machine Learning)? Or that highlight something (thinking on why README is by far the most popular…)

**Comment by hannesdatta** [comment]
We have - this is legacy and we can retire this issue.
