### ISSUE TITLE
[Development Call]: R-plots cheatsheet

### ISSUE THREAD

**Issue by Tomeulnv** [tilburgsciencehub/website#291]
### Cheatsheet for Data visualisation with R

It is always nice/important to produce nice plots. R has a wide range of options to produce beautiful and customizable plots, especially with the package ggplot2. However, the overwhelming amount of options makes it somewhat tedious to produce such graphs.

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Purpose

A BB of the nature of our existing BB "Cheatsheet for LaTeX Math Commands" would ease things a lot.

**Comment by hannesdatta** [comment]
@MatthijstenTije - can you see whether there is anything valuable in this that you could add to existing plotting content? If not, feel free to close this issue. Thank you.
