### ISSUE TITLE
Job profile "marketer"

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#297]
### Contact Details

h.datta@tilburguniversity.edu

### Shoot!

W/ Tilburg Science Hub, we’d love to hire an RA as a marketer (.2-.4FTE) who can 

-	Boost user & contributor growth
-	Do Google Analytics on our site – improve our own dashboard but also do market research on what content works well, and what not
-	Has some experience with websites and affinity with coding
-	Ideally has worked as an intern in a company/agency
- Familiarity with scrum framework
- Familiarity with running/managing social media channels, doing some banners
- good writing skills, etc. 

It's probably best to post a few "fitting" indeed.com jobs (search for them) here, and then gradually mold this into a job position for our RA team.

@BilgeKasapoglu, would you be available to work on this initially & show me what you can come up with in let's say in max. an hour or so?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
> Thank you for your email. I have time of course.  I have a clarifying question though. Do you want me to prepare a job posting for this or look for indeed.com job postings to shape the job responsibilities? Thank you


Please use indeed.com for inspiration on how such a posting may look like.

We will probably get more ideas what that person can do to grow the user base.

**Comment by BilgeKasapoglu** [comment]
Dear @hannesdatta 

I have time of course.  I have a clarifying question though. Do you want me to prepare a job posting for this or look for indeed.com job postings to shape the job responsibilities? Thank you

**Comment by hannesdatta** [comment]
Please see my answer above.

**Comment by BilgeKasapoglu** [comment]
Dear @hannesdatta ,

I prepared a doc document regarding the task. I am attaching it to this comment. If you would like me to put it somewhere else, please let me know. Thank you

Best
[Research Assistant as a Marketer.docx](https://github.com/tilburgsciencehub/website/files/8123405/Research.Assistant.as.a.Marketer.docx)

Bilge

**Comment by hannesdatta** [comment]
Have edited the doc and @kleintob will provide comments. 
https://docs.google.com/document/d/1L7ZNsIBUvWq7Pjnm-FIFQEmXc05ewB2z/edit?usp=sharing&ouid=102700861718989371394&rtpof=true&sd=true

**Comment by kleintob** [comment]
@hannesdatta I've made one small suggestion and think the document is otherwise good. I've marked this here as "done" but maybe it's more correct to say that you should now follow up again.

**Comment by hannesdatta** [comment]
Doc is live and we're hiring! tilburgsciencehub.com/jobs.
