### ISSUE TITLE
Changes to landing page

### ISSUE THREAD

**Issue by Tomeulnv** [tilburgsciencehub/website#298]
The idea is to modify landing page according to idea presented in [dev-landing-page](https://github.com/tilburgsciencehub/website/tree/dev-landing-page) but giving it a more professional touch (i.e. make it look as if Jordan did it)

Could you help us out with this @andreantonacci? Unfortunately my HTML/CSS capability is quite limited :)

Thank you

**Comment by andreantonacci** [comment]
Hi @Tomeulnv, I'll take a look once I have some free time

**Comment by hannesdatta** [comment]
I have decided to keep the layout as is at this stage, and now randomly pull most recent building blocks & examples for every new page build. See also announcement here: https://github.com/tilburgsciencehub/website/discussions/318.
