### ISSUE TITLE
Create "feature request" template for research support

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#300]
### Contact Details

h.datta@tilburguniversity.edu

### Is your content request related to a problem you've encountered during your research process? Please describe.

We're getting quite some mails from Tilburg researchers, asking us to help them with their research projects. IDeally, we would like them to open up issues on GitHub itself. Yet, all of our issue templates are for website features only, not for research support requests. People also shouldn't really have to choose yet between templates and building blocks or something like that.

So, ideally, someone creates an issue template here on Git itself, like the templates we have done before, so that researchers can submit support requests.

Check some tutorial on how to create GitHub issue templates first, btw... we have already some examples here (https://github.com/tilburgsciencehub/website/tree/master/.github/ISSUE_TEMPLATE), so it should be relatively straightforward.

Thanks in advance!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BilgeKasapoglu** [comment]
Dear @hannesdatta ,

I complted this assingment. However, I realized that there are so many templates in the Issues section. Isnt it a bit confusing for external users? It would be great if we try to minimize them because to me, they all seem like doing the same thing

Thank you

Best
Bilge

**Comment by hannesdatta** [comment]
Yeah, this is a good point. Can you come up with a proposal of WHICH issue templates to have?
Right now, we think like "content creators" ("do you want a tutorial or building block?"). Maybe we should think more like our stakeholders.

- R&D new things ("learn docker & write a tutorial")
- Solve a particular research problem ("Help me webscrape this for my research")
- Technical issues on the science hub website or platform

Just an idea.

Looking forward seeing your suggestions .

**Comment by hannesdatta** [comment]
@BilgeKasapoglu, any response?

**Comment by BilgeKasapoglu** [comment]
Dear @hannesdatta,

Based on your suggesting and going through the issue templates. I came up with the following suggestion. Let me know if you have any other idea. If it is okay with you, I can create/edit them on Atom. I put the already existing issue templates that are similar in the paranthesis.

1. **Technical Issues on the Science Hub Website or Platform** (Bug report + Edit content request)
    1. Contact Details
        1. How can we get in touch with you if we need more info?
    2. Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)? If it is a bug in the website, please indicate which browser you are using. 
        1. A clear and concise description of what the problem is.
    3. Describe the solution you'd like
        1. A clear and concise description of what you want to happen.
    4. Additional context
        1. Add any other context or screenshots about your request here.
2. **R&D New Content for the Website** (New content request + Feature request for research )
    1. Contact Details
        1. How can we get in touch with you if we need more info?
    2. Would you like this to be a Building Block or a Tutorial?
    3. Is your content request related to a problem (e.g., a problem encountered during your research)? Please describe.
        1. A clear and concise description of what the problem is.
    4. Describe the solution you'd like
        1. A clear and concise description of what you want to happen.
    5. Additional context
    6. Purpose
    7. Motivation
    8. Suggested title
    9. Suggested keywords
    10. Required tools
    11. References
3. **Solve a Particular Research Problem** (Feature request)
    1. Contact Details
        1. How can we get in touch with you if we need more info?
    2. Is your feature request related to a problem? Please describe.
        1. A clear and concise description of what the problem is.
    3. Describe the solution you'd like
        1. A clear and concise description of what you want to happen.
    4. Describe alternatives you've considered
        1. A clear and concise description of any alternative solutions or features you've considered.
    5. Additional context
        1. Add any other context or screenshots about your request here.
4. **General question**
    1. Contact Details
        1. How can we get in touch with you if we need more info?
    2. Shoot!
        1. Just ask.

Have a nice weekend! 
Bilge

**Comment by hannesdatta** [comment]
We'll transfer it to @casruger

**Comment by hannesdatta** [comment]
Research requests are not part of TSH's focus at this stage anymore. Let's close.
