### ISSUE TITLE
cheatsheets: fix filenames, etc.

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#313]
> Please use lower cap filenames for downloads and also add PPTX to the same directory and make it downloadable, too.

__Originally posted by @hannesdatta in https://github.com/tilburgsciencehub/website/pull/312#issuecomment-1063827358__

**Comment by hannesdatta** [comment]
Edit request: 
- [ ] add make cheatsheet
- [ ] make cheatsheets "easier" to find on TSH (e.g., building block)

**Comment by hannesdatta** [comment]
@RalphGit21, any update? prob this is done right? Let me know please.

**Comment by juliehabets** [comment]
Cheat sheet looks to be made; https://tilburgsciencehub.com/tutorials/reproducible-research-and-automation/principles-of-project-setup-and-workflow-management/versioning/
