### ISSUE TITLE
[Development Call]: Building block on the available options for cloud storage

### ISSUE THREAD

**Issue by srosh2000** [tilburgsciencehub/website#315]
### Is your content request related to a problem you've encountered during your research process? Please describe.

My RA supervisor wanted to assign some coding work which involves big data but the data policy allows the use of only dropbox but this initiated the idea of having a basic building block on TSH that puts all the available options in one page (e.g. AWS, surfdrive, dropbox, google drive) and compares each of the pros and cons. 

Since I have relatively limited experience working with big data/cloud I was wondering if you @hannesdatta @kleintob could also add in some inputs like what dimensions to compare the options against, what issues you think one must consider etc.. I can maybe help wrap everything into a single write up. 

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kleintob** [comment]
Here are my two cents:

One big theme on our website is workflows for empirical projects. We have information here and there on how to store data and access it, but it seems to me that something is missing that brings it all together.

I believe one has to think about this in the very beginning, when one picks a folder structure or even before that.

What does one have to think about?
1. where to put the raw data
2. how to access the raw data (this needs to be integrated into the workflow with make; check whether one has locally the same data as in the online storage and if not update or download it; updating can be done with rsync, for instance, which can be part of the make routine)
3. where to run the analysis (where are temporary files stored)
4. whether or not it makes sense to combine the above (in particular step 2.) with Git LFS, for which we have a tutorial

I think we should explain all of the above. @srosh2000 's question was more narrow: what are the dimensions related to step 1.

First of all, options:

- Dropbox
- Google Drive
- Surfdrive

- Amazon AWS
- Azure

- Network storage on campus
- a NAS one runs oneself

- what else?

Next: relevant dimensions:

a. convenience
b. is there a backup? true for network storage on campus and to some extent Surfdrive/Dropbox
c. if there is no backup, is it easy to make one regularly? If it's about raw data then an obvious possibility is to simply put the raw data already on Dataverse
d. legal restrictions (somebody claiming that we're not allowed to use Google Drive, or someone saying that it has to be locally on campus (so no Surfdrive/Dropbox, etc.)
e. speed
f. what else???

Next steps: I've unassigned myself and hereby play the ball to @hannesdatta . Please follow up.

**Comment by hannesdatta** [comment]
Legacy. Let's close.
