### ISSUE TITLE
[Development Call]: Online editor Overleaf

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#317]
### Contact Details

h.datta@tilburguniversity.edu

### Is your content request related to a problem you've encountered during your research process? Please describe.

We talk about Lyx, Latex, etc., but NOT about overleaf - an online editor that makes collaborating super easy.

Let's add a building block!

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Purpose

Overleaf is an easy route to starting to use Latex.

1. What's overleaf and when to use it (e.g., online editor, use when wanting to collaborate, but having limited experience with compiling tex documents).
2. How to get started (e.g., go to this page, sign up and start using; link to our templates for latex and maybe show how to setup a document - use screenshots here!)
3. Getting the most out of Overleaf
3a. Synching with GitHub
3b. Using Grammarly with Overleaf --> link to https://github.com/robindijkhof/overleaf-textarea

### Suggested title

Use Overleaf to collaborate on Latex documents in your brower

### Suggested keywords

latex, grammarly, overleaf, collaboration

### Required tools

a browser

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
+ put the building block under __write a paper__:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/16557730/158457698-70491fc8-3f6a-4341-8477-6c6f4efc317d.png">

**Comment by casruger** [comment]
Content is online https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/write-your-paper/overleaf/
