### ISSUE TITLE
brainstorm about a better search slogan

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#322]
We can do much better than this:

![image](https://user-images.githubusercontent.com/16557730/160153735-1051b6a3-cb76-4700-a0a3-621af69638ab.png)

**Comment by srosh2000** [comment]
Just had a little brainstorm sesh and here are some suggestions ( will maybe add more if I get more ideas later):
- **Search for topics, tutorials, tips & tools**
    - this is nice as its not only call to action but also hints the user at what we can offer and guides search instead of something so vague
- **What would you like to learn?** (love this too!) —> inspired from datacamp
    - would be good to add search suggestions along as they click the search bar like this
    
<img width="1440" alt="Screenshot 2022-03-27 at 10 26 22 PM" src="https://user-images.githubusercontent.com/67949747/160299967-f13c525e-fa89-4f96-a1fe-d021fad1da84.png">
- **What are you looking for?** —> inspired from Tilburg Education Hub ( Why didnt i hear about TEH before!)
- **Ask us anything!**
- **Search Tilburg Science Hub** ( like search reddit, KDnuggets)
**- How can we help you?
- Explore Tilburg Science Hub
- Discover Tilburg Science Hub
-Have a question? Shoot it!**

**Comment by hannesdatta** [comment]
> Search for topics, tutorials, tips & tools

We decided on the one above in yesterday's Wow meeting :).
 
The site is live!
