### ISSUE TITLE
[Feature]: preview of search terms?

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#323]
### Contact Details

h.datta@tilburguniversity.edu

### Is your feature request related to a problem? Please describe.

In yesterday's Wow meeting, @srosh2000 suggested to have some sort of "search results" preview, similar to what you see at Datacamp.

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/16557730/160551196-60c09592-5069-4348-9643-14c31cf903c3.png">

(1) My question is: should we have this when people click on "search" in the header?

<img width="293" alt="image" src="https://user-images.githubusercontent.com/16557730/160551249-38d05edf-ad8f-4452-92c9-0ab0c5acfe4d.png">

(2) Or, alternatively, when they click on search on the landing page: 

<img width="533" alt="image" src="https://user-images.githubusercontent.com/16557730/160551387-d0001fb4-d42c-4081-ae09-c6b05746dc12.png">

In the case of (1): how should the "default" search preview be generated? Hard-coded? Based on actual searches (could extract from our search provider), based on "most recent articles" that we have written? @srosh2000?

In the case of (2): do we display a preview at all? If so - do we use the same algorithm as above, or do we display different stuff here? 

Curious to hear your thoughts, @srosh2000.

Btw: as for 1) - we can use the existing dropdown layout we have for search and then populate it with our preview search results:

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/16557730/160551749-177751dc-008b-490a-8d05-b9793d531fd5.png">

### Describe the solution you'd like

A menu that unfolds before people enter search terms.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by casruger** [comment]
This gets picked up with Arvind in issue #368
