### ISSUE TITLE
come up w/ plan of action to implement our outreach strategy

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#331]
Our main goal is to connect to the Tilburg (offline and online) community, and other online communities (first Netherlands, then out of the country).

__Offline__
- Connect to Open Science (https://www.linkedin.com/company/open-science-community-tilburg/), Digital Competence Center / Research Data Office
- Fun ‘workshops’ – ScienceHub Sushi
- Workshops turn into lecture
- Connect with education (vice dean education) / education programs (Data Science)

__Online__
- Google analytics – metrics (reduce bounce rate)
- Ads target at TiU researchers, Open Science community
- Redesign website – more interactive
- Twitter/LinkedIn posts
- Linkbuilding other website
- Turing Way – what can we learn/do better?

Deliverable: PLan of action to start up our activities

**Comment by casruger** [comment]
Google analytics – metrics (bounce rate wrongly interpreted)
    •	New users per channel (mainly twitter and linked in + Tilburg university (canvas))
    •	Reduce the monopoly of SEO
    •	New users per week 
    •	Returning users  (more than 2 sessions) per week and per channel
    •	NR of visitors to contribution page or Google analytics goal 
   
 
Increase traffic
 
Offline

- Connect to Open Science ( https://www.linkedin.com/company/open-science-community-tilburg/), 
          o	I think it is great if we could get a mention on their Linkedin page (360 followers). Maybe we could link this with an activity on the Tilburg University campus (reading for example)
          o	Digital Competence Center / Research Data Office
- Fun ‘workshops’ – ScienceHub Sushi
- Workshops turn into lecture
- Connect with education (vice dean education) / education programs (Data Science)
    Get mentioned on canvas pages 
          •	Career development (make your own website) + https://www.tilburguniversity.edu/students/career/student-career-services/workshops-training
            •	Marketing analytics page?  https://snipboard.io/MmS0Gt.jpg     
            •	Data science and society 
    - Get mentioned on Tilburg University Instagram story or post

     
Online
Free:
•	Redesign website 
    -  Highlight the community aspect on the tutorial and building pages (https://snipboard.io/LS7jId.jpg)
    -  Redesign the tour page
          •	Highlight what TSH is and what you can do 
          •	Introduce to interesting tutorials and building blocks
 
 
•	Twitter/LinkedIn posts
      - Post new content of the website + old not yet published features every other week (add source to link to measure)
      - Get mentions from professors (https://snipboard.io/ilzjV8.jpg)

 
•	SEO improvement/keeping up 
o	Link building other website (Page authority (35), Domain authority (14))
 
Paid:  
Ads target at TiU researchers, Open Science community, TiU master students
Instagram 
•	Brand awareness (show adds of TSH broadly to students near Tilburg doing a master) 
•	Generate traffic by showing project related ads (Code your own free website in 15minutes, write an academic paper)
	(100,-; 14.000 impres; 105 clicks max)

Google display 
•	Brand awareness (Visitors of tilburguniversity.edu) 
•	Generate traffic by showing project related ads (Code your own free website in 15minutes)
https://snipboard.io/HTbQid.jpg

LinkedIn
•	Brand awareness (show adds to people following or in open science groups) 
	(100,-; 27.000 impres; 100 clicks max)
•	Boost posts to people in open science community's 
	(35,-; 2.000 impress; 70 clicks max)
 
 
Google Adwords
o	To promote building blocks and tutorials (broad 1 to 2 euro per click, niches cheaper)
•	More specific = less costs, but also more time consuming per page 
(Example How do I write a good README on GitHub?)
(What should be in a GitHub README?)
(install snakemake, ranked 3th, so cpc low)

**Comment by casruger** [comment]
During the meeting with Hannes converted the plan in new issues: 
Offline: 
Oranize offline event "meet the TSH crew" #351 
Get mentioned on Canvas pages MA master #348 
Get mentioned on DS master #349 
Get mentioned on career development page #346 
Get retweeted by open science community https://www.linkedin.com/company/open-science-community-tilburg/ #357
Try to get mentioned by professors #352 

Online:
Free:
Get announcements and alert bars to promote community aspect#337
Rewrite tour page #338 
Start posting on Twitter and LinkedIn, once in two weeks #345
