### ISSUE TITLE
[Feature]: Get added to student portal

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#334]
### Contact Details

h.datta@tilburguniversity.edu

### Is your feature request related to a problem? Please describe.

Add TSH to: 

https://www.tilburguniversity.edu/students/skills/programming

### Describe the solution you'd like

Write a little snippet that TilburgU can add to the programming portal.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by casruger** [comment]
We are added to this page https://www.tilburguniversity.edu/students/skills
