### ISSUE TITLE
implement announcement box on site/branch announcemnent

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#337]
- Problem: users exit site after seeing building block
- Solution: change site design to show more of what we have
- Dev: make sketch of mockup design for building block & tutorial view

**Comment by casruger** [comment]
I made a sketch of how I envision it, lets's discuss if this is a viable option. 
https://snipboard.io/LS7jId.jpg

**Comment by hannesdatta** [comment]
Talked about it today - showed @casruger how to run Hugo locally

**Comment by hannesdatta** [comment]
Decision: implement on tutorials and building blocks.

+ remove black banner from other places on the site. #355

**Comment by hannesdatta** [comment]
just integrated #358! done :)
