### ISSUE TITLE
revise tour pages

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#338]
- make mockup draft of tour page (word/google docs)
- splitting into student/researchers at a later stage

**Comment by casruger** [comment]
First draft of the tour page: 

# How to use TSH

Tilburg Science Hub (TSH) is a platform helping individual researchers, data scientists, and their teams to efficiently work on empirical research projects. It provides information about workflow and data management and tutorials that teach researchers how to organize and document their data and code, so the research becomes sustainable and reproducible. This in turn leads to time savings and transparency in the process.

[icons]
1. Follow Tutorials 	
2. Retretrieve information from building blocks   
3. Contribute yourself

## Tutorials: 
There are tutorials on how to make your research more reproducible, how to offer open education but also very practical tutorials on how to write an academic paper or how to write a LaTeX document. These tutorials offer a great starting point and give extensive information on the topic. If you are looking for a particular topic (for example how to web scrape, how to set up R) the building blocks are perfect. 

## Retrieve information from building blocks:
On the site, useful information can be found about every part of (open) research. From setting up your computer with Python and R to automating your workflow to do even quicker research and everything in between. Follow the process en see where you can learn more.

Configure your computer : 
 Most visited page 
 2nth most visited page
 
Collet your data : 
 
 
Etc. 

## Contribute yourself
The platform is an open source initiative which means that anybody can contribute or suggest improvements. This can be done via two ways, either via a GitHub Issue or via a Pull Request. 

#### Github Issue
If you want to suggest a change on the website you can do this by creating a GitHub Issue. You can for example bring a bug to our attention or point out a typo. You can also create an issue to suggest a new feature or to ask for new content to be added. For more information visit the contribute page https://tilburgsciencehub.com/tutorials/more-tutorials/contribute-to-tilburg-science-hub/contribute/

#### Pull Request
If you don’t want to only suggest changes but also want to implement them you can do this via a Pull Request. We have a step-by-step guide on how to do this on the contribute page. https://tilburgsciencehub.com/tutorials/more-tutorials/contribute-to-tilburg-science-hub/pullrequests/

**Comment by casruger** [comment]
In discussion with Hannes a 'tutorial' on how to use the platform with an onboarding overlay might be more appealing therefore continued on issue #366

**Comment by hannesdatta** [comment]
Please implement on the main  `tour` page; deactivate other tour page.

**Comment by casruger** [comment]
Implemented the tour page pull request #385 

Could not find out how to remove the tour page for researchers, so this still has to get done.

**Comment by casruger** [comment]
The new and finalized tour page is live.
If @hannesdatta could remove the research tour page, every thing is done 
https://tilburgsciencehub.com/researcher-tour/
