### ISSUE TITLE
Past utm's from shortlink to the redirected page link

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#343]

**Comment by hannesdatta** [comment]
- split up bounce rates by building block/tutorial/rest of the website
- make user segments
- blacklist for domains/entry points we don't consider

**Comment by casruger** [comment]
Discus utm problem with short links. 
If the sharable link (short link) gets shared the medium and source gets set to direct/non in google analytics. Whereas if we use the long link, the user does not get redirected and the source and medium gets viewed as the one it is (LinkedIn for example)

**Comment by hannesdatta** [comment]
@casruger I googled for this one: "redirects with google analytics" and got to this page:

https://www.newmediacampaigns.com/blog/how-to-track-landing-page-redirects-using-google-analytics

I believe this is something we can readily implement in our links, e.g., doing tilburgsciencehub.com/learn/R?campaign=123.

Maybe there are also other ways - can you do a bit of googling to find out, using the search term above or similar ones? There is probably a fix for this we can readily implement.

Cheers!

**Comment by casruger** [comment]
- To separate bounce rate per content group: Google analytics> Behaviour> Site Content> Content Drilldown

![image](https://user-images.githubusercontent.com/51459017/164255857-7db78afb-5efc-4c85-91c0-7f05c95f91eb.png)

- User segments are made 

- Bots have been excluded via all 'web site data' 'filters' under 'admin'

**Comment by casruger** [comment]
Keeping the original UTM's to a redirected link is quite technical. I would suggest adding a UTM source= 'shared-short-link' to see how big the group is. If we see a lot of traffic with that redirect we could look further into it. 
![image](https://user-images.githubusercontent.com/51459017/164506355-5ad88b3b-0b50-4e34-a647-4c10cc6c81a2.png)

**Comment by hannesdatta** [comment]
A brief description about the issue:

- We use shortlinks for our site, e.g., tilburgsciencehub.com/get/R. We ideally would like to track from where our users entered the site; e.g., linked in appends to this URL tilburgsciencehub.com/get/R?utm_source=linkedin.
- However, when Hugo forwards users to the actual page (https://tilburgsciencehub.com/building-blocks/configure-your-computer/statistics-and-computation/r/), that ?... gets removed.

Can you edit the site's code so that anything appended to the link is passed to the following site, @heyarviind?
