### ISSUE TITLE
Post on LinkedIn and Twitter

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#345]
__Goals__
- promote usage in Tilburg
- boost number of all users
- attract contributors

__For Tilburgers interested in open science:__
- Post about this event and tilburg science hub: https://www.tilburguniversity.edu/research/young-academy/prizeless-ideas-event
- Start a conversation w/ the open science community: how do you do open science? 

Campaign ideas on LinkedIn & twitter:
- notebook science w/ jupyter (+ collaborate)
- document your datasets using the gebru 2020 template
- get your code citable
- how to write an R package / voorbeeld van mij
- publish gold open access
- preregistration
- open education classes (e.g., george's site)
- autofilling values --> https://tilburgsciencehub.com/reference/list
- learn docker
- use packrat
- automatically install R packages used in a project: https://tilburgsciencehub.com/install/r-packages
- https://tilburgsciencehub.com/building-blocks/automate-and-execute-your-work/automate-your-workflow/what-are-makefiles/
- use makefiles: https://tilburgsciencehub.com/building-blocks/automate-and-execute-your-work/automate-your-workflow/what-are-makefiles/

"Did you know Tilburg University can pay your open access fees once you get published? <LINK TO TILBURG> But there's so much more that you can do.

__Which posts?__

-

**Comment by casruger** [comment]
First LinkedIn and Twitter posts placed and LinkedIn post promoted 2022-04-19
LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:6922258828738662401/
Twitter: https://twitter.com/tilburgscience/status/1516497969415135248

**Comment by hannesdatta** [comment]
Add #users to site in next post, plus say we're making more and more tutorials.

**Comment by casruger** [comment]
Share the stories of our team members. For inspiration see: https://www.linkedin.com/company/mysteryminds/
We could do a series of meeting the team, or promote for example Roshini when a new tutorial or building block gets launched which she wrote.

**Comment by casruger** [comment]
Meet the team posts: 
https://docs.google.com/document/d/15Aj21oNC52XJALissppx9rM5z1t-9r_iir9-xAsk32k/edit?usp=sharing

**Comment by casruger** [comment]
Will continue in issue #519
