### ISSUE TITLE
Description in search results

### ISSUE THREAD

**Issue by casruger** [tilburgsciencehub/website#353]
Currently, no meta description which is why Google picks a sentence from the page itself.

**Comment by hannesdatta** [comment]
follow up: use this slogan consistently in /contribute, onboarding guide, readme.md on github, etc.

Learn to work more efficiently on [empirical research projects](http://localhost:1313/tour), using tools like R, Python, and Stata – flavored with open science made in Tilburg. Initially launched by researchers from [Tilburg University](https://tilburguniversity.edu/), Tilburg Science Hub is developed on [GitHub](https://github.com/tilburgsciencehub/website) and welcomes [open source contributions](http://localhost:1313/contribute).

**Comment by casruger** [comment]
Added slogan to Twitter. 

Unsure how I can change the 'about' text on GitHub.
![image](https://user-images.githubusercontent.com/51459017/164736874-29c8849e-0169-424e-9fd7-8ee5b50c3b55.png)

I would suggest adding the slogan on LinkedIn, however, it seems like I do not have the right to do so. 
![image](https://user-images.githubusercontent.com/51459017/164735069-559848fb-ff83-4312-b970-2415bf9bce99.png)

I think the current text in readme.md fits better and the slog has a different goal than the text on the onboarding and contribute page, but if you find a fitting place let me know.
