### ISSUE TITLE
how to run hugo?

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#354]
It seems totally unclear how to run Hugo  - but I THOUGHT we had the content somewhere.

- find the content either on tsh or the github repository
- make it visible where it needs to be visible (e.g., contribution guide, in the readme.md on the github repository, and in the onboarding guide).

"WARNING BOX: How to run our site". Don't just edit the raw data files, but install link (<LINK>) and run it. Maybe w/ a screenshot'"

**Comment by andreantonacci** [comment]
@hannesdatta it's here https://tilburgsciencehub.com/launch/academic-website

**Comment by hannesdatta** [comment]
Thanks @andreantonacci! A shorter, Tilburg Science Hub-specific instruction may still be useful for our site, @casruger. We don't want people to first having to read through the generic tutorial.

**Comment by casruger** [comment]
Added the content on how to run the site local on the contribute page with pull request #373
And added the information on the onboarding page https://github.com/tilburgsciencehub/onboarding/wiki/Setting-up-your-computer/
