### ISSUE TITLE
display usage stats on our site?

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#362]
In an attempt to make our site more "lively", I would like to explore options to including "statistics" on our site, right on the landing page.

A few examples:

xxx users yesterday
xxxxx looking at tilburg science hub right now
xxxxx lines of code written last week
etc.

My feeling is that there must be a way to pull in these stats from google analytics or via the GitHub API. 

Can you please

- look for inspiration on what usage stats we could show so that users get more of a feeling others are there and use the site AND
- maybe check whether you can find some tools that allow us to do this.

A few examples:
- https://github.com/anuraghazra/github-readme-stats#github-stats-card
- https://docs.github.com/en/rest/metrics/community

**Comment by hannesdatta** [comment]
+ find screenshots of sites that already do this as an inspiration

**Comment by hannesdatta** [comment]
- Make specific recommendations where to put this information
- Add your own inspiration

Inside Kaggle you’ll find all the code & data you need to do your data science work. Use over 50,000 public [datasets](https://www.kaggle.com/datasets) and 400,000 public [notebooks](https://www.kaggle.com/kernels) to conquer any analysis in no time.

Section w/ kopjes van GitHub contributors

**Comment by hannesdatta** [comment]
![image](https://user-images.githubusercontent.com/16557730/166212164-4df3cd7b-2353-4f01-907d-37a09ca58f7d.png)

**Comment by casruger** [comment]
@hannesdatta  what do you think if we add the following section to the homepage? This would not be dynamic though since we need to make the image in photoshop. 
If you like the idea I will make the image better and make a pull request. 


![Image](https://user-images.githubusercontent.com/51459017/169268135-e0060eda-5afe-45bc-bf36-9ba5b375bbdb.png)

**Comment by casruger** [comment]
Closed with pull request #437
