### ISSUE TITLE
Retargeting website visitors to increase retention

### ISSUE THREAD

**Issue by casruger** [tilburgsciencehub/website#372]
Over the last 3-months we had 748 returning users, this was 8.61% of all users who visited the site. Ideally, we would like the number of returning visitors to be higher (not that returning visitors click on the contribute page more often, could also be because we click this button more often). 

![Image](https://user-images.githubusercontent.com/51459017/166102175-c129d200-4f7d-4539-89e0-06c1a0af11ed.png)

We can increase the % of returning visitors by retargeting people who have seen our website with google search advertisements (when they are searching for content which we can also offer) and by showing them content which they might not know they were looking for via display advertisements (think of click here to see how you can improve your GitHub profile).

**Comment by casruger** [comment]
Retargeting display idea

Learn open science w/
Tilburg Science Hub
More than 10 tutorials, offered for free
Learn at your own pace
Start today

 


![Image](https://user-images.githubusercontent.com/51459017/172823890-e7eeb8c6-22d0-4338-bd4f-1e9dce713b91.png)

**Comment by casruger** [comment]
Since a lot of the clicks come from India, Bangladesh, and Iraq we split up the budget between current visitors and start a new campaign targeting The Netherlands

**Comment by casruger** [comment]
Copied existing campaign which only targets The Netherlands splitting the budget 50/50 between worldwide audience and The Netherlands

**Comment by hannesdatta** [comment]
Pls add brief bullet point description of progress & screenshot of campaign, @casruger

**Comment by casruger** [comment]
- We have had 2,820 impressions and 50 clicks from The Netheralands 
- We have had 61,000 impressions and 1,770 clicks world wide 
- In total we have spent 21.17 + 3.95 = 25.12 euro by 29-06

An overview of the audience: 


![Image](https://user-images.githubusercontent.com/51459017/176426983-e22794eb-52a9-4760-bea0-c4b71d64f61d.png)

The session duration of especially The Netherlands is very low and all visitors came from app advertisements. Therefore I assume these might have been miss clicks. Because of this the ads will not be shown to in applications any more, to try and pay for desktop actual visitors. 

As requested a screenshot of the advertisements: 
https://ads.google.com/aw_cm/ExternalPreview?hl=en_US&ad=605704451203&adGroup=141071985027&ocid=917706713&isObfuscatedOcid=false&showMulPreview=true&showVariations=true&creativeType=35&pk=ACMAqCcuwElis0xFB-wTCOSCAW4CEA9AYYiEnCGTejpjI2Y2Xl4pOdkW1KPpOZFOqXTWnvAdPgogQfovmbBUn4sEW2Z2mdTB8AJJ7tTm8BpMrUakwTOMjQW_9RPeKPXHP5_cDFpLhsE3CnUrVrCy16ZU6frtBOPYHRGl7peYalpIrq8vE2Bc_vVSxNw
![Image](https://user-images.githubusercontent.com/51459017/176427372-ef6f62f6-a671-4021-b275-4ed8f01c2eb0.png)

**Comment by casruger** [comment]
We continue this issue in #519
