### ISSUE TITLE
get in touch w/ illustrators to get quotes for adding more dynamic visuals to our site

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#375]
We need the site to look more "alive".

E.g., https://www.khanacademy.org/

The package could include ADDING more visuals in the first place (and making them look dynamic/lively), but also using existing stuff on our site.

**Comment by hannesdatta** [comment]
E.g., animation here: 
![image](https://user-images.githubusercontent.com/16557730/166212687-ca6da62c-1d76-4762-b022-7b3a40ff46aa.png)

**Comment by hannesdatta** [comment]
e.g., hover actions:

![image](https://user-images.githubusercontent.com/16557730/166212751-72b2d30c-b946-472e-9422-764d4d5089f3.png)

**Comment by hannesdatta** [comment]
or animations on fimga

https://www.figma.com/

**Comment by hannesdatta** [comment]
e.g., text that starts being typed when made visible:

https://www.palantir.com/

**Comment by hannesdatta** [comment]
e.g., playful font here:

![image](https://user-images.githubusercontent.com/16557730/166213513-96153b60-10a8-48b6-88d9-f8328d1ada50.png)


https://grow.google/intl/europe/

**Comment by hannesdatta** [comment]
@andreantonacci - can you help us out on this one, please? We're trying to make our page become more dynamic, but somewhat don't find the right market places to hire jordan-like quality illustrators. any pointers?

**Comment by andreantonacci** [comment]
@hannesdatta Umh, have you tried on [Dribbble](https://dribbble.com)? Not sure you can post a job for free, but you can definitely find someone and then reach out privately to them, that's how we scouted Jordan
