### ISSUE TITLE
Identify first time visitors and serve pulsing highlight next to tour page

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#376]

**Comment by casruger** [comment]
We would like to identify first-time visitors to give them a pop-up highlighting the tour page. 
Therefore, the first question is, is it possible to identify these first-time visitors, and secondly, is it possible to give them a small pop-up or have a blinking highlit dot next to the tour page, only for the first-time visitors. 

The pop-up would preferably look like the blue box in the image which disappears if the visitor clicks somewhere else on the screen.  




![Image](https://user-images.githubusercontent.com/51459017/169277800-4c09b5dc-1e7b-4de7-8c40-d7bf222ac53a.png)

**Comment by hannesdatta** [comment]
Which site is this?

**Comment by heyarviind** [comment]
@casruger can you provide more information like where to show these dots to the first-time users? I can create a demo for you to see, if things go well we will merge it in the main website

**Comment by casruger** [comment]
@heyarviind we would like this pulsing dot to appear next to the tour button (see screenshot). And we would like it to stay there during the full first session of the visitor. The header is visible from every page and moves with scrolling, so we would like the dot to be visible from every page as well. Again, the dot should disappear once the visitor clicked on the tour button or comes back for a second or third  etc. visit. 

![pulsing-tour-dot](https://user-images.githubusercontent.com/51459017/176712406-3e4d3d53-010d-468e-aaeb-a98dc8f76a33.jpg)

**Comment by heyarviind** [comment]
@casruger starting with this, will push an update by tomorrow to review

**Comment by heyarviind** [comment]
https://github.com/tilburgsciencehub/website/issues/366

Also now these two issues are the same? we need to show a pulsing dot with the explainer tooltip for first-time visitors right?

**Comment by casruger** [comment]
We are running a/b tests from Netlify using this feature
