### ISSUE TITLE
Increase the number of tutorials

### ISSUE THREAD

**Issue by casruger** [tilburgsciencehub/website#381]
More people click on the page tutorials than Building blocks when they arrive at the home page. The term tutorials is also more SEO friendly and in addition, I think our building blocks which are labeled 'code snippets' are more than that. 
Therefore, It might be interesting to expand the number of tutorials and let them refer to the building blocks for more details. 

How I see it for forexample R studio: 

Tutorial/Tutorial-R-and-RStudio:
How to setup R and RStudio (explain how to set up like in the building block)(note that you can also make R available in command prompt and refer to that building block)
The basics of R studio (explain what you see in the overview)
Install packages (promote Building blocks on packages like Shiny)

Building blocks:
Building-blocks/Access-R-from-command-promt
Building-blocks/Shiny-apps
Building-blocks/auto-install-r-packages

**Comment by hannesdatta** [comment]
Potentially also define other ways to bundle content

**Comment by hannesdatta** [comment]
Revised doc - will check w/ @srosh2000 about focus and which tutorial to start with

**Comment by casruger** [comment]
Made seperate issues of the tutorials which have not yet been written out
