### ISSUE TITLE
refine descriptions for tutorials

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#390]
Hey @casruger,

I implemented the new tutorial landing page.

Can you please revise the DESCRIPTIONS in _index.html of the respective tutorials so that the landing page for tutorials looks "good"? Right now, the descriptions may not always be good to get attention (they haven't been shown earlier so we didn't pay much attention).

Any other feedback on the new landing page?

See

https://tilburgsciencehub.com/tutorials/

**Comment by hannesdatta** [comment]
length - 3 lines

**Comment by casruger** [comment]
Shortened the description of the tutorial principles of project setup and workflow management #405
