### ISSUE TITLE
[Bug]: Move background up + search icon to the right  place 

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#396]
### Contact Details

h.datta@tilburguniversity.edu

### What happened?

The new landing page broke the positioning of our background pic:

![image](https://user-images.githubusercontent.com/16557730/168545680-1729405c-4c65-4090-a774-e693144cd354.png)

The rounded white shape needs to move up.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by casruger** [comment]
The background on the homepage moved down too much. The curve where the white part begins should be just above the text "Code like a pro." and the loop image. So both the first image and text should be inside the white, while they are partly in blue now.
