### ISSUE TITLE
Replace search bar with tutorials on the homepage

### ISSUE THREAD

**Issue by casruger** [tilburgsciencehub/website#404]
In optimize we can target new visitors with a different version. Might be interesting to replace the search bar with a tour and or tutorial button.

**Comment by casruger** [comment]
Replaced the search bar with call to action buttons in a A/B test for new visitors. 
![Image](https://user-images.githubusercontent.com/51459017/171608335-f2d16722-45eb-417a-a550-45bcf8957efd.png)

**Comment by hannesdatta** [comment]
Run new A/B test on updated landing page, @casruger will post screenshot and results will be discussed next week.

**Comment by casruger** [comment]
Very good results in favor of the new test page (with buttons rather than the search bar). Lower drop-off rates and higher pages per session in favor of the test page. Therefore this test will also be held on all visitors. See issue #446


[Search bar or buttons on homepage test results.pptx](https://github.com/tilburgsciencehub/website/files/9009291/Search.bar.or.buttons.on.homepage.test.results.pptx)
