### ISSUE TITLE
[Development Call]: Prepare Descriptive Statistics Tables and Graphs on Stata

### ISSUE THREAD

**Issue by BilgeKasapoglu** [tilburgsciencehub/website#407]
### Contact Details

b.kasapoglu@tilburguniversity.edu

### Is your content request related to a problem you've encountered during your research process? Please describe.

I have been trying to find a way to create publishable Descriptive Statistics tables and graphs on Stata. I think it would be nice to have a tutorial showing these. There are so many pieces of information all over the Internet but it would be great to summarize them in one/two tutorials.

### Would you like this to be a Building Block or a Tutorial?

Tutorial

### Purpose

Teach our users how to create and modify Stata graphs and tables

### Suggested title

Two-Way Graphs in Stata Made Easy

### Suggested keywords

Stata, Data Visualization, Graph, Tables, Summary Statistics, Descritive Statistics

### Required tools

Stata

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BilgeKasapoglu** [comment]
- [ ] Prepare a do.file to create graphs
- [ ] Prepare a do.file to create tables

**Comment by lachlandeer** [comment]
Closing since no-one working on it actively
