### ISSUE TITLE
fix google analytics on a few of our domains

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#410]
e.g., web-scraping.org - we don't get live tracking data although we're on the site (or, it's really delayed). same with odcm.hannesdatta.com and dprep.hannesdatta.com and thesis.hannesdatta.com.

**Comment by heyarviind** [comment]
@hannesdatta can you please provide (if you can) GA credentials, so that I can debug the problem.

**Comment by heyarviind** [comment]
I have checked for ```web-scraping.org``` and it is working just fine @casruger can you please double check on your side?

**Comment by casruger** [comment]
Hi Arvind, it seems like there might still be a problem. If I visit the site I do not see a visit in Google Analytics. See screenshot of "users in the last 30 minutes" being empty even tho I have the website open in another tab. 
<img width="956" alt="image" src="https://user-images.githubusercontent.com/51459017/201179024-14ad3dbf-d5d6-4811-935b-ebb38aad10df.png">

**Comment by heyarviind** [comment]
@hannesdatta can you please merge this pull request on other website

https://github.com/hannesdatta/web-scraping.org/pull/21

**Comment by hannesdatta** [comment]
we're gonna migrate to a new tool eventually, given GDPR concerns.
