### ISSUE TITLE
Port repos to Bookdown

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#412]
For an open education project by @gknox79, this repository (https://github.com/tilburgsciencehub/course-customer-analytics) needs to be ported into an ebook format - using https://tilburgsciencehub.com/make/ebooks/?utm_campaign=referral-short. I feel bookdown may be the most appropriate thing.

The look and feel of this web book/ebook need to be similar to https://r-graphics.org/  or https://rafalab.github.io/dsbook/ (the latter has a download as PDF button, we we need to have, too!).

The main goal here is that students can access the book as a website and download it as a PDF.

@BilgeKasapoglu - something for you?

@casruger to make sure it enters our production pipeline (e.g., free lab capacity).

Start w/ the title page/landing page and first chapter or so, and then I'd like to review it before we do the entire thing.

Btw, you're working on the fork, the original repos is available at https://github.com/gknox79/customer-analytics).

Please launch the ebook as a GitHub Pages site, see here for the instructions. https://bookdown.org/yihui/bookdown/github.html

**Comment by BilgeKasapoglu** [comment]
Dear @hannesdatta,

I have been having hard time to post the content to GitHub pages. You said that you would like to see the content on a website. I tried using the Github pages. However, I cannot see my files on the website as you can see here: https://bilgekasapoglu.github.io/customer-analytics-bookdown/ . Then, I considered using Hugo to publish the website but I could not. Would you please help me figure this out? Thank you in advance

I am adding you to the repository : https://github.com/BilgeKasapoglu/customer-analytics-bookdown.git
Best
Bilge

**Comment by juliehabets** [comment]
@hannesdatta is this still necessary as the CA course has already been given?

**Comment by lachlandeer** [comment]
closing as I don;t see this happening anytime soon. 

reopen if you want this done in the next 6 months and assign a current RA to work on it
