### ISSUE TITLE
add new example

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#414]
Please add this fantastic ebook/web companion as an example item to our page:

https://hschuett.github.io/BayesForAccountingResearch/

@hschuett is a colleague from accounting at TiSEM!

**Comment by juliehabets** [comment]
@casruger  can you maybe help me with this? I am happy to write the contents for this example, however I'm not sure of the steps needed to actually make it happen :)

**Comment by juliehabets** [comment]
@hannesdatta i created a PR and added the example!
