### ISSUE TITLE
move regression content to Tilburg Science Hub

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#425]
Hi @srosh2000 and @BilgeKasapoglu,

I need this content (https://dprep.hannesdatta.com/docs/building-blocks/regression-analysis/) to move from the dprep site to Tilburg science hub.

Please make individual building blocks, and wrap it up in a tutorial that links to these building blocks. The tutorial should be narrative, as the existing ones. 

The tutorial will be used for the upcoming dprep edition. 

I ideally would like to have the tutorial online by the end of july.

Please let me know who will take the task!

Thanks!

**Comment by srosh2000** [comment]
Hi @hannesdatta , 
I can work on this. Just to make sure I understand the task right, we would have building blocks namely:
- evaluate model assumptions 
- outlier screening 
- model reporting 
- visualise linear relationships 
- predictions 
and the tutorial would tie these together by giving overview of reg analysis and descriptions for each step while linking to building blocks?

**Comment by srosh2000** [comment]
https://tilburgsciencehub.com/building-blocks/analyze-data/regressions/regression-analysis/ 

just noticed we have this content... should we remove this then? cuz the tutorial would cover all of it by linking separate building blocks

**Comment by hannesdatta** [comment]
yes - makes sense.

**Comment by hannesdatta** [comment]
if possible, retain the shortlink somehow (tsh/learn/regression, i.e., port that to the new page)

**Comment by juliehabets** [comment]
@srosh2000 is this still an issue or can it be closed? :)

**Comment by hannesdatta** [comment]
We now have rich regression content at TSH. We can close.
