### ISSUE TITLE
write proper overview/intro to building block on git

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#426]
We were about to promote https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/use-github/github-workflow/ on LinkedIn/Twitter, but after following the link ourselves, we realized that users may totally not get what this is all about. In short, we're missing a proper introduction to the content.

Deliverable: an updated building block that can be understood for (a) users that have never been on the site, and (b) users that click on a campaign on twitter to learn more about git/github.

**Comment by srosh2000** [comment]
@hannesdatta Just drafted an intro and made pull request. Lemme know if it fits well or needs further improvement.
