### ISSUE TITLE
Offline advertisments targeting Tilburg University researchers

### ISSUE THREAD

**Issue by casruger** [tilburgsciencehub/website#431]

**Comment by hannesdatta** [comment]
explore instagram targeting

**Comment by casruger** [comment]
I made a couple of drafts, but I think it would be useful to share some thoughts on what we would like to communicate. 
https://docs.google.com/presentation/d/1BNOTva3oGG_hsYAWcghsQPBmgtBFizo8MEnhVceAo5o/edit?usp=sharing

**Comment by casruger** [comment]
An other interesting ad could be: 
Hey researcher what do you do this summer? Get to know open science and contribute to Tilburg Science Hub.

**Comment by hannesdatta** [comment]
I like this.

**Comment by casruger** [comment]
Look at the possible offline methods with which we can advertise on campus like folders, posters etc.

**Comment by casruger** [comment]
For a potential a4 sheet get inspired by #379

**Comment by casruger** [comment]
Physical ideas: 
- replacing the coffeecups in vending machines with cups with our own customized printing ~ 250,- for 1000 cups https://www.cupsz.com/nl/products/225-ml-8-oz-enkelwandig
- Banner on the bridge to the library 200cm x 100cm ~40,- 
- Notepad with 25 pages (to hand out during offline events) 110,- 50 books 
- Pens 60,- 50 pens
- Mug 80,- 10 mugs
- Doorhanger 110,- 100  doorhangers 
- Wine box to give to successful researchers 50,- for 5 boxes 100,- for 10 boxes (https://www.reclameland.nl/drukken/wijnkist)
- Cavabottle 20,- per bottle https://bedruktefles.nl/product/cavafles-etiket-maken/
- Redwine bottle 25,- per bottle https://bedruktefles.nl/product/rode-wijn-etiket-maken/
- A5 Notebook 130,- 10 Notebooks
- Availible/ unavailable slider on door 35,- per slider 
- USB hub 230,- 10 hubs

**Comment by casruger** [comment]
Deliverables: 
Uitschrijven mogelijkheden en keuze Tobi and Hannes

**Comment by casruger** [comment]
Chosen for Mugs and Banner on the bridge to Library #

**Comment by hannesdatta** [comment]
Cool!

From: Cas Ruger ***@***.***>
Date: Friday, 23 December 2022 at 13:34
To: tilburgsciencehub/website ***@***.***>
Cc: Hannes Datta ***@***.***>, Comment ***@***.***>
Subject: Re: [tilburgsciencehub/website] Offline advertisments targeting Tilburg University researchers (Issue #431)

Chosen for Mugs and Banner on the bridge to Library #
