### ISSUE TITLE
enhanced contributors page

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#432]
We could at a list of all the names that contributed to the site. This shows our gratitude and could be an incentive for some people to be on the list.

**Comment by hannesdatta** [comment]
Done w/ the first draft! 

<img width="226" alt="image" src="https://user-images.githubusercontent.com/16557730/180388634-c676cf45-87db-48d8-b9f3-9849a9a4e21e.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/16557730/180388699-f9004af6-d143-4a71-bbe1-6520a6d66fc9.png">

**Comment by hannesdatta** [comment]
I would love to UPDATE our list of contributors.

Currently, this is just a list of NAMES, see https://tilburgsciencehub.com/contributors/.

I want to 
- [ ] allow contributors to TSH to commit their own "profiles" in form of a markdown with their interest, a photo, etc. see https://music-economics.org for an example for speakers (I own this site and the code is publicly available on my github). Think of: name, about description, links to social media profiles, email address. and a photo.
- [ ] link these pages to individual articles via tags in the header
- [ ] include link to TSH contributors somewhere more prominently on the page

NEXT STEP:
- [ ] HTML draft of contributor page
- [ ] HTML draft of updated list of contributors that will ultimately replace https://tilburgsciencehub.com/contributors/

**Comment by hannesdatta** [comment]
- Add skills
- Make picture on single article page a bit less prominent
- Update the overview / list page: use round photo, some effect.
- description_short & description_long
- ability to add some free text
- title rename to `name`
- add generic picture/placeholder if stuff hasn't been placed yet

**Comment by thierrylahaije** [comment]
@hannesdatta Completed, pushed to a new branch named 432-contributors. Please let me know whether you like the layout and structure now. I updated all issues you mentioned above. Did not do a PR yet since I am not sure whether the layout is correct now and we do not have the content for the contributors yet.

**Comment by hannesdatta** [comment]
- [ ] Please make this background transparent

<img width="424" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/6ebcabcc-64b6-4c1b-8fb1-1296bebc660a">

- [ ] Please already create your full profile (the reason is that we need to show it to others so they know exactly how to place their files

- I like the animation :)



- [ ] it's unclear to me yet how we link your posts to your profile. Please show on your profile page which recent posts/edits you have made (i.e., ability to click through to content).

- [ ] In line with the previous comment, make "names" clickable in the building blocks and tutorial section so people can get from A to B.

- [ ] Expand the about menu to encompass a menu point that you can view the contributor page.

<img width="81" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/6618eb38-6c7d-44a1-89f0-545d086897e1">

**Comment by thierrylahaije** [comment]
@hannesdatta  I fixed all issues mentioned, except for the about sub-menu, since I would like to discuss with you first what we will exactly display in the sub-menu. Since you also wanted the blogs in the about sub-menu, I would like to now how we want to display them (do we also show singles or just the main page (blog/contributor page)), since this will affect the way I will design the display the sub-menu.

All other issues have been pushed to branch 432-contributors

**Comment by hannesdatta** [comment]
@thierrylahaije - another important one: the images are currently stored in the template. You need to move them out to a different directory (as they do not belong to a general theme). can you place them somewhere here?

https://github.com/tilburgsciencehub/website/tree/master/static

**Comment by thierrylahaije** [comment]
@hannesdatta I updated the development branch (432-contributors). Can you check if everything is as expected? If so, I can create a PR
