### ISSUE TITLE
update budget

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#444]

**Comment by lachlandeer** [comment]
Since 2023 budget seems to be OK (i.e. we're spending it), closing this

if needs re-open please add to the current core team board so we can easily find stuff we need to do!

**Comment by kleintob** [comment]
Indeed, I worked this out with Saskia van Gurp in November 2022. She sent an update on 11 January, where all the 2022 spending was all in. It's all in good shape.
