### ISSUE TITLE
Sharing non TSH content on LinkedIn and Twitter

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#445]
We currently use LinkedIn and Twitter as sort of marketing tool. I think the community would expand if we shared interesting stuff for researchers and students for which we receive no benefits. Like interesting papers on open science, or news from Tilburg University that researchers might like. That way people use us as a kind of news channel and we could expand our following. 

I am not in the publishing bubble so if you know any interesting releases (maybe the web scraper paper you wrote?) Let me know!

**Comment by hannesdatta** [comment]
@lachlandeer - would you be willing to take over the Twitter account for some time to keep building our network?

**Comment by casruger** [comment]
As far as I know Lachlandeer has picked this up, so we can close this issue correct @hannesdatta ?
