### ISSUE TITLE
[Development Call]: Install Stata Packages

### ISSUE THREAD

**Issue by casruger** [tilburgsciencehub/website#452]
### Is your content request related to a problem you've encountered during your research process? Please describe.

It is currently not explained how to install packages in Stata. Please add this information in the same we did it for python namely, by adding a page called Install Stata Packages. 

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Purpose

Make clear how someone can install and use packages in Stata

### Suggested title

Install Stata Packages

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliehabets** [comment]
Hi @thierrylahaije  care to take this up? :) Don't think it will take too long to write this building block

**Comment by thierrylahaije** [comment]
@juliehabets Hi Julie! I see this issue is still assigned to me, while we talked about this issue a little time ago and that it would be better to assign someone who is better in R than me, I am more of Python. Could you assign someone so that I this issue can be fixed? Thanks!
