### ISSUE TITLE
[Feature]: Check for unique short links

### ISSUE THREAD

**Issue by casruger** [tilburgsciencehub/website#453]
### Is your feature request related to a problem? Please describe.

We use short links for every page which could lead to two pages with the same short link. 

### Describe the solution you'd like

A python script that checks all (short) links and whether the new one is unique. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
Hasn't happened so far. Let's retire this one.
