### ISSUE TITLE
update documentation + signin procedures

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#489]

**Comment by hannesdatta** [comment]
- [ ] add to onboarding guide the new ad services we are using (all in one place)
- [ ] best practices in sharing accounts
- [ ] getting our accounts for 2 factor authentication

**Comment by casruger** [comment]
Added our marketing channels (social media and advertisement) to the onboarding https://github.com/tilburgsciencehub/onboarding/wiki/Website-visitors-data-and-marketing-channels

**Comment by casruger** [comment]
Google ads has been set up correctly for 2step authentication since you can add new accounts with their own email. Keeping tsh@tilburguniversity.edu the main account. The same way google analytics works.

**Comment by casruger** [comment]
@hannesdatta could you confirm that this is your facebook? https://www.facebook.com/hannes.datta
If so, I could make you the main account for the facebook page's and advertisements.

**Comment by casruger** [comment]
For Twitter we currently have shared our login information, we could get started with https://tweetdeck.twitter.com/. Here yo can invite individual Twitter accounts to manage the main account just like on LinkedIn.

**Comment by casruger** [comment]
All channels are set up for two-step verification. If someone wants access that person needs to get added with their own login (in most cases e-mail address) by Hannes Datta which is the administrator on all channels.
