### ISSUE TITLE
by end of september: small presentation about ad effectiveness/experience on the site (+ budget spent, etc.) + defining way forward

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#491]

**Comment by casruger** [comment]
Made a small presentation about our ad spent and what the effectiveness has been. Could use our findings to come up with the next steps. https://docs.google.com/presentation/d/1D4d4Lo0MuHEnTpNYdcuC8zVM_7ezpj0F/edit?usp=sharing&ouid=117986693098938196251&rtpof=true&sd=true
