### ISSUE TITLE
Suggest change to: building-blocks/configure-your-computer/statistics-and-computation/latex.md

### ISSUE THREAD

**Issue by bodr101** [tilburgsciencehub/website#495]
### Contact Details

b.deruijter@tilburguniversity.edu

### Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)?

a code to download a certain package using brew cask has been changed. So, only one line needs to be changed in the article.

### Describe the solution you'd like

**old way of adding mactex to mac:**
(base) MacBook-Pro:~ bodr$ brew cask install mactex

**Error message:**
Error: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.

**New way of adding mactex to mac:**
(base) MacBook-Pro:~ bodr$ brew install mactex --cask

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
Do a thorough search on the site to see whether this still is an issue. Got a Macbook, @MatthijstenTije, to test it out?
