### ISSUE TITLE
[Bug]: Search doesn't work

### ISSUE THREAD

**Issue by casruger** [tilburgsciencehub/website#499]
### What happened?

New visitors on mobile can't use the menu and the search function in the menu. 

### To reproduce

On mobile, open new incognito session, go to tilburgsciencehub.com, click on the search icon. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by casruger** [comment]
Some async in the header couses this fixed with pull request #500 but try and pinpoint further

**Comment by casruger** [comment]
Async of /js/terminal.js coused this issue. The async has been removed leading it to load faster and preventing this issue. #503

**Comment by casruger** [comment]
Plus, search does not work on both mobile and desktop. 
Search "pipeline" and press enter does not give any suggestions.

**Comment by hannesdatta** [comment]
Just checkout an older version -- hashed ac5cd3590543a1a31a8fad51fddd5b63c483938c from beginning of august 2022 -- and launched locally. search works then. I would diff/compare the state of index.html and corresponding headers/footers to identify which script exactly is causing these issues.

**Comment by hannesdatta** [comment]
found the bug:

```
<script src="https://cdn.jsdelivr.net/npm/algoliasearch@4.5.1/dist/algoliasearch-lite.umd.js" integrity="sha256-EXPXz4W6pQgfYY3yTpnDa3OH8/EPn16ciVsPQ/ypsjk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/instantsearch.js@4.8.3/dist/instantsearch.production.min.js" integrity="sha256-LAGhRRdtVoD6RLo2qDQsU2mp+XVSciKRC8XPOBWmofM=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.css@7.3.1/themes/reset-min.css" integrity="sha256-t2ATOGCtAIZNnzER679jwcFcKYfLlw01gli6F6oszk8=" crossorigin="anonymous">
<script src="/js/main.js"></script>
```

these scripts cannot be loaded with `defer` because then the order in which these scripts become available is incorrect (think main.js depends on algolia's two scripts above).

this is a solution in case our site speed drops tremendously. there is quite some talk online that this may happen I believe. w/ webpack, we could bundle all of these scripts and then combine them when loading them. https://webpack.js.org/.

action: let's monitor site speed after having fixed the search. check back in a month or so.

**Comment by casruger** [comment]
Seems like this stil does not work half of the time.

**Comment by casruger** [comment]
Issue has been fixed by removing the async of loading jsquary. Site performance dropped a bit from 82 with the bug to 77 without the bug. But it is fixed now
