### ISSUE TITLE
clean up board, create card views for new team members

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#507]
With many new team members, please perform some maintenance on the board.

- Remove team members who have left us; re-assign issues if needed
- Create new overview cards on the board for new team members
- Ensure that recently created cards are assigned to team members, and appear in the correct column(s) on the Scrum board
- Make the board the place where TSH team members begin their day - I haven't really communicated that today. Thanks!

**Comment by casruger** [comment]
I am not sure what the status of issue #302 and #425 are. All other issues which Bilgi was assigned have been closed or given the correct status.

**Comment by casruger** [comment]
All members have their own board, and assigning the open tasks will be done in our scrum meetings.
