### ISSUE TITLE
[Edit]: Renaming Blade to HPC

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#513]
### Contact Details

h.datta@tilburguniversity.edu

### Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)?

The name of the Blade computing environment has changed to HPC TiU (High-Performance Computing).

Please update all references to the blade on our site and the onboarding guide.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliehabets** [comment]
Done! See e.g., https://tilburgsciencehub.com/building-blocks/configure-your-computer/infrastructure-choice/lisa_cluster/
