### ISSUE TITLE
Verify whether we can get a Netlify open source license

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#518]
We currently use Netlify but need to pay to add (technical) team members.

However, Netlify has an open source program so we could make use of their features for free.

__Deliverables:__
- Please evaluate whether we qualify for such a plan.
- If not: come up w/ action points what we would have to do to conform.
- If yes: fill in application (or be in touch with me if we need to do something else).

I tagged @casruger and  @juliehabets - briefly chat about capacity issues here and decide who wants to tackle it. Thx!

**Comment by juliehabets** [comment]
@casruger i can pick this up!

**Comment by juliehabets** [comment]
@hannesdatta i looked into this and have only 1 action point to check. One requirement for Netlify open source is the following:  

- Must feature a link to our service on your main page, or all internal pages.  You have two options:
1. We have premade badges for your convenience 
2. You may create your own link, which should read “This site is powered by Netlify”, and include a link back to our home page.


As of right now, I cannot find such a badge on the site. I suggest that we use a premade badge, the code is already given on this website (at the bottom): https://www.netlify.com/press/#badges 

I don't know who normally makes the hmtl changes? Let me know and if it is finished, I can fill out the form to apply!

**Comment by casruger** [comment]
@juliehabets, a badge in the footer is the most aesthetically pleasing option I think. 
The best option in my opinion is below our copyright (see first screenshot) . 


![Image](https://user-images.githubusercontent.com/51459017/193547474-4be30d97-a382-428e-88bc-ca664522776b.png)

But we can also have it next to our disclaimer. 


![Image](https://user-images.githubusercontent.com/51459017/193547966-2836adf4-bc10-403b-93ff-3d1e532e5c0d.png)



Let me know what you think, or if you have an other place, then I will added it at put it online.

**Comment by juliehabets** [comment]
@casruger I think both look good, so for me you can go with your preferred one! Let me know when it is added online :)

**Comment by casruger** [comment]
@juliehabets the badge is added and online. Good luck with the request!

**Comment by juliehabets** [comment]
@casruger request is done! Who admins the TSH email? (i had to submit the email as well so I chose that one)

**Comment by hannesdatta** [comment]
I asked IT to add you to the inbox, @juliehabets!

**Comment by juliehabets** [comment]
Looks like it worked, however Netlify responded this:

_Hi there,
 
In order to sponsor a team for this project we need a netlify login to attach things to  - would you or someone on your team let us know a Netlify login email that should be the initial team owner?  They'll be able to invite other owner-level members.
 
You can find your login email at https://app.netlify.com/user/settings in case you already have one associated with some other email address.
 
Let us know if you have any questions. Thanks!_

I do not have access to any of this data, so please let me know if you do!

**Comment by casruger** [comment]
Received the open source license
