### ISSUE TITLE
[Development Call]: Import Large Datasets Into Python

### ISSUE THREAD

**Issue by MKT-Analytics** [tilburgsciencehub/website#528]
### Is your content request related to a problem you've encountered during your research process? Please describe.

When I was working with a large dataset - larger than my RAM, I was not able to read this dataset with the use of pandas due to memory error. I could try using AWS services, but I was searching for a quicker solution. 

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Purpose

Teach users how to work with large datasets in Python on a local machine. 

### Motivation

I found out about Dask, a library in Python for parallel computing, which allows me to read files way bigger than my RAM. It's solved my issue with a larger-than-memory dataset.

### Suggested title

Import Large Datasets Into Python

### Suggested keywords

Python, pandas, Dask, import, data, data preparation, big data, large datasets, memory, RAM, MemoryError

### Required tools

Python

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliehabets** [comment]
I believe this is closed now, right?

**Comment by MKT-Analytics** [comment]
That's correct! I'm closing the issue
