### ISSUE TITLE
PowerBI & Tableau building block idea

### ISSUE THREAD

**Issue by juliehabets** [tilburgsciencehub/website#540]

**Comment by MKT-Analytics** [comment]
@juliehabets [https://www.tableau.com/academic/students](https://www.tableau.com/academic/students) that's what I meant in the meeting

**Comment by juliehabets** [comment]
@MKT-Analytics thanks for the link!! Somewhere next week you can expect the draft i think

**Comment by lachlandeer** [comment]
too vague to be actionable for now. 

reopen down the line if we feel like this is a direction we want to head. if do so, create an itemized list of building blocks to create
