### ISSUE TITLE
[Development Call]: Public API with documentation to learn data retrieval w/ APIs

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#542]
### Contact Details

h.datta@tilburguniversity.edu

### Is your content request related to a problem you've encountered during your research process? Please describe.

To train students in data retrieval with APIs, I require a publicly available API w/ documentation that students can use to "try" out an API.

__Desired features__
- the whole thing runs in docker so we can launch it flexibly on VMs
- ideally is written in Python (Fast API)
- mimicks a user-based social network with a couple of endpoints (e.g., users <-> song plays <-> artists; or users <-> playlists <-> artist charts or something like that) - we can think about the specifics together ("what's a cool application?")
- inspired from books.toscrape.com -- a demo for learning how to scrape -- now that I think about it, we could just use their data and have a parallel API for it, keeping things simple. what do you think?
- holds the "real" data in an SQlite database
- endpoints need to support iteration, extending limits, etc.
- API has to have live & browseable documentation (so that endpoints are documented)
- initially, we do not require authentication w/ the API
- in a future version, we could have students test out different ways to authenticate (e.g., simple API key -- that way, we can collect email addresses of our users, e.g., restricting only to Tilburg initially), OAuth for user-level data.
- the whole project ideally is accompanied by a fancy-looking, Tilburg science hub-styled website via HUGO. Maybe the site takes off? books.toscrape is quite popular...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
@thierrylahaije - maybe something for you? Gotta discuss priorities here w/ @juliehabets I guess, but I feel you may be interested in this.

**Comment by thierrylahaije** [comment]
@hannesdatta definetely interested in this project!

**Comment by thierrylahaije** [comment]
@hannesdatta is this still something you would like to do? I saw this issue was still open. I can start working on it.

**Comment by hannesdatta** [comment]
hey there,
YES - a 'tool' to learn APIs is still very much needed. Which framework do you suggest?

**Comment by hannesdatta** [comment]
__Infrastructure:__

1. fastAPI
2. MySQL database that is populated via R scripts that @hannesdatta writes (CSV)
3. website interface (PHP)

*Infrastructure needs to be "fired up" through a docker file/container.*

__1. A few notes on the API__
- needs to have authentication for selected endpoints
- some endpoints are only accessible after authentication
 


__3. A few notes on the interface__
- Website that (a) clearly has some examples on how to use our API, (b) makes clear this is a dummy site, (c) provides "views" of the data -- say, a mock-last.fm site
- needs to allow users to generate API keys (but no login required)

**Comment by hannesdatta** [comment]
Continuing this work on a separate repository at https://github.com/tilburgsciencehub/apis-to-scrape

**Comment by thierrylahaije** [comment]
This issue will be closed since all work and related issues have been done in the new repository -> https://github.com/tilburgsciencehub/music-to-scrape
