### ISSUE TITLE
[Development Call]: Filling in PDF forms using Python

### ISSUE THREAD

**Issue by paulina-ambroziak** [tilburgsciencehub/website#543]
### Is your content request related to a problem you've encountered during your research process? Please describe.

Each month, we must complete several forms, which takes time. Making it automatic will save us time and effort.

### Purpose

How to automate filling in PDF forms with the use of Python?

### Motivation

Saves time and effort, avoids mistakes

### Suggested title

Filling in PDF forms using Python

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
We've automated it and it works like a charm! :)
