### ISSUE TITLE
add broken link checker to our site

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#572]
Hi @thierrylahaije,

I tried to look for the broken link checker but it seems not to be activated on our site.

Can you please add it to our site?

Thanks!

**Comment by thierrylahaije** [comment]
Hi @hannesdatta,

Just created a new repository and pushed everything. It is now in here:
https://github.com/tilburgsciencehub/broken-link-checker/

During testing I found out that I am no longer able to create secrets on organizational level (I cannot enter the settings tab of the organization), which makes the script currently unable to create issues. Therefore I cannot set and check the organizational secret code for the github api. Can you give me the correct permissions? Than I can complete the last bit.

**Comment by thierrylahaije** [comment]
I finished this task, I will therefore close this issue.
