### ISSUE TITLE
[Development Call]: Pre-processing text data for NLP tasks

### ISSUE THREAD

**Issue by srosh2000** [tilburgsciencehub/website#584]
### Is your content request related to a problem you've encountered during your research process? Please describe.

When working with text data pre-processing the data is of utmost importance to have quality inputs for accurate outputs. So this building block can explain various steps and caveats to keep in mind when cleaning text data and point to good tools and resources for the same.

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srosh2000** [comment]
@shrabasteebanerjee  any inputs from your side on tips on pre-processing text data that I could include? Or a proposed structure for the building block?

**Comment by lachlandeer** [comment]
Interesting idea for content @srosh2000  

Pre-processing generally is tough as it depends what the ultimate goal is -- and whether once sticks to a Bag of Words approach or goes into embeddings I've had different success with different amounts of pre-processing. (This in itself would be an interesting piece of content, perhaps separately)

My question would be what do you wanna construct here? Is it a here's some different packages that might be useful for different problems in R and/or Python? Or do you want more of an example flavour (i.e. let's do something on a data set for a particular problem)? Or something else entirely?

**Comment by srosh2000** [comment]
@lachlandeer Thanks for the inputs! I will def follow up on bag of words vs embeddings approach. When to use either, context dependency etc

I am thinking of having a more general building block for starters taking them through various steps of text preprocessing and R/Python libraries/functions that can be used for each step e.g. tokenization, stop words removal etc. 

I could also go through each step using a toy example(from a personal project dataset or kaggle dataset) and include the code snippets and corresponding output to show how it would look like after each step of processing.

**Comment by lachlandeer** [comment]
closed with #597
