### ISSUE TITLE
[Development Call]: Enhancing git

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#595]
### Contact Details

h.datta@tilburguniversity.edu

### Is your content request related to a problem you've encountered during your research process? Please describe.

I found some of these tools, especially restore-mtime, fantastic to use in combination of Git w/ make.

https://github.com/MestreLion/git-tools/

Let us highlight this in the form of a building block.

Problem: When checking out a repository or new branch, the timestamps of checked out files are the ones when we checked out the repos, not when they were originally committed. This causes problems downstream (say, when we use Git in combination with make).

Using git-tool's restore-mtime, we can fix this problem. In particular, the tool changes the timestamps to the ones when the files were last committed.

Usage:

git restore-mtime --test (preview changes)
git restore-mtime (actually do the changes).

Give a few examples.

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
closed by #685
