### ISSUE TITLE
[Development Call]: Best Practices for Git Branching

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#605]
### Is your content request related to a problem you've encountered during your research process? Please describe.

Yes -- too many branches and naming conventions make it hard to keep track of project development

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Purpose

Discuss the most popular ways people branch and name branches. Let's 3 altternatives 

We should then pick one and then adopt that for TSH

### Suggested title

Best Practices for Git Branches

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MKT-Analytics** [comment]
Hello @lachlandeer. I've come up with a proposed outline for this building block, including some sample text. My idea was to first familiarize the reader with the concept of branches before diving into an explanation and comparison of different branching strategies. Please let me know what you think of the structure and chosen strategies. Cheers, Paulina.
[git-branching-strategies.docx](https://github.com/tilburgsciencehub/website/files/10701957/git-branching-strategies.docx)

**Comment by MKT-Analytics** [comment]
Here's the text from the file:

**1.	Git branching strategy**
A Git branching strategy helps developers to work together on a project, track changes and maintain multiple versions of the codebase. There are several different Git branching strategies available, and each one has its own strengths and weaknesses. The right strategy depends on the specific needs of the project and the team.

**1.1	Git branch**
A branch in Git is a separate line of development in the repository. Branches are a fundamental concept in Git as they enable teams to maintain multiple versions of the codebase and easily switch between them.
The main reason to use branches in Git is to provide a way to isolate changes made to the code. When you create a new branch, you make a copy of the current state of the code, and any changes made on that branch are kept separate from the main codebase. This allows multiple developers to work on different features or fixes without affecting each other's work. When a feature or bug fix is complete, the changes can be merged back into the main codebase, preserving the history of the changes and providing a clear and concise record of what was done and why.

**1.2	The main branch**
The “main” branch in GitHub (formerly known as "master") is the default branch name when you create a new repository, and it is the branch that is used to store the production-ready code. The "main" branch is usually the branch that is deployed to live servers and is considered the main source of truth for your codebase.
 
![image](https://user-images.githubusercontent.com/62939823/217952631-02f33b99-d368-42b1-8483-bc2d08582340.png)


**2.	Best practices for naming branches** 
Describe best practices to name branches (in form of bullet points with tips)

**3.	Strategy 1: Trunk-Based Development**
-	Description of how it works
-	Picture visualising it (similar as in 1.2)
-	Pros & cons 
-	Who is it best for?/type of teams
-	What type of projects is it best for? 
-	How to do it in command line? (code)
Trunk-Based Development is a Git branching strategy that prioritizes the use of a single branch for development, typically named "main" (also referred to as the "trunk"). The basic idea behind Trunk-Based Development is to make small, frequent changes directly to the “main” branch and share those changes with other team members as soon as possible.

**4.	Strategy 2: Feature Branching**
-	Description of how it works
-	Picture visualising it (similar as in 1.2)
-	Pros & cons 
-	Who is it best for?/type of teams
-	What type of projects is it best for? 
-	How to do it in command line? (code)
Feature Branching strategy uses feature branches for each new feature, with developers merging their feature branches into the "main" branch when complete. 

**5.	Strategy 3: Git Flow**
-	Description of how it works
-	Picture visualising it (similar as in 1.2)
-	Pros & cons 
-	Who is it best for?/type of teams
-	What type of projects is it best for? 
-	How to do it in command line? (code)
Git Flow is a popular branching strategy that uses two main branches - "main" and "develop". The "main" branch is the stable production-ready code, and the "develop" branch is where all development takes place. Feature branches are created from the "develop" branch and merged back into "develop" when complete. Releases are created from the "develop" branch and merged into "main" with a tag.

**6.	Conclusion/comparison**
Conclusion in a form of a table to show summary of each strategy in easily comparable way.

**Comment by lachlandeer** [comment]
Thanks @MKT-Analytics 

This looks good. A little worried about the length. An alternative would be two blocks, one "what is git branching" which is essentially 1 and 2 of above, and another on best practices which is 3,4,5. What are you thoughts?

With Strategy 3 -- are you thinking of branches as `main`, `dev` and then stuff people work on like `feat/feature1` and so on?

**Comment by lachlandeer** [comment]
Thinking more about this two block style:

Block one: Git branching

* What? Why? When might I do this?
* Create a branch `new-branch`, make a few commits, compare new branch to master show they're different 
* Merging branches

There's also a hodge-podge of stuff here: "https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/use-github/github-workflow/" that we might want to restructure as part of a development of the "Version and Share Code with Github" part of the site

Block 2: Best Practices for Branching

* So, now you (reader) wanna adopt branching. How should you do it? 
* Here's three styles, outline each, pros and/or cons

**Comment by MKT-Analytics** [comment]
The building block was merged, closing the issue. Created separate issues for practical example (#653) and branch naming guidelines (#665).
