### ISSUE TITLE
[Development Call]: Acknowledging TSH content developers

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#607]
### Is your content request related to a problem you've encountered during your research process? Please describe.

It would be nice to have a page in the "about" section where we can list past and present content developers who work within TSH. It gives them somewhere they can point to and say "hey, this is me" and here's what I've done. Useful for their job hunt and also a "feel good"

I'd propose a page that splits into "current" and past. A small pic from their linkedin, description of their interests and perhaps link (automatically?) to their two most recent contributions?

Could also update core team to include Lachlan and Shrabastee

### Would you like this to be a Building Block or a Tutorial?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shrabasteebanerjee** [comment]
Core team update done! Definitely need a fresh content developer page, this one is somewhat out of date - https://tilburgsciencehub.com/contributors/

**Comment by lachlandeer** [comment]
this has been updated. closing
