### ISSUE TITLE
[Development Call]: Interpreting linear regression models in R

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#620]
### Is your content request related to a problem you've encountered during your research process? Please describe.

Single var linear regression - how to interpret when

lin-lin
lin-log
log-lin
log-log 

Then do similar for multivar - and note the differences.

Need one place to direct students to consistently

### Would you like this to be a Building Block or a Tutorial?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
@fleurlemire - good comment to assign this to someone - can you inquire who's available at move this item ahead?

**Comment by valerievossen** [comment]
This building block is not written yet, right? @fleurlemire

**Comment by fleurlemire** [comment]
No, indeed, as far as i know, it is not! @valerievossen

**Comment by MatteZic** [comment]
If you wanna do it, I have a really nice doc that goes through everything step by step. I can send it over @valerievossen

**Comment by MatthijstenTije** [comment]
I am going to start working on it @matteozicari, so if you could send it to me. It would be really appreciated.

**Comment by MatthijstenTije** [comment]
Valerie and I added a Pull request for this building block @shrabasteebanerjee, looking forward to hearing your feedback!
