### ISSUE TITLE
[Development Call]: marginal effects with `margins` in R

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#621]
### Is your content request related to a problem you've encountered during your research process? Please describe.

marginal effects used to be hard in R, now `margins` makes it easy 

simple text book example extending from #619 to compute APE and AME and interpret correctly. Maybe add how to export via `modelsummary`

### Would you like this to be a Building Block or a Tutorial?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
hey @gmullin-tiu 

Is the version currently on the TSH site the draft version of what you worked on?

**Comment by gmullin-tiu** [comment]
Hey, yes, it is. Let me know if you have any comments on what to change. I had a short tip section with math language, but I did not manage to make it render it on the site. I am going to ask around to see how to do it (I did not find any building block that already had math language to imitate)

**Comment by gmullin-tiu** [comment]
I managed to include the equations by looking at this https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/write-your-paper/amsmath-latex-cheatsheet/
 @srosh2000 as far as I understand it works when I call katex at least once in the file, then every other equation wrapped in $ or $$ is rendered correctly.
