### ISSUE TITLE
[Development Call]: Diff-in-diff: the latest developments

### ISSUE THREAD

**Issue by shrabasteebanerjee** [tilburgsciencehub/website#622]
Quick primer for tools to tackle dynamic DID with heterogeneous treatment effects

**Comment by lachlandeer** [comment]
Packages to think about for R include

`did`
`did2s`

this looks interesting but havent used it:

`diddesign`

**Comment by lachlandeer** [comment]
See also: https://asjadnaqvi.github.io/DiD/

**Comment by shrabasteebanerjee** [comment]
Naz does a nice job with her post here! Something to draw on for inspiration, and also cite: https://towardsdatascience.com/uncovering-the-limitations-of-traditional-did-method-2f068f56d19a

**Comment by lachlandeer** [comment]
Useful paper that we could draw from:

https://www.jonathandroth.com/assets/files/roth_act10.pdf

**Comment by shrabasteebanerjee** [comment]
@lachlandeer is that the paper you meant to share, or was it this one? :P https://www.jonathandroth.com/assets/files/DiD_Review_Paper.pdf (@srosh2000 good summary of DID developments and their applicability in different settings!)

**Comment by lachlandeer** [comment]
yes, indeed it was that paper -- my bad :)

I think a way forward to make this manageable could be to propose 2-3 building blocks each around specific ideas, that can be linked together for the interested reader. I think doing this in one might be "too much" to take in at once.
