### ISSUE TITLE
[Bug]: script fails for fetching popular pages

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#623]
### What happened?

fetch-popular-pages-ga fails daily 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by heyarviind** [comment]
this would be fixed by Monday

**Comment by heyarviind** [comment]
this issue has been fixed, please see the action logs for confirmation @lachlandeer 

https://github.com/tilburgsciencehub/website/actions/runs/4149773476/jobs/7178964984

**Comment by lachlandeer** [comment]
perfect thanks!

will close this

**Comment by lachlandeer** [comment]
see #629
