### ISSUE TITLE
[Development Call]: Loading data in R with `vroom`

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#630]
### Is your content request related to a problem you've encountered during your research process? Please describe.

`vroom` seems about as fast as `data.table`'s `fread` and is my preferred method to load large tabular data. 

Would be good to have a short building block that uses it and compares

### Would you like this to be a Building Block or a Tutorial?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
Let's add it here: https://tilburgsciencehub.com/import/large-datsets/?utm_campaign=referral-short

@Fernando-Iscar - please assign RA where you see fit. Thanks.

**Comment by Fernando-Iscar** [comment]
Hi @MatthijstenTije! Could you extend the scope of your BB with `vroom` functionalities?

**Comment by MatthijstenTije** [comment]
Hi @Fernando-Iscar, i will update the BB with the `vroom` functionalities.
