### ISSUE TITLE
[Development Call]: `requirements.txt` and the like for Python

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#633]
### Is your content request related to a problem you've encountered during your research process? Please describe.

Building block on what they are and how to use them, particularly with virtual environments. See #632 

### Would you like this to be a Building Block or a Tutorial?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
We got it here. https://tilburgsciencehub.com/configure/virtual/environments/?utm_campaign=referral-short

Let's close.
