### ISSUE TITLE
Improve "related posts"

### ISSUE THREAD

**Issue by shrabasteebanerjee** [tilburgsciencehub/website#635]
__DELIVERABLE__

- Based on the [Hugo documentation](https://gohugo.io/content-management/related/#configure-related-content), come up with a bullet-point list of improvements we may want to make on the default recommendations.

- Try opening a development branch in which you experiment with making such changes to the configuration and viewing the results in your browser using localhost (so, not a live website). Try to tweak these parameters to enhance the experience. Do you see something completely irrelevant? Try tweaking so these things get eliminated.

- Assess what other ways there may be to enhance recommendations.

- Conclude with an assessment on whether it is enough to use Hugo's internal rec' engine or whether we should invest in trying alternative recommendations.

**Comment by hannesdatta** [comment]
A few considerations:

- we could do a quick check and how many people actually click on these related post before investing a lot of time.
- we are currently using the default way of Hugo to display related items. We may want to check what algorithm this really is.
– I know that we can override this default algorithm. So, why don't we commission a thesis project that tries to use our meta data to come up with a recommendation engine? We could hardcode this information in a Jason file, and make that the default way through which pages are recommended.

I just saw this issue, so sorry about common thing. Happy to hear your thoughts.

**Comment by shrabasteebanerjee** [comment]
I think the related posts widget could promote more engagement and discovery if it works well, so perhaps we can try a simple updated algo and see if it's leading to better metrics relative to baseline? 

I like the thesis idea, but i'm not sure how smooth the integration process would be - something to ask our developer?

We can also have an RA work on this if they have interest in recommenders!

**Comment by shrabasteebanerjee** [comment]
(even if we don't go as far as a recommender engine, might be worth re-evaluating what tags to put in individual posts to make it easier for hugo to show relevant stuff)

**Comment by hannesdatta** [comment]
__Draft for deliverables:__

- Based on the [Hugo documentation](https://gohugo.io/content-management/related/#configure-related-content), come up with a bullet-point list of improvements we may want to make on the default recommendations.
- Try opening a development branch in which you experiment with making such changes to the configuration and viewing the results in your browser using `localhost` (so, not a live website).
- Assess what *other* ways there may be to enhance recommendations.

Conclude with an assessment on whether it is enough to use Hugo's internal rec' engine, or whether we should invest in trying alternative recommendations.

@shrabasteebanerjee  - please review this and modify where needed. We can then assign it to e.g., @thierrylahaije.

**Comment by hannesdatta** [comment]
@shrabasteebanerjee do I need to assign this to the to do already? Or do we wait for @lachlandeer to 'schedule' this? Not sure.

**Comment by shrabasteebanerjee** [comment]
I believe you can work on it already if you have bandwidth, since it will still be a few weeks till the new RAs are onboarded and we move to the content sprint!

**Comment by hannesdatta** [comment]
> **Draft for deliverables:**
> 
>     * Based on the [Hugo documentation](https://gohugo.io/content-management/related/#configure-related-content), come up with a bullet-point list of improvements we may want to make on the default recommendations.
> 
>     * Try opening a development branch in which you experiment with making such changes to the configuration and viewing the results in your browser using `localhost` (so, not a live website). Try to tweak these parameters to enhance the experience. Do you see something completely irrelevant? Try tweaking so these things get eliminated.
> 
>     * Assess what _other_ ways there may be to enhance recommendations.
> 
> 
> Conclude with an assessment on whether it is enough to use Hugo's internal rec' engine or whether we should invest in trying alternative recommendations.
> 
> @shrabasteebanerjee - please review this and modify where needed. We can then assign it to e.g., @thierrylahaije.

@thierrylahaije - let's add this to your sprint.

**Comment by hannesdatta** [comment]
We can rework this when we switch to Flask.
