### ISSUE TITLE
[Edit]: Research Cloud page - include section on "setting up a new workspace and configuring git"

### ISSUE THREAD

**Issue by shrabasteebanerjee** [tilburgsciencehub/website#636]
### Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)?

Main article here, improve/add as needed: https://tilburgsciencehub.com/building-blocks/configure-your-computer/infrastructure-choice/getting-started-research-cloud/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srosh2000** [comment]
+ tip on addressing disk space warnings

**Comment by shrabasteebanerjee** [comment]
updated!
