### ISSUE TITLE
[Bug]: Tour layout

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#637]
### Contact Details

h.datta@tilburguniversity.edu

### What happened?

I was just checking out our tour and noticed it doesn't render properly on my screen:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/16557730/218964970-0fdf41d2-bf5f-4c11-998f-fc87733beadc.png">

Further, I noticed that we link to the "old" tour on a mobile device, and the new tour on desktop. Is this intended?

### To reproduce

Open our site and click on tour - try with different browser widths.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
web worked OK for me today. Mobile is a very different experience (and don't know what the primary one is). 

We should investigate further. Adding to the WebDesign Sprint, to potentially package with some other tasks for a developer down the line

**Comment by hannesdatta** [comment]
Looks good now.
