### ISSUE TITLE
Organise small RA led workshops/tutorials for community on specific topics (e.g cloud computing, SEO)

### ISSUE THREAD

**Issue by shrabasteebanerjee** [tilburgsciencehub/website#642]

**Comment by lachlandeer** [comment]
I'm thinking of potentially using the "introduction of TSH workshops" to increase the awareness and uptake of TSH materials by students and (more importantly ?) researchers as part of my e-Science Fellowship application this year. This would give us some additional budget and potentially also raise awareness of our platform (post-summer cleanup) to folks in other universities in NL.

Would we be OK with this? @hannesdatta @kleintob @shrabasteebanerjee

**Comment by shrabasteebanerjee** [comment]
I agree, great idea l!

**Comment by kleintob** [comment]
Sure!

From: Shrabastee Banerjee ***@***.***>
Reply to: tilburgsciencehub/website ***@***.***>
Date: Thursday, 9 March 2023 at 07:46
To: tilburgsciencehub/website ***@***.***>
Cc: Tobias Klein ***@***.***>, Mention ***@***.***>
Subject: Re: [tilburgsciencehub/website] Organise small RA led workshops/tutorials for community on specific topics (e.g cloud computing, SEO) (Issue #642)

I agree, great idea l!

**Comment by hannesdatta** [comment]
We run onboarding workshops for RAs. We can close this.
