### ISSUE TITLE
[Q]: Tutorial on Airbnb

### ISSUE THREAD

**Issue by paulina-ambroziak** [tilburgsciencehub/website#650]
### Contact Details

97ambro@gmail.com

### Shoot!

I've noticed that on the TSH website, there is the tutorial "Inside AirBnB - Workflow Walkthrough", which is saved as a draft (see: website\content\tutorials\more-tutorials\airbnb-workflow).

@lachlandeer I was wondering if it is supposed to be unpublished or if it's just an omission. 

I found issue #94, which relates to this tutorial.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
Good question -- let's chat about this live next time we talk so we can navigate thru together? Then we can document what we learn here and decide what to do

**Comment by MKT-Analytics** [comment]
@hannesdatta Do you know why this tutorial is not available on the TSH website? Was it removed for any specific reason, or is it an oversight that should be corrected? Except for the conclusions, it appears to be complete.

Attaching the screenshots of the tutorial:
![localhost_1313_tutorials_more-tutorials_airbnb-workflow_exporting_data_](https://user-images.githubusercontent.com/62939823/229375214-b02489f3-51ab-46f9-aeac-a3a50e5b8e35.png)
![localhost_1313_tutorials_more-tutorials_airbnb-workflow_transforming_data_](https://user-images.githubusercontent.com/62939823/229375217-53a4fe38-cbf7-4dd4-b3f3-8ce6621e9986.png)
![localhost_1313_tutorials_more-tutorials_airbnb-workflow_loading_data_](https://user-images.githubusercontent.com/62939823/229375220-88ebd06e-c498-42d4-85c2-00f860d0acc0.png)
![localhost_1313_tutorials_more-tutorials_airbnb-workflow_airbnb-workflow-overview_](https://user-images.githubusercontent.com/62939823/229375223-09873c72-bcf5-412f-b411-7faf4f895195.png)
![localhost_1313_tutorials_more-tutorials_airbnb-workflow_conclusion_](https://user-images.githubusercontent.com/62939823/229375225-629c7251-f2fc-4165-b16c-944e780923b3.png)
![localhost_1313_tutorials_more-tutorials_airbnb-workflow_automating_workflows_](https://user-images.githubusercontent.com/62939823/229375226-6e4bc935-f40e-48d6-a7c0-123ed310aeab.png)

**Comment by lachlandeer** [comment]
closed by #717
