### ISSUE TITLE
Suggest change to: building-blocks/collect-data/webscraping-apis/scrape-dynamic-websites.md

### ISSUE THREAD

**Issue by srosh2000** [tilburgsciencehub/website#655]
### Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)?

Need to add tip regarding installation of selenium and webdriver. Make sure to check the python version they are installed to. 

### Describe the solution you'd like

Safe bet is to activate an environment via anaconda navigator and run the installation commands on the anaconda prompt to make sure the packages are installed in the same python version/directory. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
Not an issue anymore - most students run Python 3 now.
