### ISSUE TITLE
Suggest change to: building-blocks/configure-your-computer/statistics-and-computation/text-editor.md

### ISSUE THREAD

**Issue by alexandervossen** [tilburgsciencehub/website#656]
### Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)?

Atom has been sunsetted https://github.blog/2022-06-08-sunsetting-atom/. Maybe we can come up with a new recommendation? I also have a personal interest in this since I have not found a good replacement yet – tried VSCode but I am not 100% happy. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
I'd suggest also recommending VSCode. 

We could also check out what's happening with Sublime? I know a few folks that a huge fans of that.

Perhaps we also move away from one text editor and suggest a couple of different ones? A page each for set up, and packages that we like on each, and then a comparison page?

thoughts @alexandervossen

**Comment by alexandervossen** [comment]
Sounds good! @lachlandeer.

**Comment by lachlandeer** [comment]
To Do:

- [ ] Change Atom spiel to VS code 
- [ ] Write a building block about Sublime Text
- [ ] Write a building block about Emacs and/or Vim (for the so inclined user) 
- [ ] Write a building block comparing text editors
