### ISSUE TITLE
Learn/refresh GitHub & Git concepts with these Datacamp courses

### ISSUE THREAD

**Issue by Fernando-Iscar** [tilburgsciencehub/website#657]
# Goal of this issue

Inform about the availability of short introductory Datacamp courses on Git and GitHub, which could be especially useful for new RAs or others interested to learn or refresh their knowledge of these tools.

The courses take about 2-3 hours each to complete.

# Resources

The Datacamp courses on Git and GitHub can be found on the Datacamp website: 

- Git: https://www.datacamp.com/courses/introduction-to-git
- Git for Data Scientists: https://www.datacamp.com/courses/introduction-to-git-for-data-science
- GitHub Concepts: https://www.datacamp.com/courses/github-concepts

These courses are provided with practical examples and exercises to reinforce learning.

# Deliverables

No deliverables

**Comment by hannesdatta** [comment]
- [ ] Add these resources to the onboarding guide, please. We have a section on getting started.
- [ ] Also add a note we can get RAs premium datacamp when they request it via me, also somewhere on the onboarding guide
- [ ] find a suitable place on Tilburg science hub and add these links to the respective source code files (md)

**Comment by lachlandeer** [comment]
Closed with #664
