### ISSUE TITLE
Suggest change to: tutorials/more-tutorials/chatgpt-article/chat-gpt-research.md

### ISSUE THREAD

**Issue by shrabasteebanerjee** [tilburgsciencehub/website#658]
### Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)?

Add this as another resource, or include some examples from it?

https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4356243

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
Like the idea. Let's get an RA to do a wider search to post some suggestions here that we can then integrate?
