### ISSUE TITLE
Start bundling AI resources: tilburg.ai

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#663]
__Background:__

Our university is currently in the process of collecting documents on the use of AI by students and researchers. These documents live only in email boxes, and - at best - somewhere on the internet.

I have recently bought `tilburg.ai`, which could become a place for hosting these "live" documents. Ideally, we host a light-weight page to gather content. In the long-term, we could integrate these to our site. But for now, let's have a separate page and contribute to it actively.

__Deliverable:__
- A repository in the Tilburg Science Hub organization, with a website that either runs in Hugo or Quarto.
- Get inspired
  - Quarto: https://quarto.org/docs/gallery/#websites. I like https://course.fast.ai/. Try adapting the colors a bit (e.g., background color, etc.) to make it match the Tilburg style a bit.
  - Alternative: just use https://odcm.hannesdatta.com as a template.
- Make a suggestion which structure to go with and launch initial version in a new repository.
- Initialize with this content: https://tiu.nu/aiready. I can email more content later.
- Important: IT DOES NOT need to be perfect. Consider it as a living document.

**Comment by hannesdatta** [comment]
Assigning @fleurlemire for content, etc.., and maybe @NielsRahder for tech (but you guys figure out whether you need more people to be involved, e.g. @thierrylahaije, @MKT-Analytics).

**Comment by hannesdatta** [comment]
Some other thoughts:

We could also invison a blend of "a tip of the day" (https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/) with a collection of resources. 

Maybe you come up with something creative and cool here.

Remember the goal: inspiring people about the use of AI in education and teaching. How? That's your turn :)

**Comment by hannesdatta** [comment]
- @fleurlemire comes up with an initial quarto site structure and a "demo" repository
- important point here is: get content we already have on that site.
- we can ask @thierrylahaije later to add some CSS flavor (e.g., colors to match tilburg science hub, etc.)

**Comment by Fernando-Iscar** [comment]
@hannesdatta Sure! I'd be happy to also contribute to this! I already talked to @fleurlemire to arrange it.

**Comment by hannesdatta** [comment]
Now a dedicated project: tilburg.ai. Closing the issue.
