### ISSUE TITLE
[Bug]: Running error for newer Hugo versions

### ISSUE THREAD

**Issue by ana-bianca-luca** [tilburgsciencehub/website#667]
### Contact Details

a.b.luca@tilburguniversity.edu

### What happened?

When running hugo v0.111.3 in local repository, it throws an error for these two files: building-block-shell.md, tutorial-shell.md.
For older versions, this is not the case. 

![image](https://user-images.githubusercontent.com/60931541/227986086-0ac05aa3-221d-40a5-9148-9eeb98a4d5c9.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
closed with #668
