### ISSUE TITLE
[Q]: Naming convention for branches - a consistent way forward for the TSH website?

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#669]
### Shoot!

I want to move TSH towards the following convention when we branch: 

for building blocks:

```
buildingblock/NAME
```

For tutorials:

```
tutorial/NAME
```

For webdesign, the standard `feature`

```
feat/NAME   OR feat/NAME
```

where NAME is a short name of the task one works on

thoughts @hannesdatta @shrabasteebanerjee @kleintob 

PS : I don't like th issue number branching: 

```
XXX-very-long-name-of-issue
```

as its not that easy to manage. One can refer to the issue the they are working on in a PR, such as #665

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kleintob** [comment]
Just to understand, what do you mean by the “/”
A related question: do we have an opinion on camelCase? With it, we can also go beyond one word if it is helpful (while aiming for one).

From: Lachlan Deer ***@***.***>
Reply to: tilburgsciencehub/website ***@***.***>
Date: Monday, 3 April 2023 at 12:07
To: tilburgsciencehub/website ***@***.***>
Cc: Tobias Klein ***@***.***>, Assign ***@***.***>
Subject: [tilburgsciencehub/website] [Q]: Naming convention for branches - a consistent way forward? (Issue #669)

Contact Details

No response

Shoot!

I want to move TSH towards the following convention when we branch:

for building blocks:

buildingblock/NAME

For tutorials:

tutorial/NAME

For webdesign, the standard feature

feat/NAME   OR feat/NAME

where NAME is a short name of the task one works on

thoughts @hannesdatta<https://github.com/hannesdatta> @shrabasteebanerjee<https://github.com/shrabasteebanerjee> @kleintob<https://github.com/kleintob>

PS : I don't like th issue number branching:

XXX-very-long-name-of-issue

as its not that easy to manage. One can refer to the issue the they are working on in a PR, such as #665<https://github.com/tilburgsciencehub/website/issues/665>

Code of Conduct

  *   I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
The `/` acts as a separator in branch names. 

For example suppose I have a bunch of branches. I would rather have them listed as 

```
buildingblock/diff-in-diff
buildingblock/rdd
buildingblock/marginal-effects
feat/new-front-page-design
feat/new-recommender
tutorial/the-complete-guide-to-webscraping
```

Than (how its been for far)

```
diff-in-diff
dd
marginal-effects
new-front-page-design
new-recommender
the-complete-guide-to-webscraping
```

Or even (issue referenced naming)

```
652-diff-in-diff-new-methods-for-2022
777-rdd-using-rd-robust
666-how-do-i-compute-marginal-effects
454-new-front-page-design-with-clicky-things
333-recommender-engine-update-suggestion
555-building-a-webscraping-guide
```

The first of these is much easier to read and navigate

There's nothing to really change, except encouraging people to use the system we prefer

**Comment by kleintob** [comment]
I wasn’t aware of this—thanks!
Tobi


From: Lachlan Deer ***@***.***>
Reply to: tilburgsciencehub/website ***@***.***>
Date: Monday, 10 April 2023 at 19:40
To: tilburgsciencehub/website ***@***.***>
Cc: Tobias Klein ***@***.***>, Mention ***@***.***>
Subject: Re: [tilburgsciencehub/website] [Q]: Naming convention for branches - a consistent way forward for the TSH website? (Issue #669)


The / acts as a separator in branch names.

For example suppose I have a bunch of branches. I would rather have them listed as

buildingblock/diff-in-diff

buildingblock/rdd

buildingblock/marginal-effects

feat/new-front-page-design

feat/new-recommender

tutorial/the-complete-guide-to-webscraping

Than (how its been for far)

diff-in-diff

dd

marginal-effects

new-front-page-design

new-recommender

the-complete-guide-to-webscraping

Or even (issue referenced naming)

652-diff-in-diff-new-methods-for-2022

777-rdd-using-rd-robust

666-how-do-i-compute-marginal-effects

454-new-front-page-design-with-clicky-things

333-recommender-engine-update-suggestion

555-building-a-webscraping-guide

The first of these is much easier to read and navigate

There's nothing to really change, except encouraging people to use the system we prefer

**Comment by lachlandeer** [comment]
Everyone seems to have switched to this for now. Its soooo much easier to navigate. Closing
