### ISSUE TITLE
[Edit]: Onboaring guide

### ISSUE THREAD

**Issue by paulina-ambroziak** [tilburgsciencehub/website#670]
### Check the onboarding guide to make sure it's easy to understand and follow.

Notes after speaking to Valerie:

- .md format is not an issue
- the main issue was to find the template for writing the building blocks or tutorials (we have them [here](https://tilburgsciencehub.com/tutorials/more-tutorials/contribute-to-tilburg-science-hub/pullrequests/) but it is not easy to find)
- problems with the text formatting (e.g. how to highlight text as a summary, example, warning or tip) were due to difficulties with finding the template
- it is not clear how to fill in e.g. aliases
- lack of instruction on how to preview the website locally (with hugo server)
- not clear process of opening a pull request on GitHub
- Solution: update Onboarding Guide with a step-by-step guide explaining everything from creating a building block/tutorial from a template (including templates that can be downloaded in the .md format) to building the site locally to creating a pull request.

**Comment by lachlandeer** [comment]
see also some discussion in #647

**Comment by paulina-ambroziak** [comment]
A partial solution to issue #675.

**Goal:** Update the Onboarding Guide with a step-by-step guide explaining everything from creating a building block/tutorial from a template (including templates that can be downloaded in the .md format) to building the site locally to creating a pull request.

_______________________________

Hi @valerievossen,
I've created a step-by-step tutorial on how to make a contribution to the TSH website as a Research Assistant. You can find it in the [Onboarding Guide](https://github.com/tilburgsciencehub/onboarding/wiki) ('Contributing to the TSH website' in the menu on the right side). I divided the guide into four parts:
- [Content Creation](https://github.com/tilburgsciencehub/onboarding/wiki/Content-Creation)
- [Website's Repository](https://github.com/tilburgsciencehub/onboarding/wiki/Website's-Repository)
- [Preview the Website](https://github.com/tilburgsciencehub/onboarding/wiki/Preview-the-Website)
- [Publish the Changes](https://github.com/tilburgsciencehub/onboarding/wiki/Publish-the-Changes)


Could you please review it and see if it's logical, easy to follow, covers all the necessary details, and solves the problems that you've encountered yourself? Feel free to make any changes.

@StefKirsch, you also might be interested to see it.

+ tagging @lachlandeer in case you want to review it as well.

**Comment by valerievossen** [comment]
Hey @paulina-ambroziak, 
Looks good! I reviewed the whole onboarding guide and made some small changes. When new RA's are onboarding, I can still make any additional changes if they come across anything confusing, but I think it should be all clear like this!

**Comment by StefKirsch** [comment]
Hi @paulina-ambroziak,

looking good! I wish I had that guide available last time (even though it was very gezellig to have you me go through the steps in person 😁)

One remark regarding the flow: Is is possible to link the sub pages of "Contributing to the TSH website" right from the [Onboarding Guide](https://github.com/tilburgsciencehub/onboarding/wiki)? And then have a button per sub-site to go to the next one? It is perfectly useable and understandable as it is, but this would make it easier to go through all the steps!

**Comment by hannesdatta** [comment]
We can close this one.
