### ISSUE TITLE
[Development Call]: Tutorial on setting up Virtual Machine

### ISSUE THREAD

**Issue by paulina-ambroziak** [tilburgsciencehub/website#676]
### Is your content request related to a problem you've encountered during your research process? Please describe.

@alexandervossen Could you provide an overview of the content that will be included in the tutorial (maybe just by bullet points) and tag me in relevant parts that I can help you with?
From there on, we can start creating the tutorial together. We can collaborate on a separate branch.

**Comment by hannesdatta** [comment]
@alexandervossen - anything to be done here?

**Comment by alexandervossen** [comment]
I think that became a bit redundant so I think thieving can be closed
