### ISSUE TITLE
Add setting up Hugo to onboarding guide

### ISSUE THREAD

**Issue by valerievossen** [tilburgsciencehub/website#689]
Setting up Hugo would be a useful thing to include in the onboarding guide. 
As well, how to solve possible issues you run into when setting it up (especially for Windows)

**Comment by valerievossen** [comment]
@srosh2000 @gmullin-tiu maybe you want to add something to the description of this issue ?

**Comment by srosh2000** [comment]
@valerievossen Thanks for making the issue. Gaston and I just discussed and looks like we faced the same issue and resolved it the same way so I'll update the building block for hugo installation and onboarding guide accordingly. Thanks for bringing it up!
