### ISSUE TITLE
[Development Call]: Regression discontinuity - sharp RDD

### ISSUE THREAD

**Issue by ana-bianca-luca** [tilburgsciencehub/website#691]
### Is your content request related to a problem you've encountered during your research process? Please describe.

Foundations of the sharp regression discontinuity design
- practical example
- local nature of RD effects

Material: Cattaneo, Idrobo & Titiunik (2020) - [A Practical Introduction to Regression Discontinuity Designs: Foundations](https://arxiv.org/abs/1911.09511)

### Additional context

First buildingblock of the Regression Discontinuity topic

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
close by #695
