### ISSUE TITLE
Suggest change to: tutorials/more-tutorials/chatgpt-article/chat-gpt-research.md

### ISSUE THREAD

**Issue by vikash-nepal** [tilburgsciencehub/website#692]
### Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)?

In this research work for the very first-time synchro-reassigning transform (SRT) technique is employed for the classification of various PQ disturbances event. Through rigorous numerical analysis, it is established that SRT is superior to STFT, WT, SST, and even SET. Irrespective of PQ disturbance events and SNR conditions. Particularly, when harmonics and interharmonics are present in the power signal, the difference between SET and rest of the TF methods asre much more pronounced. 

The paper is organized in the following manner, section 2 deals with various TF techniques used in this paper. Section 3 provides the explanation of math behind Renyi entropy and its importance to quantify the effectiveness of TF techniques. All the results analysis is carried out in section 4. The conclusion is drawn in section 5.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
Hi

I can't see how the text you detail is relevant for the site. 

Closing for now
