### ISSUE TITLE
[Feature]:  Guidance page on TexMacs [https://www.texmacs.org/]

### ISSUE THREAD

**Issue by fleurlemire** [tilburgsciencehub/website#696]
### Is your feature request related to a problem? Please describe.

TexMacs has been found to be a non-fussy editor

### Describe the solution you'd like

Adding guidance on TexMacs [https://www.texmacs.org/], a powerful scientific editing software, can be useful in several scenarios: Learning TexMacs, Document Formatting, Collaboration, Publishing and Presentations and Mathematical Writing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fleurlemire** [comment]
Hey @lachlandeer 
I agree with you, but this is all the information I got:
_- Could you consider adding a guidance page for TexMacs [https://www.texmacs.org/]? Although I now use Microsoft Word, there was a time when I tried to use Lyx, and then moved to TexMacs. I found TexMacs to be a non-fussy editor._

**Comment by lachlandeer** [comment]
okkk .. so perhaps a something in a "configure your computer" section discussing some latex editor alternatives?

@ana-bianca-luca -- would you be interested in tackling this?

**Comment by ana-bianca-luca** [comment]
@lachlandeer sure, I can take this
