### ISSUE TITLE
[Feature]: Guidance page for OpenAI Whisper

### ISSUE THREAD

**Issue by fleurlemire** [tilburgsciencehub/website#697]
### Is your feature request related to a problem? Please describe.

Transcription is a time consuming affair, and if outsourced, it can be expensive. The cost of transcription when using Whisper can be zero, and the output can be surprisingly decent.

### Describe the solution you'd like

Creating and adding a guide page for OpenAI Whisper can help to understand and get started with OpenAI Whisper.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
closed with #715
