### ISSUE TITLE
[Edit]: Adding R code next to Docker to examples/keywords-finder.md

### ISSUE THREAD

**Issue by fleurlemire** [tilburgsciencehub/website#698]
### Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)?

Some people are not able to move beyond the Docker installation phase. By adding R code, we can still make this useful without needing to install Docker first.

### Describe the solution you'd like

Adding code for R, to make this work, without the use of Docker

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
Let's retire this issue.
