### ISSUE TITLE
[Feature]: Update FE building block about assumptions

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#700]
### Contact Details

h.datta@tilburguniversity.edu

### Would you like this to be a Building Block or a Tutorial?

Thesis students wonder how to verify the "normal" assumptions known in OLS models (homogeneity of residuals, multicollinearity etc.) in a fixed effects model.

It would be great to state so in our existing fixest building blocks.

Here is a good starter: https://www.econometrics-with-r.org/10-5-tferaaseffer.html

 

### Describe the solution you'd like

An update to https://tilburgsciencehub.com/fixest/?utm_campaign=referral-short, involving details on checking assumptions (with code snippets).

Goal is to direct thesis students to this building block so they can correctly apply fixest.

### Suggested title

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
Sounds reasonable.

I'd suggest having that as a new page, so as we flesh out causal inference stuff we have a couple of fixed effects building blocks ... 

Something like: 

- Intro to Panel Data (optional, but contrasts to the "familiar" OLS case)
    - Discusses ways forward: pooled OLS, Between, Within (FE) and Random Effects - then links to building block on each
- Then on the fixed effects page, we outline the basics and the assumptions one needs in contrast to a pooled OLS estimator
    - We then link to the fixest page for how to "do" fixed effects regression   

thoughts @hannesdatta?

**Comment by shrabasteebanerjee** [comment]
+1 to this request, and also lachlan's idea - perhaps @srosh2000 can work on this?

**Comment by lachlandeer** [comment]
i put @valerievossen on it for now as she has some free time.

We've agreed to flesh out the following:

- [ ] Panel Data basics (set up, notation, bias)
- [ ] Assumptions in these models (the "4 standard ones" + the difference stances on error term correlation over time)
- [ ] Each of the standard estimators (pooled OLS, between, within, FE) linking back to the assumptions above + a common example implementing them

**Comment by lachlandeer** [comment]
Some interesting stuff on panel data more broadly here: https://rpubs.com/phle/r_tutorial_panel_data_analysis

Not saying we should use it ... more leaving it here to mull over for a later date
