### ISSUE TITLE
[Development Call]: Regression discontinuity - plots

### ISSUE THREAD

**Issue by ana-bianca-luca** [tilburgsciencehub/website#702]
### Is your content request related to a problem you've encountered during your research process? Please describe.

RD plots (coding):
- choosing the bins (location, number)

Material: Cattaneo, Idrobo & Titiunik (2020) - [A Practical Introduction to Regression Discontinuity Designs: Foundations](https://arxiv.org/abs/1911.09511)

### Additional context

Second buildingblock of the Regression Discontinuity topic

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
close with #703
