### ISSUE TITLE
[Development Call]: Doing calculations with coefficients from regression analysis (Delta Method)

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#706]
### Contact Details

h.datta@tilburguniversity.edu

### Is your content request related to a problem you've encountered during your research process? Please describe.

I'm always frustrated when researchers/students do calculations with coefficients that come out of a (linear) regression model, but forget to include standard errors.

The purpose of this building block is to teach how to use the "DeltaMethod" function from the car package to do calculations with coefficients (linear combinations).

Steps:
1. Explain purpose (say, you have estimated effect of A on Z and B on Z, now you would like to compute the combined effect of A and B on Z).
2. Delta method as a solution: how does it work
3. Practical application with (a) estimating a regression model with some exemplary data, and computing combinations of coefficients using the delta method.

Example code follows:

```
library(datasets)
data(mtcars)

m<-lm(mpg~.,data=mtcars)

summary(m)

# compute standard errors of joint effects
library(car)

deltaMethod(m, 'cyl+hp')
deltaMethod(m, '2*cyl-3*hp')
deltaMethod(m, '(Intercept)+gear')
```

__The code would have to be adjusted to an example that actually makes sense__.

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Suggested title

Using the delta method to "calculate" with estimated coefficients from regression models

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
Closed by #714
