### ISSUE TITLE
[Development Call]: Regression discontinuity - continuity based approach

### ISSUE THREAD

**Issue by ana-bianca-luca** [tilburgsciencehub/website#708]
### Is your content request related to a problem you've encountered during your research process? Please describe.

- Local polynomial point estimation: choosing kernel function K, bandwidth h, polynomial order p
- Optimal point estimation (in practice)
- Local polynomial inference (conventional inference and undersmoothing, standard bias correction, robust bias correction): using different bandwidths + in practice

Material: Cattaneo, Idrobo & Titiunik (2020) - [A Practical Introduction to Regression Discontinuity Designs: Foundations](https://arxiv.org/abs/1911.09511)

### Additional context

Third buildingblock of the Regression Discontinuity topic

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
Close with #711
