### ISSUE TITLE
Update contribution

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#718]
Hi @fleurlemire -

can you please update the picture (other contributors, more international, bigger team) and stats: 8k visitors this months. Not 4000.

![image](https://github.com/tilburgsciencehub/website/assets/16557730/b7c94288-4a27-4f58-982b-bf07b40932cd)

Thanks!

**Comment by fleurlemire** [comment]
@hannesdatta , do you want like all contributors/the whole team (like then there is still a lot dutch with some new people) or just some of them? I already talked with Thierry about it and he will help. I already collected some information, so i will finish that when you answer this question and get it live then!

**Comment by hannesdatta** [comment]
Just make it a diverse selection. No need to show everyone. Thanks!

**Comment by lachlandeer** [comment]
completed in #728
