### ISSUE TITLE
[Development Call]: Regression discontinuity - fuzzy RDD

### ISSUE THREAD

**Issue by ana-bianca-luca** [tilburgsciencehub/website#719]
### Is your content request related to a problem you've encountered during your research process? Please describe.

Foundations of the fuzzy regression discontinuity design
- introduction/general information
- assigned treatment vs. received treatment
- fuzzy vs. sharp RDD
- estimation and inference methods: intention to treat effects, treatment effects for subpopulations, bandwidth and window selection

Material: Cattaneo, Idrobo & Titiunik (2023) - [A Practical Introduction to Regression Discontinuity Designs: Extensions](https://rdpackages.github.io/references/Cattaneo-Idrobo-Titiunik_2023_CUP.pdf)

### Additional context

Fourth buildingblock of the Regression Discontinuity topic

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
closed with #720
