### ISSUE TITLE
[Bug]: Site doesn't build on recent Hugo version

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#723]
### Contact Details

h.datta@tilburguniversity.edu

### What happened?

I cloned the site today on a windows laptop w/ Anaconda and Hugo's latest version - and Hugo throws me these errors when building the site.

```
(base) >hugo serve
Start building sites …
hugo v0.114.1-e9b716ad9869b79e7c374bbdae4daf5ee6406bd4+extended windows/amd64 BuildDate=2023-06-23T11:02:58Z VendorInfo=gohugoio

Built in 11888 ms
Error: error building site: "\website\content\building-blocks\develop-your-research-skills\tips\stata-code-style.md:17:4": failed to parse Markdown attributes; you may need to quote the values
```

Is this something anyone can reproduce? Is our site not compatible with the most recent Hugo or is this a thing that has to do w/ my installation?

DELIVERABLE: 
- build site on most recent version of hugo and see whether it runs through. if not, fix underlying issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
@NielsRahder? @thierrylahaije? @fleurlemire?

Let me know how can check this and assign yourself. Thanks.

**Comment by thierrylahaije** [comment]
@hannesdatta @fleurlemire I will check this out. If I find out there are any errors, I will look into it, report the big and fix the error.

**Comment by StefKirsch** [comment]
I got the exact same error! The problem is caused by the syntax used in the building block "Stata Coding Style Guidelines". I already submitted the problem and a possible solution as issue #730 😊

**Comment by hannesdatta** [comment]
Done and submitted PR!
