### ISSUE TITLE
[Development Call]: Regression discontinuity - local randomization approach

### ISSUE THREAD

**Issue by ana-bianca-luca** [tilburgsciencehub/website#731]
### Is your content request related to a problem you've encountered during your research process? Please describe.

Local randomization approach of RDD: 
- introductory theory
- estimation and inference (Fisherian, Neyman, Super-population)
- practical example

Material: Cattaneo, Idrobo & Titiunik (2023) - [A Practical Introduction to Regression Discontinuity Designs: Extensions](https://rdpackages.github.io/references/Cattaneo-Idrobo-Titiunik_2023_CUP.pdf)

### Additional context

Sixth buildingblock of the Regression Discontinuity topic

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
close with #732
