### ISSUE TITLE
[Development Call]: Regression discontinuity - validation and falsification analysis

### ISSUE THREAD

**Issue by ana-bianca-luca** [tilburgsciencehub/website#733]
### Is your content request related to a problem you've encountered during your research process? Please describe.

Validation and falsification analysis methods for the RD designs:
- Predetermined Covariates and Placebo Outcomes
- Density of Running Variable
- Placebo Cutoffs
- Sensitivity of Observations around the Cutoff
- Sensitivity to Bandwidth Choice
- Sensitivity to Window Choice

Material: Cattaneo, Idrobo & Titiunik (2023) - [A Practical Introduction to Regression Discontinuity Designs: Extensions](https://rdpackages.github.io/references/Cattaneo-Idrobo-Titiunik_2023_CUP.pdf)
Cattaneo, Idrobo & Titiunik (2020) - [A Practical Introduction to Regression Discontinuity Designs: Foundations](https://arxiv.org/abs/1911.09511)

### Additional context

Seventh buildingblock of the Regression Discontinuity topic

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
closes with #734
