### ISSUE TITLE
[Development Call]: Visualize your data - theory and best practices

### ISSUE THREAD

**Issue by ana-bianca-luca** [tilburgsciencehub/website#735]
### Is your content request related to a problem you've encountered during your research process? Please describe.

New section for data visualization: "Visualize your data"
First bb of the section to introduce data visualization theory (data encoding, chart elements, chart types) and best practices for visualization.

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
We got it on the site. Thanks!
