### ISSUE TITLE
info for outgoing RAs - letter of recommendation

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#749]
__Background__

I was recently approached me for a letter of recommendation. I think it may be worthwhile to add to our onboarding guide (maybe notes for deboarding) that students can approach any TSH faculty member for a recommendation letter when exiting.

__Deliverable__
- Add to our onboarding guide
- Yneed to find a good place for this on the guide. 
- It should be some kind of incentive to work for us (maybe also add to our job posting?), but also a piece of reward for hard-working students.

On that page, please tell 
- students that want this that they need to give us basic information (say, whether the took any courses with us, which grades they obtained, when they took the courses), and 
- mention anything worthwhile of their time with TSH (e.g., what they are most proud of to achieve, etc.).

We will then add some of our own thoughts to the letter.

Thanks!

**Comment by fleurlemire** [comment]
Hi @hannesdatta.

I made a proposal for a text and the place where we can put it in the onboarding guide. You can see my proposal at: https://docs.google.com/document/d/19gLFzTmnK9nqlW5b8XPaRI3IMSoQR_Ge4GpcYL5RLB4/edit?usp=sharing

Would you like to share your feedback with me? I will add it to the onboarding guide whenever you agree

**Comment by fleurlemire** [comment]
Hi Hannes, It has been added to the onboarding guide, see: https://github.com/tilburgsciencehub/onboarding/wiki/Notes-for-Deboarding together with a checklist of things that needs to be removed etc. If anything needs to be added, we can do it here. We can also add other deboarding stuff on this page.
