### ISSUE TITLE
Revisions to new landing page

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#763]
- [x] find a good place for adding DOCUMENTATION on how the landing page is being compiled (e.g., onboarding guide, readme, "how to")
- [x] fix duplicate title issue for recently published articles
- [x] set recently published to 3
- [x] fix fly in effect

**Comment by lachlandeer** [comment]
can you also check the display on mobile? When i quickly tried, the ordering of the blocks felt unnnatural when presented linearly. Can chat more about it as needed.

**Comment by thierrylahaije** [comment]
Hi @lachlandeer, could you explain what you mean exactly? Because I checked it in Google Developers on different mobile phone screen sizes and it should be working correctly. We can also plan a meeting if you would like.

**Comment by thierrylahaije** [comment]
@hannesdatta All issues have been fixed. Pull request made.

**Comment by hannesdatta** [comment]
@lachlandeer - I merged this version. Can you confirm the order of the mobile page is now improved? I couldn't spot it from the source code.

**Comment by lachlandeer** [comment]
It's more conceptual.. 

The order the tiles appear doesn't make sense to me when they appear linearly. Is there a way to have different order easily for mobile?

**Comment by thierrylahaije** [comment]
Our landingpage cards use the Bootstrap Framework as a basis for responsiveness. Adjusting the positioning of the blocks on mobile or tablet can be done very easily by adding the order class to a column. 

Each block in the index.html looks something like this:

<div class="col-lg-10 col-xl-8 col-sm-22"

by adding the class "order" + "sm"/"xl"/"lg" (depending of the screen size of choice, mobile would be "sm" (small)) you can choose the position of the column on a screensize. For example, the class "order-sm-1" places a block on position 1 in the row small devices.

More information about the bootstrap column ordering can be found over here:
https://getbootstrap.com/docs/5.0/layout/columns/#reordering

**Comment by hannesdatta** [comment]
@lachlandeer - if you let us know your updated order, Thierry can implement it. Thanks!
