### ISSUE TITLE
Font for tour

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#769]
The font for our tour seems to be off:

<img width="803" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/aec5b90e-78aa-483a-bab9-a331b384e7a3">

In any case, this doesn't resemble our usual font. Can you fix?

**Comment by thierrylahaije** [comment]
I checked this problem, but I could not reproduce it. In my browser, the Tour font is working correctly:

<img width="545" alt="image" src="https://github.com/tilburgsciencehub/website/assets/65568251/086cc973-dccc-4d5a-8d4e-4e0ba611c7e9">

Were you using Chrome or Safari? Safari is known for the fact that it has problems with rendering certain styles and using certain common web building elements, such as difficulties with fonts, webp images, styling properties etcetera.

Couple of question for reproducibility:
- Which browser were you using?
- Were you running Hugo locally or was this on the production website?
- Which device were you using? Laptop or tablet?
- Did you have this issue only with the TSH website or also when using other sites? (with the rest of the variables the same (browser, system, device etcetera))

**Comment by hannesdatta** [comment]
It was Safari. It does work in Firefox/Chrome etc.

Quick fix possible? If not, we can park it.

**Comment by thierrylahaije** [comment]
Great. I found the problem. The css font rule that was being used for the tooltip is not being rendered by Safari correctly. I adjusted this, using a font rule that was already being used in the scss. Now the Tour renders well on each browser without font issues. Update will be pushed tonight.

**Comment by hannesdatta** [comment]
Magic!

Thanks. 🙇
