### ISSUE TITLE
[Feature]: Drop down button "Contribute"

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#775]
### Contact Details

h.datta@tilburguniversity.edu

### Is your feature request related to a problem? Please describe.

The contribute button now points to a tutorial and it's hard to see exactly what are the various ways to contribute.

### Describe the solution you'd like

I want to turn the YELLOW button in our menu into one that has a drop down menu.

![image](https://github.com/tilburgsciencehub/website/assets/16557730/f6c754f7-0e08-4198-a95b-1785e56464cf)

The menu items in this drop down button should be:
- Contribution guide
- Submit a new issue
- View the onboarding guide

...etc.

It will make it easier for people to find the stuff they need.

Make it blend in well with the design of our website. It should look beautiful.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thierrylahaije** [comment]
Feature added and merged. Issue will be closed.
