### ISSUE TITLE
[Bug]: Sub-lists render wrong

### ISSUE THREAD

**Issue by thierrylahaije** [tilburgsciencehub/website#788]
### What happened?

When creating lists containing multiple levels, there is a rendering issue:

<img width="239" alt="image" src="https://github.com/tilburgsciencehub/website/assets/65568251/c58f96d6-3c3f-4d6b-acc2-9b39f8a32e3c">

As visible above, the sub <ul> has a margin on the y-axis, just as the main ul. Sub <ul> tags should not have this margin on the y axis.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
Is this still pending?

**Comment by thierrylahaije** [comment]
Issue moved to #896.
