### ISSUE TITLE
remove legacy tour

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#796]
The TOUR in the header links to the correct tour (the animated one).

The link in the YELLOW BUTTON links to the old tour.

Please strictly start the NEW tour when pushing the yellow button.

![image](https://github.com/tilburgsciencehub/website/assets/16557730/e5787929-a4e4-46ec-a11b-29683274592b)

**Comment by hannesdatta** [comment]
__Next step:__

When clicking here...

<img width="233" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/7a577f2b-6500-4be4-a27f-eefc7ccd65aa">


The page needs to scroll up and start the new tour as well! Thank you.

**Comment by thierrylahaije** [comment]
Fixed in PR #841
