### ISSUE TITLE
Use Google Analytics to improve user retention

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#803]
__Background:__

We haven't really used GA so much to improve the experience on our site. I would now like you to use it to come up with ideas on how to improve user retention on our site! In particular, I'm worried about our high bounce rates and relatively few returning visitors (we have high inflow though, which is good).

__Deliverable:__

- A powerpoint deck with information on the behavior of our users on our site. How do they get in? Who stays? Which content do they look for? What do they search? Anything that can help us understand our users better is good.
- Specific suggestions on how to improve user retention on our site: this can be content (e.g., "more in this or that category") or tech (e.g., a button here or there).

I want you to have this deck to the point, and be able to present it to our Core Team for about 10-15 minutes. No script. Lots of graphs, ideas. Inspire us.

Makes sense?

Thanks!

**Comment by hannesdatta** [comment]
Oh, btw, please make an appointment with me and @thierrylahaije when you can present this to us. Add @lachlandeer @shrabasteebanerjee and @kleintob if they're available (optional but maybe they want to think about this as well).

**Comment by hannesdatta** [comment]
@alexandervossen may be interested as well...

**Comment by NielsRahder** [comment]
I will have a look at it, and plan a date for the presentation when I have more information about when I will be done. 

Perhaps also an idea to add @fleurlemire to this issue for brainstorming and the presentation?
