### ISSUE TITLE
Rotate content on landing page

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#828]
Our cards now always look the same.

Please implement some python code that makes our content change more frequently, say, every hour or so (you can use `cron` to start up at somewhat random times)

What I want is that you have "candidate items" and, for now, a random number generator picks which item to show at a particular time.

Build this extension with the mindset that we will create "segments" to see different versions of the main landing page.

**Comment by thierrylahaije** [comment]
For this issue I have some questions:

Do you want to change:
 - The order of the blocks or which blocks are displayed?
     - If so, how many items do you want as maximum? We currently have 8 cards.
 - The content of separate blocks
     - If so, which separate blocks should be refreshed?

Furthermore you are speaking about "segments". Do you mean a specific combination of cards with a "segment" ?

**Comment by hannesdatta** [comment]
- The order of the blocks does not need to change.
- Within the best practices for naming git brnaches, there should be multiple topics appearing from time to time (say, in one build, it's best practices, in another refresh, it's gonna be another item).
- Same with the slider (row 2, to the left)
- recently published: I don't think this is what actually got recently published. These haven't changed for a month or so. Are we pulling in the right content here?
- Same content rotation with Use ChatGPT for research and learn something new.

We do not need more cards.

Segments: in the future, the content is going to be personalized. But, I don't think you need to do anything with this right now...

**Comment by hannesdatta** [comment]
Implement as discussed:

rotate content of single block among the most popular ones (and fill in the block w/ most popular tutorials with the remaining ones).

You can go ahead making a PR on this.
