### ISSUE TITLE
pull in tweets, show most recent X on landing page

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#829]
ensure layout blends with what we have on the site right now

**Comment by thierrylahaije** [comment]
This currently is a problem. I tried many ways, but due to the fact that Musk made everything paid in the new API, it is almost impossible to create a custom twitter widget. The only possibility would be to implement the basic twitter widget, but then we will not be able to adjust the styling...

**Comment by hannesdatta** [comment]
Hm... then we can cross-post using the new article/blog cards/articles #831. So, let's not try to directly embed tweets due to this problem.
