### ISSUE TITLE
second-level category overview page

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#830]
__Background:__

We currently serve only content to people who KNOW what content they want (e.g., "scrape with python").

What I now want to do is give people the option to 'discover' new content in particular categories.

Say, you're interested in data collections.

Right now, there is no such page that gives us an overview about the (a) tutorials, and (b) code snippets that one could use.

__Deliverable:__

- Build a "second-level landing page" where all the content relevant to our CURRENT categories is listed.
- The page should feature tutorials (e.g., cards), maybe a list of most recent articles, maybe a list of most read articles, [...] - in terms of style, use inspiration / reuse code from our current landing page
- Tech is important: do NOT let hugo decide what to show, but reuse our python script to generate the content for these category pages.
- We can "hard link" to these category pages for now in our menu
- Future vision is that we have a zillion of these pages, for any kind of search term that we (pre)-define.
- link articles BOTH with newly defined keyword (say `category`), but also ability to use directories from the building blocks that we have now
- description specific to the landing page

**Comment by thierrylahaije** [comment]
I have created a basic version of this. The pages now look like this (basic):

<img width="1347" alt="image" src="https://github.com/tilburgsciencehub/website/assets/65568251/ff1ad173-3eda-4879-89bf-f16409d0b62b">


The .md files are created by a python script, since hugo does not allow dynamic pages. The python script reads a specific .json file, extracts the specified "terms" (e.g. regression analysis), gets the related articles by NLP in title (will be extended by content check), and creates the .md file.

The json file looks as follows, making it very easy to add new terms.
<img width="581" alt="image" src="https://github.com/tilburgsciencehub/website/assets/65568251/ff3408ea-7112-44d4-986d-527b74df0d96">

**Comment by hannesdatta** [comment]
Hi Thierry,

looks like a good start!

Yet, I do not see where you put this into code.

Please link your branch in this issue so I can review it Including the HTML layout etc).

<img width="360" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/fc6f4814-6b3a-4a8d-a75e-e0d557632fcc">

**Comment by thierrylahaije** [comment]
@hannesdatta Sorry, I forgot to add the files to a new branch. I created a branch called 830-second-level which contains the code and files.

The following files and folders are added (if you want to review):
- content/custom-categories/
- scripts/categories.json
- scripts/categories.py
- themes/tilburg/layouts/custom-categories/

**Comment by hannesdatta** [comment]
- [ ] next time, @thierrylahaije - please link these branches in the issue itself - makes it easier to find. I have done it now. thx!

![image](https://github.com/tilburgsciencehub/website/assets/16557730/2c045c84-93fc-44b3-992a-712453aeb405)

**Comment by hannesdatta** [comment]
Great work, @thierrylahaije.

Let us now assign @NielsRahder and @fleurlemire to come up with a first visual mock up of what we want on these pages.

@fleurlemire - I have called Niels and explained in detail.

Deliverable:
- a mockup drawing with a topic-based landing page
- ideally blends in with existing designs we have on the site (e.g., card view)
- yet, it doesn't have to be a card view - it can be "anything" we can eventually generate, think about an infinity scroll of stuff, just to name it.
- also think about stuff we do not have yet

This needs to be a place for anyone wanting to learn more about...

cloud computing, web scraping, cleaning data, etc.

All of these topics need to have a "landing" page on our site, and you will be the ones coming up with an initial draft on how it will look like.

Sounds good?

Please plan a meeting with me to show me what you come up with.

Thanks!

**Comment by hannesdatta** [comment]
I will de-assign @thierrylahaije assigned as he will handle the technical implementation after we're done iterating on this.

@thierrylahaije, great work so far!

**Comment by lachlandeer** [comment]
Hey @hannesdatta -- is this still in progress? or the site update fixes it?

**Comment by hannesdatta** [comment]
This has been built and is implemented. Thanks everyone.
