### ISSUE TITLE
have announcements section on the site where we blog about developments

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#831]
+ show recent announcements on landing page (i.e., have  card that is sometimes or always shown)

**Comment by thierrylahaije** [comment]
I currently made a card for the announcements, just as the building-blocks:

<img width="1339" alt="image" src="https://github.com/tilburgsciencehub/website/assets/65568251/8507e898-7365-44df-b46e-7f0613775eef">

It practically works in the same way as the other cards. The announcements.md looks like this:

<img width="852" alt="image" src="https://github.com/tilburgsciencehub/website/assets/65568251/f33244d9-b975-41e3-b667-36cd7171a839">

We could also make it possible to let users set custom icons, are change the icon to another fixed icon of your choice.

**Comment by hannesdatta** [comment]
- Relabel to: "Blog" or "News".
- Please allow us to write the news in `.md` files, similar to how we do building blocks or tutorials. Right now, merely linking to external content isn't enough (although that option should also be there). Thanks!

**Comment by thierrylahaije** [comment]
I created a new branch called 831-announcements. This contains the updated announcements structure and layout. @hannesdatta can you please check it and let me know whether it is okay?

**Comment by hannesdatta** [comment]
Thanks for your work! Here are my requests:

- [ ] Show a publication date (as given in md of announcements) on top of the announcement page

<img width="691" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/609c684b-a529-42b9-b6f2-5eeebf23a890">

- [ ] Call announcements BLOG

- [ ] We need a "LIST OVERVIEW PAGE" for all announcements that we post.


<img width="163" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/bf95f7cd-3f8e-4d6b-a9a0-7d37227ae932">

- [ ] I would like you to remove the ANNOUNCEMENT card. we will have to find a better place to display them. For now, create a SUBMENU to the ABOUT MENU, and call this submenu BLOG.

- [ ] Link to this card here by splitting the block horizontally in two:
<img width="219" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/1c9c2c1d-1765-4031-af0c-b96979f5b689">


One is: get to our code snippets, the other one is: visit our blog.

Does it make sense?

**Comment by hannesdatta** [comment]
(the basic intuition is that I think the announcements are distracting on the landing page..., so, I rather showcase our content and LINK to the blog (we need the blog anyways).

**Comment by thierrylahaije** [comment]
I fixed all the issues except the following:

I would like you to remove the ANNOUNCEMENT card. we will have to find a better place to display them. For now, create a SUBMENU to the ABOUT MENU, and call this submenu BLOG.

@hannesdatta Just for me to clarify, you want a submenu like when you hover tutorials or like when you hover examples? Or what is your vision here exactly?

**Comment by hannesdatta** [comment]
@thierrylahaije - thanks!

Can you please
- [ ] ensure your code changes here are mergeable with the most up-to-date version of our site (in which we know have a new card structure because of #844)?
- [ ] in terms of menu: one that looks like the CONTRIBUTE menu (popping up when you hover over about), with items: About Tilburg Science Hub (/about), meet our contributors (/contributors), and visit our blog (/blog).
- [ ] show post publication dates at our blog post list:

![image](https://github.com/tilburgsciencehub/website/assets/16557730/928aa1c9-c95e-4821-b7e9-55e2f3ac787d)

After that, we're good to go!

**Comment by thierrylahaije** [comment]
@hannesdatta I updated the issues mentioned above. I changed the development branch (831-blog now) to make sure everything is mergeable.
