### ISSUE TITLE
add blog posts

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#846]
Hi @fleurlemire,

please check our recent updates in https://github.com/tilburgsciencehub/website/issues/831.

We will soon have our own Tilburg Science Hub blog, a place to feature important milestones, highlights of our project, etc.

The goal is to show to others more about our community, and to showcase the breadth of work that we do.

Can you please add the curation of this section to your list? Concretely speaking, share with me a list of proposed posts. We can start with dating back some to the summer (to fill it up a bit), and then, going forward, use this section regularly.

My goal is to have some action in that section once every two - three weeks.

@thierrylahaije will work on the last few technical issues. Please draft your posts using Google Docs. 

Once @thierrylahaije is done on #831 we can launch the section. Thanks!

**Comment by hannesdatta** [comment]
Hi Fleur,

we're done with the technical development of the blog.

__Now it's your turn to fill it with some content.__

Remember our goal: show others more about our community, showcase the breadth of work we do, etc.

I want this to be a page that Tilburg colleagues visit to understand what we've been up to, and kind of "meet us" without physically meeting us.

Maybe have posts on:

- This is our blog and what we plan to do. 
- Then a post on: we've been busy last semester developing content about causal inference (linkt o a few posts) and something else (link to that too). 
- and maybe a post on our recent hires and what we seek to do the next semester (focus on broadening content to different schools at Tilburg).

I'm happy launching it with two posts. And then going forward, you will add content here every 2-3 weeks or so.

Makes sense?

Thanks!

**Comment by hannesdatta** [comment]
__Deliverable:__

- at least two blog posts in branch `831-blog`.

https://github.com/tilburgsciencehub/website/tree/831-blog

Add them here:

https://github.com/tilburgsciencehub/website/tree/831-blog/content/blog as `md` files.

**Comment by fleurlemire** [comment]
Hi @hannesdatta, I added the md-files and opened a PR with the first two draft for possible blog posts.

**Comment by hannesdatta** [comment]
Can you revise, see comments in PR? Thanks!

**Comment by fleurlemire** [comment]
Yes, i will revise today or tomorrow! @hannesdatta

**Comment by fleurlemire** [comment]
Hi @hannesdatta , i added some new posts for the upcoming weeks: https://docs.google.com/document/d/1pErqMkXecg5k-Zhn2ofnUx71Wu7_1y6V2C1JbWQdw6M/edit
Do you want to take a look and give feedback or do you want me to add them as PR later on and look at it then one at the time?

**Comment by fleurlemire** [comment]
I added some small questions in the document for the blogposts about the post we made some time ago. Moreover I added questions about possible new posts that I can create? 
https://docs.google.com/document/d/1pErqMkXecg5k-Zhn2ofnUx71Wu7_1y6V2C1JbWQdw6M/edit
