### ISSUE TITLE
[Feature]: Adding timestamp on content

### ISSUE THREAD

**Issue by shrabasteebanerjee** [tilburgsciencehub/website#848]
### Is your feature request related to a problem? Please describe.

I feel that for some of the faster moving areas we write about (docker, chatgpt, etc), readers would want to know when the post was written and last updated. also an incentive for us to keep content fresh! Any ideas how to add a timestamp to BBs?

### Describe the solution you'd like

adding a timestamp and "last updated" flag to any content.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thierrylahaije** [comment]
I will look into this. Should be a simple task.

**Comment by hannesdatta** [comment]
Hi @thierrylahaije,

for those articles for which we DO want to show the dates, why don't we simply hard-code them in the header of the `.md` file?

date_published

and

date_updated.

Or do you want something else?

I'd say: why don't we just implement it. I'd love to see where you display the dates on the site. @shrabasteebanerjee  - any thoughts?

**Comment by shrabasteebanerjee** [comment]
This approach sounds reasonable! Anything that helps to keep track of when
stuff was changed/added is perfect.

**Comment by thierrylahaije** [comment]
I added this option, but it currently has some problems on mobile screens:
<img width="513" alt="image" src="https://github.com/tilburgsciencehub/website/assets/65568251/8dafb31c-e30e-41ca-b01c-7870b7b9f412">

On desktop, it works well:
<img width="1355" alt="image" src="https://github.com/tilburgsciencehub/website/assets/65568251/14e1bbde-1c80-48c8-8cb6-2b7fb75692e5">

Maybe an idea to change the mobile way of sharing? I thought if we change it to a share button, which then gives a pop-up, might be better for mobile devices. We can then combine the date and share button, which would fit for mobile devices.

We can also add the time if necessary.

**Comment by thierrylahaije** [comment]
@shrabasteebanerjee @hannesdatta feature is now implemented. We can now use date_published & date_updated parameters in the md's to display the date that the file is published or updated.

**Comment by lachlandeer** [comment]
closed with #948
