### ISSUE TITLE
[Feature]: Multilingual Website

### ISSUE THREAD

**Issue by thierrylahaije** [tilburgsciencehub/website#849]
### Is your feature request related to a problem? Please describe.

Currently, we are busy to make the website more attractive and interesting to the public, to make users come back to our website. Another thing we could also do to expand the amount of users, is increase the visibility to prospects (possible users). Currently, our website is only available in English. This does create a problem. Only people who search in English (and so speak/read English properly) will find our content via Google. This leaves a huge part of the world which cannot find our content (by statistics, it is about 75%), even though it might be very useful for them.

**Original Question I asked ChatGPT**:
If I add languages, for example, Spanish and Chinese to my website alongside English, will it increase organic traffic through Google?

**Answer**
Yes, adding additional languages like Spanish and Chinese to your website can potentially increase organic traffic through Google, especially if you are targeting audiences who speak those languages. Here are a few reasons why this can help:

- Reaching International Audiences: By offering multiple languages, you can make your website **_more accessible to people worldwide_** who speak those languages, potentially expanding your audience and attracting more potential visitors.

- Improved SEO: If your website provides relevant and high-quality content in different languages, it can enhance your search engine results page (SERP) rankings for people searching in those languages. This can _**increase the visibility of your website.**_

- Multilingual Searches: People looking for information in their native language often prefer to search in that language. Having content written in that language _**increases the chances of your website appearing in relevant searches**_.

- Enhanced User Experience: Offering content in multiple languages can improve the overall user experience of your website, potentially leading to **_more engagement and returning visitors_**.

### Describe the solution you'd like

We could try to add an additional language, for example Spanish, to test and see the effect on our overall visitors. This could be done via a Python script using DeepL.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
Hi @thierrylahaije.

The idea is interesting, but I'm giving it a pass for now. The reason is that we don't have anyone onboard that would be able to check whether the site actually is properly translated. Users of a different language can simply use Google translate for now. We also need to keep in mind the research community we're targeting is largely English-based.

So, while it's good to offer content in native languages, I think we simply can't provide that service at this stage of our growth.

@shrabasteebanerjee and @lachlandeer, what do you think?

**Comment by lachlandeer** [comment]
Agreed that for now this doesnt feel like a priority

Even software carpentry (which has a HUGE) number of contributors only has a small set of dual language stuff.
