### ISSUE TITLE
Replace FontAwesome

### ISSUE THREAD

**Issue by thierrylahaije** [tilburgsciencehub/website#855]
Currently, we are using my FontAwesome free account, which has limits (max 10k views per month). I think we should buy the pro plan of FontAwesome for TSH. It's $100 per year and it gives us a lot of possibilities:
- up to 1 million views per month.
- easily add icons anywhere (such as the icons in the cards).
- more than 26k icons (the free version only has 2k icons, which are quite limited).
- add our custom icons to FontAwesome: the pro plan also enables us to upload our icon svgs to fontawesome, and add them to the website using an <i> tag with a specific class instead as a separate svg or image. This reduces the overall serverload of website.

@hannesdatta what do you think, do you want to use the free or paid version? And could you set up the account (either free or paid)? Since I do not have access to any TSH email accounts.

**Comment by hannesdatta** [comment]
Replaced with our own one. Done.
