### ISSUE TITLE
Master Thesis guide 

### ISSUE THREAD

**Issue by alexandervossen** [tilburgsciencehub/website#866]
### Is your content request related to a problem you've encountered during your research process? Please describe.

As mentioned in the weekly WOW I am looking for someone to help me expand the great guide Hannes provides for his students on his site https://thesis.hannesdatta.com/. My idea would be to build on the same structure, expand a couple of aspects and generalize it to other topics in management beyond marketing. Ideally, in a second later step we would expand that to other social sciences and computer science. 
Assign yourself if you have some time! 

### Would you like this to be a Building Block or a Tutorial?

Tutorial

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
Closed via #1002
