### ISSUE TITLE
[Bug]: contributor page profile pics

### ISSUE THREAD

**Issue by shrabasteebanerjee** [tilburgsciencehub/website#868]
### What happened?

The halo around the profile pic seems to be a bit off for some profiles (e.g mine and Alex's) :) Perhaps we make it static/remove it?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexandervossen** [comment]
This also extends to the overview page (at least n Safari) where my pic is a bit smaller and Shrabastee's is a bit larger.

**Comment by hannesdatta** [comment]
@alexandervossen - pls provide a screenshot and exact browser user agent so @thierrylahaije can reproduce and fix. thanks

**Comment by alexandervossen** [comment]
@hannesdatta I had issues uploading the screenshot here, but I sent a mail to @thierrylahaije with the browser infos as well :)

**Comment by thierrylahaije** [comment]
@hannesdatta @alexandervossen bug fixed in PR #877.
