### ISSUE TITLE
fix Valerie's pic

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#872]
Hi @thierrylahaije - can you check why Valerie's pic doesn't render?

<img width="280" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/5b8311cc-ae97-40b0-9e52-e67e19fcffc9">

**Comment by valerievossen** [comment]
I do get to see the picture when I open the contributors page (on the page with everyone as well as my personal page), is it still not showing @hannesdatta ?

**Comment by hannesdatta** [comment]
Yes! Sorry. I don't know what went wrong here. It's there.

**Comment by hannesdatta** [comment]
Thanks!
