### ISSUE TITLE
[Development Call]: OpenAI's OPEN CODE INTERPRETER

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#874]
### Contact Details

h.datta@tilburguniversity.edu

### Is your content request related to a problem you've encountered during your research process? Please describe.

We need to feature open AI's open code interpreter! 

Can we have a building block on how it eases
(a) working in the terminal,
and
(b) coding up a web scraping project?

### Additional context

Got this email from an alumni:

> I hope everything is going well in the new semester. This week, I came across something quite interesting that I thought you might also find "cool”. It's possible you've already seen it since it's trending on Github, but since it was just recently released, I wanted to share it with you in case you haven't seen it yet. It's called "Open Code Interpreter," an open-source code interpreter that can be run locally on your computer.
 
> You can check out a video demonstration of it here: https://twitter.com/hellokillian/status/1699156860073640038?t=fyBy3PabxpYK5BTapB6hzg&s=19
 
> I've already tested it, and it can even scrape websites using Beautiful Soup through text commands.
 
> Additionally, you might want to watch this YouTube video to see how it works and what it can do: https://www.youtube.com/watch?v=7KFbG_3dKKs
 

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Purpose

Help programmers and researchers use the terminal and other coding languages easily.

### Motivation

Terminal is sooo hard to learn - maybe this makes things much faster. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NielsRahder** [comment]
@hannesdatta this looks really promising. I will definitely dive into this!
