### ISSUE TITLE
[Bug]: Fix Action fetch-popular-pages-ga

### ISSUE THREAD

**Issue by thierrylahaije** [tilburgsciencehub/website#878]
### What happened?

Action called fetch-popular-pages-ga is currently not working successfully. It generates an error in the .py script.

### To reproduce

To reproduce, check actions tab and click the fetch-popular-pages-ga action.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thierrylahaije** [comment]
I cannot get this error fixed for some reason... The action says the following:

```
Run python scripts/main.py
Traceback (most recent call last):
  File "/home/runner/work/website/website/scripts/main.py", line 315, in <module>
    main()
  File "/home/runner/work/website/website/scripts/main.py", line 296, in main
    os.chdir(root_folder)
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/website/static'
Error: Process completed with exit code 1.
```

Which should be in this line:

```
# Navigate to the root folder (one level up from the current notebook file)
    notebook_path = os.path.dirname(__file__)
    root_folder = os.path.join(notebook_path, 'static')
    os.chdir(root_folder)
```

I tried different ways to set the root folder, but for some reason, the action expects an additional '/website/' for some reason, which I cannot understand. Need to investigate this further.

**Comment by hannesdatta** [comment]
We're retiring GA.
