### ISSUE TITLE
Create aisle sign designs

### ISSUE THREAD

**Issue by fleurlemire** [tilburgsciencehub/website#882]
Please use the template (see email) and make it “Tilburg Science Hub”-ish (our design)?

Think about a call to action for researchers and teachers on how to use Tilburg Science Hub.
Something like: Use google cloud for research, Etc.

Think of it as show-casing some of our content.
Let us plan to have an update every week (so create four versions for a start).

We can then ask the secretaries to display this.

**Deliverable**: one template that we can use, deliver four different versions

**Comment by hannesdatta** [comment]
Any update?

**Comment by fleurlemire** [comment]
I am working on it, but have no time anymore today so i will update you at the latest monday on this and more @hannesdatta

**Comment by fleurlemire** [comment]
Hi Hannes,

I made a list of quotes/call to actions we could possibly use. Please let me know what you think of these. Then I can workout the ones you agree with in the format.

I made for one quote already some versions of designs:
- One with logo, quote and a visual of the subject
- One with logo, quote and representation of a BB of that subject on our website
- Two with logo, quote and representation of a BB of that subject on our website and QR code people can scan to go to our website
- One with logo, quote and representation of a BB of that subject on our website and visual of subject (in this case google cloud logo)

Everything is added in here: https://docs.google.com/presentation/d/16iQjMozYlXxHLCePun_FMwzGNzU8uP4VE647dYMcO7c/edit?usp=sharing

Please also let me know what is preffered or if you prefer something else and this is not what you had in mind. 
If I know your preferences for quotes and designs, I will implement this for four different versions.

**Comment by fleurlemire** [comment]
I added multiple designs:
https://docs.google.com/presentation/d/16iQjMozYlXxHLCePun_FMwzGNzU8uP4VE647dYMcO7c/edit#slide=id.g29e63fcd122_0_90

Please let me know what you think and which "quotes"/subjects we can use and what not.

**Comment by hannesdatta** [comment]
Done!

**Comment by hannesdatta** [comment]
I love the design.

The screens need to become a little more advertorial.

![image](https://github.com/tilburgsciencehub/website/assets/16557730/8d99ebbb-a0d9-413a-970c-d7a7e103eb65)

For example, use as header here:

"Already using GitHub? Use it to automate code formatting and testing"

Find out how to use GitHub Actions at tilburgsciencehub.com/learn/actions (ensure link works/is available)

+ provide QR code.

Can you revise accordingly?

**Comment by fleurlemire** [comment]
@hannesdatta 
I added QR codes. Do you also want the url to the specific topics in the graphs? Because they are quite long (e.g. https://tilburgsciencehub.com/topics/automation/automation-tools/makefiles/what-are-makefiles/) or is the QR code enough with the url to the website itself? 
I also changed the headers. I hope this is more what you had in mind, if not, please let me know, then I can revise again.
