### ISSUE TITLE
[Development Call]: Interpreting regression output

### ISSUE THREAD

**Issue by valerievossen** [tilburgsciencehub/website#885]
### Contact Details

v.a.p.m.vossen@tilburguniversity.edu

### Is your content request related to a problem you've encountered during your research process? Please describe.

A short building block about interpreting the regression output in R, to give guidance in interpretation of estimate, standard errror, t-value, and significance stars.

Screenshot of example regression output and then interpret each part one-by-one.

### Would you like this to be a Building Block or a Tutorial?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
hey @valerievossen 

Did any progress get made on this one?

**Comment by valerievossen** [comment]
No, will work on this the upcoming week! @lachlandeer
