### ISSUE TITLE
scripts legit?

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#890]
<img width="279" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/7f7a60bc-1a1a-4354-866f-b5cf0c42d094">

@thierrylahaije  - I noticed we're loading some scripts from this URL. Is this legit?

**Comment by thierrylahaije** [comment]
I checked what it was, and it is a script for animated typing. One of the old pages contained some sort of a "bash terminal". There the script was used, but I am unsure whether this so to say terminal is still active somewhere in our website. Do you know this maybe ? @hannesdatta
