### ISSUE TITLE
[Update request]: XGBoost

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#901]
I kindly request the update of our new building block on XGBoost, available at https://tilburgsciencehub.com/building-blocks/analyze-data/machine-learning/xgboost/.

My major concern is that it's a bit "bumpy" in terms of language, and I did not have the time to test whether it works/whether everything is clear.

Therefore, I ask @shrabasteebanerjee to assign a new RA to this review request, preferably one with some ML experience. I think this request is particularly suitable to a new RA together with a buddy. Do complete the entire checklist please. In case of questions, please reach out.

# Request to update content

__Background__

Content (building blocks and tutorials) has been developed over many years by different RAs and faculty members. Our platform has also undergone continuous technical development, resulting in varying content quality, with some never being revised.

The purpose of this issue is to test and update existing content, aiming to improve its quality by enhancing user experience, reflecting the latest tools or versions, and improving clarity and accuracy.

__What needs to be updated?__

- Please briefly describe here which building block/tutorial (links) or which section of the website needs to be updated.

__Deadline__

- Is there a specific deadline?

## Checklist

__IMPORTANT:__ Before starting, ensure you are familiar with our [style guide](https://tilburgsciencehub.com/tutorials/more-tutorials/contribute-to-tilburg-science-hub/style-guide/). Also, please read some of our content on the site to get familiar with the style. 

*See this checklist below for what needs to be done.*

### 1. "Do" the content

A first reality check can be conducted by actually WORKING with our content. Just read the building block or tutorial from the perspective of a new user.

Ask yourself the following questions:
- [ ] a. Is it clear what you will learn after reading the building block?
- [ ] b. Is the language professional and transparent, or does the content come across as amateurish?
- [ ] c. Do you run into any issues when working on this building block or tutorial? Are the visuals clear? 

Write down any weird things you want to fix, and keep these notes.

### 2. Consider the checklist below and complement your initial check with these (more formal) dimensions

- [ ] **Keywords and Metadata:**
   - Ensure we have complete metadata in our `.md` files - sometimes, keywords were only loosely entered. Can you expand them? Also, use ChatGPT or similar AI tools to generate relevant other keywords.
- [ ] **Section structure and learning goals:**
   - Identify a few (say, 1-3) learning goals/objectives of the building block or tutorial, and highlight them at the start.
- [ ] **Title and Headings within the Content:**
   - Update titles and headings to create a clear and descriptive language that accurately reflects the content's focus. Ensure to the correct capitalization.
- [ ] **Grammar and Style:**
   - Use Grammarly, ChatGPT, or other language proofing tools to review and correct any grammatical errors or writing inconsistencies in the content.
- [ ] **Use of Code Tabs and Comments:**
   - Check that the code that is most optimally presented in a code box is included in the code box.
   - Check whether the code is sufficiently annotated/commented.
   - If software packages are missing from the code tab (e.g., Stata, R, Python) and you have the expertise, you can add the implementation for the other software packages as well. 
- [ ] **Use of Explanation Boxes:**
   - Ensure that explanation boxes are used effectively where necessary (e.g., info, warning), providing additional context, tips, or warnings to the users.
- [ ] **Have a Summary Box at the end:**
   - For more complex content, you can briefly recap the key lessons learnt in a summary box toward the end of the article.
- [ ] **Media and Visuals:**
   - Review and update images or screenshots to enhance the understanding of the content.
   - Add new visuals where this is needed.
   - Add proper image descriptions for accessibility. 
- [ ] **Links and References:**
   - Verify that all links and references are still valid and point to the correct resources. Use persistent links where possible.
- [ ] **Version Compatibility:**
   - Ensure that the content is compatible with the latest versions of relevant software packages and tools.

### 3. Work on your changes and commit/do a PR (for testing and reviewing)

- Now you have a good idea of what you need to fix. Create a separate branch for your update, and commit frequently while doing your changes.
- Ask another RA to check your update and identify any other inconsistencies/problems.
- Make a pull request once the content is ready for review.

Remember to create separate branches for each update and submit pull requests once the content is ready for review. Let's collaborate and ensure Tilburg Science Hub is even more valuable for our community.

**Comment by shrabasteebanerjee** [comment]
@hannesdatta Niels wanted to do another pass on this, so I'll hold off a few more days - we can assign more folks if further elaboration is needed after that

**Comment by hannesdatta** [comment]
Great to hear! Let me know when it's ready for review.

**Comment by lachlandeer** [comment]
closed with #922
