### ISSUE TITLE
[Development call]: Forest plot generation in R

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#909]
__Background:__  
Forest plots provide a comprehensive way to visualize results from various studies or groups. It's super important to check robustness of own results (when running multiple studies), or by analyzing others' work. 

By allowing for a clear comparison of effect sizes and confidence intervals, they offer intuitive insights that raw numbers often fail to deliver.

Check how to generate them yourself. Are there preferred packages?
 
__Deliverable:__  
- Overview: the intuition behind forest plots. Discuss benefits. 
- Detailed steps to create forest plots in R (using some simulated data)

**Comment by shrabasteebanerjee** [comment]
Hi Matteo, may be interesting for you to work on this once you are done with #832 ? Just putting it here for reference :)
