### ISSUE TITLE
[Development call]: Stylizng bar charts in ggplot2

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#910]
__Background:__  
Effective data visualization requires not just accuracy but also aesthetics. The `ggplot2` package in R is a versatile tool, but many users struggle with custom styling.

__Deliverable:__  
- Building Block: "Styling Bar Charts in ggplot2"
  - Step-by-step guide on customizing color, theme, and labels.
  - Demonstrating various styles suitable for different data scenarios. Particularly zoom in on use in academic papers. Standard errors/error bars. Black-and white or greyscale formatting. How to use grouping. How to save as publishable PNG or PDF.

**Comment by hannesdatta** [comment]
Yes - check what we already have on the site but it definitely needs to be there. High quality graphs, greyscale for papers, etc. Also use ggsave. Happy to review a first draft.

**Comment by MatthijstenTije** [comment]
- Added first draft for "Stylizing Bar Charts in ggplot2" in branch #910-Stylizng-bar-charts-in-ggplot2 
- Introduced two additional building blocks:
         - One to explain the workings of ggplot2: "Grammar of Graphics of ggplot2"
         - Combining Analysis and Visualization in R with ggpubr and rstatix 
The first one addresses the required knowledge of ggplot2, but this was still missing on the site. 
The second one avoids overlength in the initial draft. However, it also seems natural to be a BB in itself.

**Comment by MatthijstenTije** [comment]
@hannesdatta 
Sorry for the tag, just to make sure you are seeing the previous message. Feel free to review.

**Comment by hannesdatta** [comment]
Hi @MatthijstenTije, EXCELLENT work. I love Grammar of Graphics, and I also didn't know about ggpubr and statix. Excellent. Really.

When working on future content, please do not use "building block" anymore but refer to articles. This will align better with our updated site structure. I also noticed you did not consistently use `packagename` in code quotation marks. You need to do this always, also functions, except when used in the TITLE of your article. The use of ` in subheaders within an article is fine. Finally, please do not use the First Person Singular ("I"), but always use the collective version ("We"). Even though you develop content for TSH, you do this for the collective entitity TSH (while still remaining the author of the article, of course).

My only request to you is to carefully read the articles again (USE the current master branch and the live version of the site). DO NOT work in your old branch (I had to port it to the new structure). When reading, please think about whether you can add/it is useful to add more screenshots here or there. I found grammar of graphics excellent, but the other two articles were mnissing a bit of screenshots, just to improve the flow of them.

THANKS so much! Again, I learned so much reading these!

@fleurlemire - worthwhile promoting ggpubr and grammar of graphics - it's super useful for thesis students.

**Comment by MatthijstenTije** [comment]
Hi, @hannesdatta. Thank you for the positive feedback. Nice to hear you liked the building blocks. I'll make sure to reference articles instead of "building blocks" and consistently use code quotations for package names and functions, and at last. I'll avoid first-person and use the collective "we" in future content.

I will review the articles on the current master branch for possible additional screenshots.  

Appreciate the help and feedback!
