### ISSUE TITLE
[Development call]: Creating Qualtrics Surveys & exporting data to R, Python and Stata

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#911]
__Background:__  
Qualtrics is a widely used tool for creating online surveys. Integrating its results with statistical software is crucial for further analysis.

__Deliverable:__  
- Building block with a step-by-step guide on setting up a Qualtrics survey.
- Instructions to export data to R (followed by Python and Stata).
- Potentially using the RQualtrics package.

**Comment by matteozicari** [comment]
@shrabasteebanerjee @hannesdatta I could work on this one after I'm done with #909. Let me know if that's fine!

**Comment by shrabasteebanerjee** [comment]
Yes this will be valuable, please go ahead! You have access to Qualtrics
through TiSEM, let me know if you have trouble logging in.
