### ISSUE TITLE
[Development call]: Mediation Analysis Tutorial in R

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#912]
__Background:__  
Mediation analysis helps in understanding the mechanisms behind observed relationships. A straightforward guide on this is valuable for many of our users.

__Deliverable:__  
- Overview of what mediation analysis
- Reviewing key principles behind mediation analysis.
- Step-by-step tutorial using example data or a public dataset.
- Interpretation of results.

@shrabasteebanerjee, maybe check w/ some CB colleagues (e.g., Rik) to get a good idea of what is required here to begin with.

**Comment by MatthijstenTije** [comment]
Good evening, 

I have made the tutorial about mediation analysis. However, I still have some questions:
- I have used a dataset, that I have used in class, which is a cleaned version of the original version the authors uploaded online. Would this cause any problems?
- I have for now put it into the building blocks, of analyzing data, as I did not know where to put it on the site. Any ideas for it? 

Looking forward to the feedback! 

Kind regards, 
Matthijs
