### ISSUE TITLE
 [Development Call]: Decision Tree Algorithm and it's implementation in Python 

### ISSUE THREAD

**Issue by K-sohooli** [tilburgsciencehub/website#968]
### Contact Details

Kheiry.sohooli@gmail.com

### Is your content request related to a problem you've encountered during your research process? Please describe.

I am working on the XGBoost building block right now, and I noticed there is no building block for the algorithms that are fundamental to understanding XGBoost algorithm. One of these algorithms is Decision Tree.

### Would you like this to be a Building Block or a Tutorial?

Building Block

### Purpose

a building block could be added to the platform to explain the concepts of decision tree and it's implementation. Then it is possible to link the relevant part of XGBoost building plot to the decision tree building block to comprehend the concepts much better. Besides, the decision tree algorithm itself is a powerful algorithm and have a wide range of applications. 

### Suggested title

Decision Tree algorithm and implication in Python 

### Required tools

Python 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
done in #1182
