### ISSUE TITLE
revise Copilot tutorial

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#982]
@alexandervossen had provided feedback on the GitHub Copilot Tutorial, now available at https://tilburgsciencehub.com/learn/copilot/?utm_campaign=referral-short. I felt it was ok to go ahead publishing the tutorial now itself. 

Do take the time to see whether all the feedback that @alexandervossen gives below has been implemented. Thanks.

> Thanks @VirginiaMirabile! I also had a look at it after I rendered it locally. I would also say it is worthwhile to expand the text a bit, especially in the intro.  Offer some more use cases and get people curious on how to set it up.  Why not ask copilot to write a tutorial on itself for some inspiration? 
> In general I like the direction the tutorial is going, but you can also be a bit more descriptive on what you are doing in the code and why you are doing it. I would also encourage you to provide some more practical examples. For example you can ask copilot to make a bar chart of the fertility variable in the swiss data and then in a second step ask it to change the colours. This way readers get an intuition on how easy it is to chnage all the little tweaks that make dealing with a powerful but complex package like ggplot challenging. I would also use a dplyr example - let copilot suggest for example to aggreagte and sort something - this way readers also see the benefit of not having to go to the documentation again and look for the right command. Does that make sense? A

_Originally posted by @alexandervossen in https://github.com/tilburgsciencehub/website/issues/972#issuecomment-1812763365_

**Comment by lachlandeer** [comment]
updated in #1038
