### ISSUE TITLE
[Feature]: GitHub copilot in VSCode

### ISSUE THREAD

**Issue by alexandervossen** [tilburgsciencehub/website#987]
### Is your feature request related to a problem? Please describe.

VSCode offers the best integrated interface for copilot and we also recommend as our text editor of choice. So a tutorial on how to set it up and get the max out of it would be very useful. 

### Describe the solution you'd like

The name says it all :) @matteozicari  and @VirginiaMirabile  can you help? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteozicari** [comment]
Hi @alexandervossen , I'm currently working on bb #911 and will start working on a new issue on interpretation techniques for machine learning predictions really soon. It'd be great if someone else could do it! Keep me updated though!!

**Comment by alexandervossen** [comment]
@VirginiaMirabile given the great success of the Rstudio guide may you want to help with this here as well? Then we could get this rolling :)

**Comment by lachlandeer** [comment]
hi @alexandervossen @VirginiaMirabile 

Is there a status update on this?

**Comment by alexandervossen** [comment]
Its done
