### ISSUE TITLE
optimizing mobile site

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#992]
In Google's Search Console, I discovered our site is amazingly well optimized for desktop, but not for mobile.

Let us see what we can do about it.

![image](https://github.com/tilburgsciencehub/website/assets/16557730/e44854b7-e3e6-449a-a1e0-9837b915604f)

![image](https://github.com/tilburgsciencehub/website/assets/16557730/22cf40c4-ac09-44c7-ba04-5775c2cf7422)

![image](https://github.com/tilburgsciencehub/website/assets/16557730/3aa6d101-0917-4763-9f16-cecbe6e71062)

**Comment by thierrylahaije** [comment]
@hannesdatta issues tackled in branch bugs-optimizing.

**Comment by thierrylahaije** [comment]
Main problem we currently have is the loading time of certain cdn's that seem overloaded. These include the following:

- Jquery (highly important)
- TypeKit
- Fontawesome

In our case, I think either one of the following will probably be the best:

1. Self host files: Effect is dependent on the server. If the server speed is high enough, this should fix the problem.
2. Create own CDN: Use a self distributed CDN that hosts jquery, typekit and fontawesome. -> Costs money, so advice is to first try option 1.

If your okay with this, I will continue with option 1 first to test the effect on the web performance

**Comment by hannesdatta** [comment]
@marijnbransen1998 - is mobile still an issue?

**Comment by thierrylahaije** [comment]
Now we are on flask, everything seems quite fine (mobile 80/100, pc 90/100). But we still have an FCP of 2.8s

Google says that, to provide a good user experience, sites should strive to have a First Contentful Paint of 1.8 seconds or less. This means on mobile there is room for some improvement. Coming week I am going to do some minor adjustments to images and the way certain elements load, which further improve the performance to an FCP below 2s.

**Comment by hannesdatta** [comment]
I think we need to explore this in two ways: getting the server to respond faster (probably a deployment thing on my side, comments appreciated!), and within-site stuff (@thierrylahaije). It would be great to set it up in a way that makes the site "self-maintainable" (e.g., suppose you use some image compression or something, we should have a script that scans the repos for "shitty" formats and automatically converts these and adjusts files or something like that). Anyway, make it "self-maintainable" as much as you can.

**Comment by thierrylahaije** [comment]
The following things still need to be tackled within flask:

Speed:
- [x] Image compression (automatic or manual?)
- [x] Check for unused CSS

Accessibility:
- [x] Button names
- [x] HTML language element

Indexing:

- [x] Sitemap.xml

**Comment by thierrylahaije** [comment]
Auto images compression is now added, all images are automatically converted to webp (the best web format available). Furthermore I decreased the size of javascript by almost 50% by moving parts to python and removing old unused functions, which decreases both FCP and LCP. I will test the pagespeed as soon as the server is updated and I will then add screenshots of the actual performance of the website. 

One thing we could still look into to improve speed is whether we need all bootstrap parts. Quite often, multiple files are not used and imported for nothing. I will look into this as one of the final issues.

**Comment by thierrylahaije** [comment]
I have updated a lot of things to improve the speed and I now acquired the following results:

On PC (overall went from 76 to 97 out of 100):
<img width="950" alt="image" src="https://github.com/user-attachments/assets/fc12abfb-0545-4129-8b21-e019821fb2bd">

On Mobile (overall went from 62 to 78 out of 100):
<img width="950" alt="image" src="https://github.com/user-attachments/assets/0a69fe8b-672c-4495-b284-aa500ebb409f">

@hannesdatta Now everything is as optimized as it can be. The last thing you can do is try to increase the server capabilities to get the mobile speed below 2.5s (research recommends 2s, which is difficult to acquire without 100% customization). 

Overall I tested the real life stats on my phone and laptop and the website was super fast!
