### ISSUE TITLE
[Development Call]:  Literature research using the SCOPUS API

### ISSUE THREAD

**Issue by alexandervossen** [tilburgsciencehub/website#995]
### Is your feature request related to a problem? Please describe.

Chatgpt says about the problem: 

This tutorial addresses the challenge researchers and students face in accessing, extracting, and analyzing extensive scholarly data efficiently. It streamlines literature reviews, enables customized data analysis, and bridges the technological proficiency gap, empowering researchers to derive valuable insights and optimize their research processes using the Scopus API.

### Describe the solution you'd like

Chatgpt recommends the following solution: 

The solution, in this case, would be a comprehensive tutorial within Tilburg Science Hub's resources. It would provide step-by-step guidance on utilizing the Scopus API, including accessing data, extracting relevant information, performing analyses, and customizing data retrieval to meet specific research needs. The tutorial might consist of practical examples, code snippets, and best practices, empowering researchers to proficiently navigate the API for their scholarly pursuits. Additionally, it could offer guidance on integrating this extracted data into various research workflows effectively.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VirginiaMirabile** [comment]
Hi Alex, is someone already working on this or can I take this project? Seems really interesting and could be helpful for my upcoming thesis!

**Comment by alexandervossen** [comment]
No it is not taken so far- great! Let me chat to Tom & Gergo about this.

**Comment by gbocsardi** [comment]
Hi Virginia, glad to see you'd like to contribute! Here's a brief outline of the functionality I have imagined for the code (with level of completion as of now):  

### Getting a batch of papers into Python 

I have code to create proper queries from keywords, for example a list of keywords. This can help to piece together long queries without doing it in the Scopus UI. 

A colleague of mine also showed me a clever way to download the results of a search on Scopus using the UI, which bypasses API limits, and so can be very useful when the API quota runs dry. :D

### Keyword matching on an existing batch of papers
After having the batch of papers in Python, we can do various forms of keyword matching on their titles and abstracts. I have code for doing simple string matching from a list of keywords, and also giving a frequency distribution of the keywords in the batch. 

I have wrote a semantic matching, which uses a Word2Vec embedding to create "meaning-vectors" from both the keywords and the papers, and uses cosine similarity to determine whether the keyword and the paper match.

I have some code for a topic modeling, but it's pretty elementary for now, perhaps @tomhackenberg can help.

### Digging into the references of the papers
This is where the fun begins. I have code that queries the [Abstract Retrieval API](https://dev.elsevier.com/documentation/AbstractRetrievalAPI.wadl) and gets *very* detailed information about a paper, including the full list of references.

I have the code to generate an "edge-list" from a batch of papers, that is a list of pairs when a paper cites another. This can be used to build a citation graph on top of the batch, with the papers as nodes and citations between them as edges. 

This is where I am currently standing, I have some very basic R code to generate the network, but there are some issues there that I need to straighten out still.

## Todos
1. As you can see, this is still pretty chaotic, so coming up with a good structure for a tutorial is a must
2. Finishing up the R code for the graph (I'll do this one, just listing it for the sake of completeness)
3. Coming up with any other usecases that might come up in a lit review, so we can cover those too.

With all these details still, does this sound like something you'd be interested in?

**Comment by alexandervossen** [comment]
Sounds like a plan! @VirginiaMirabile do you agree?

**Comment by VirginiaMirabile** [comment]
Hi, yes seems very interesting indeed! Its my first time working with this topic so maybe i'll contact you if some things are not clear. Is there a way i can see what you've already worked on in order to brainstorm on the "to dos"?

**Comment by gbocsardi** [comment]
It's part of a paper's development, so I'll check how I can share it best, perhaps a separate Github repo, where I can develop the code without sharing the data. @alexandervossen any other ideas on how best to do this?

**Comment by alexandervossen** [comment]
Lets do a joined call next week!

**Comment by gbocsardi** [comment]
Hi, sorry for the delay, got a little swamped, should we do a call next Friday (26th), say 15-16?

**Comment by VirginiaMirabile** [comment]
Perfect, that works for me!
